### PR TITLE
Create silx.io.open

### PR DESCRIPTION
**Pull request by vallsv**

### CODE REVIEW

**Comment by PiRK** [comment]
This seems to conform with what we discussed during the silx meeting. I suggest we merge the PR and let history judge the consequences.

**Comment by dnaudet** [comment]
Hi!
What about file access mode? And how about making a context manager?
(I don't know the if this is supposed to be an internal function or not so ignore my questions if they're out of scope)

**Comment by t20100** [comment]
+1 for with statement support.

I guess there is no access mode because for the previous load function naming, you'd expect read mode only..

**Comment by vallsv** [comment]
Access mode and context manager are not part of this patch. We can open a bug for the context manager, i will take care of it for fabioh5.the mode IS supposed to be read-only (but no idea if there is different read mode on hdf5)

**Pull request merged**
