### PR TITLE
Intensity histogram action enhancement

### PR DESCRIPTION
**Pull request by payno**

### CODE REVIEW

**Comment by payno** [comment]
I still have an issue when guessing the number of bins. If it is a B&W image, he will try to fit with a number of bins of 516 and many interval will be empty. 
This gave a bad looking output

outputhisto

**Comment by payno** [comment]
To solve the number of bins in a B&W image: adding a (bad) hack. Checking if type is integer and if minVal==0 and maxVal==255

**Comment by payno** [comment]
For now it is missing : 
   - should we lock the possibility to change the line type from the button ''change curve line and marker style"
   - error is not displayed
   - some optimization by removing a fiew loops

**Comment by vallsv** [comment]
Looks fine.

**Comment by payno** [comment]
closes #394

**Pull request merged**
