### PR TITLE
[specfile tests] Close specfile objects

### PR DESCRIPTION
**Pull request by PiRK**
This PR closes files properly in tests, so that we don't need to call `gc.collect()` before deleting the test files.

There is still a problem with `test_spectoh5`, caused by `convert(self.spec_fname, self.h5_fname)`. This line still requires a `gc.collect` for a reason unknown.

### CODE REVIEW

**Comment by PiRK** [comment]
The issue with `test_spectoh5` and `convert` is that it uses `silx.io.open`, which has a known bug: it tries to open the file with FabIO first, then with SpecH5, and the first attempt keeps a file handle.

This will be fixed with the next FabIO release. In the meantime, we need to continue calling `gc.collect`.

**Comment by vasole** [comment]
Tests are failing.

**Comment by PiRK** [comment]
I forgot to test Python 2. It seems Python 3 is more permissive than Python 2.
Now it is fixed.

**Comment by vallsv** [comment]
LGTM. Nice clean up.

**Pull request merged**
