### PR TITLE
math module

### PR DESCRIPTION
**Pull request by dnaudet**
Adding the math module to silx.

### CODE REVIEW

**Comment by kif** [comment]
Question: does the PR trigger the continuous integration ?
the code looks good  to me but it would be cool to have green light for merging (i.e. no test broken & documentation builds)

**Comment by dnaudet** [comment]
It looks like it does trigger it.
In the PR list there's a green tick next to the PR. If you click on it you can see the results (build and conflicts).

**Comment by t20100** [comment]
Travis (for Linux, python 2.7, 3.4, 3.5 and Mac OS X, python 2.7) and appveyor (Windows, python 2.7 and 3.5) are watching the project since previous PR.
But nothing is testing the doc is actually building...

**Comment by payno** [comment]
Looks good to me

**Comment by t20100** [comment]
The authors are the physical persons writting the code, which is not necessarily the person that did the commit, so we are adding a __authors__ field.
During your work hour, the copyright owner is your employer cited in the license header.

**Pull request merged**
