### PR TITLE
[plot] Add square amplitude mode to ComplexImageView

### LINKED ISSUE #1503: [silx view] visualization images of complex numbers
The new control for displaying amplitude, phase, etc. of an image of complex number is very good!

I would like to ask you to add a new entry "square amplitude"  |A|**2 This represents intensity when the complex number is an amplitude (wave, electric field, etc).

Thanks,
 
Manuel

### PR DESCRIPTION
**Pull request by t20100**
This PR adds an extra mode to visualization of complex in the plot (and the data viewer).

Closes #1503

### CODE REVIEW

**Comment by vallsv** [comment]
LGTM

**Comment by vallsv** [comment]
Juste a little think, the ComplexView must also patch SQUARE_AMPLITUDE. It can be done alter this PR.

**Comment by vallsv** [comment]
Sorry, it was already done.

**Comment by t20100** [comment]
DataView has already been updated.

**Pull request merged**
