### PR TITLE
Colormap arcsinh normalization

### LINKED ISSUE #2133: [silx view] Provide arcsinh as colormap
This feature is available internally, but not yet provided to the GUI.

It could be useful to implement it for the next release.

Feedback from Peter ID16A.

### PR DESCRIPTION
**Pull request by t20100**
Merge PR #3054 first!

This PR adds `arcsinh` normalization to colormap normalizations.

closes #2133

### CODE REVIEW

**Comment by t20100** [comment]
Added a fix that seems to be related to issues in merge of previous PRs

**Comment by vallsv** [comment]
Do you think you can subdivide the colorbar as it is done for log? It could make the result better.
If you dont have time, it's fine to merge it.

**Comment by t20100** [comment]
I opened issue #3062 for the `ColorBar` ticks placement.

**Comment by vallsv** [comment]
LGTM

**Pull request merged**
