### PR TITLE
Misc.: Use github action to run CI on linux and macos

### LINKED ISSUE #3272: Consider using azure pipeline for CI

### PR DESCRIPTION
**Pull request by t20100**
closes #3272

### CODE REVIEW

**Comment by t20100** [comment]
CI working with github actions for linux, macos and windows.
It seems, it needs to be on master branch to start working, so for looking at the result, see on my fork: https://github.com/t20100/silx/actions/runs/499115931

Here is the matrix of effectively tested features:

os | GUI | OpenGL | OpenCL
-- | --- | ------ | ------
linux | ✓ | ✓ | ✗
macos | ✓ | ✓ | ✓
windows | ✗ | ✗ | ✗

**Comment by kif** [comment]
Any idea why OpenCL is failing on linux ? it should work, no ?

**Comment by kif** [comment]
I just checked with pyFAI, and the OpenCL part is also skipped on GH-actions
LGTM.

**Comment by t20100** [comment]
Thanks for the merge! Let's see how it goes...

For OpenCL on linux, only `ocl-icd-opencl-dev` is installed so there is probably no OpenCL device installed (I took it from our [`.travis.yml`](https://github.com/silx-kit/silx/blob/master/.travis.yml#L45))

**Comment by t20100** [comment]
Looking at it, https://github.com/silx-kit/silx/blob/master/ci/intel_opencl_icd.sh is no longer called.

**Pull request merged**
