### PR TITLE
silx.gui.plot.PlotWidget: Fixed rendering; Doc: Updated sample code.

### PR DESCRIPTION
**Pull request by t20100**
This PR does 2 things:
- Enables usage of image mask in tools (histogram, colormap autscale and profiles) in `examples/stackView.py`.
- Fixes a bug in text rendering in the matplotlib backend when the widget as a width of 0.

To reproduce the bug, use the `examples/stackView.py` from this PR, create a horizontal profile and then open the mask tools.
This leads to:
```
Traceback (most recent call last):
  File "silx/gui/plot/backends/BackendBase.py", line 343, in postRedisplay
    plot.replot()
  File "silx/gui/plot/PlotWidget.py", line 3137, in replot
    self._backend.replot()
  File "silx/gui/plot/backends/BackendMatplotlib.py", line 1517, in replot
    self.draw()
  File "silx/gui/plot/backends/BackendMatplotlib.py", line 1501, in draw
    self._drawOverlays()
  File "silx/gui/plot/backends/BackendMatplotlib.py", line 1014, in _drawOverlays
    axes.draw_artist(item._backendRenderer)
  File "matplotlib/axes/_base.py", line 2762, in draw_artist
    a.draw(self.figure._cachedRenderer)
  File "silx/gui/plot/backends/BackendMatplotlib.py", line 339, in draw
    self.text.draw(*args, **kwargs)
  File "silx/gui/plot/backends/BackendMatplotlib.py", line 268, in draw
    return Text.draw(self, renderer)
  File "matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "matplotlib/text.py", line 681, in draw
    bbox, info, descent = textobj._get_layout(renderer)
  File "matplotlib/text.py", line 274, in _get_layout
    key = self.get_prop_tup(renderer=renderer)
  File "matplotlib/text.py", line 842, in get_prop_tup
    x, y = self.get_unitless_position()
  File "matplotlib/text.py", line 824, in get_unitless_position
    x = float(self.convert_xunits(self._x))
  File "silx/gui/plot/backends/BackendMatplotlib.py", line 307, in convert_xunits
    return self.__get_xy()[0]
  File silx/gui/plot/backends/BackendMatplotlib.py", line 300, in __get_xy
    invtrans = trans.inverted()
  File "matplotlib/transforms.py", line 2377, in inverted
    self._b.inverted(), self._a.inverted())
  File "matplotlib/transforms.py", line 2377, in inverted
    self._b.inverted(), self._a.inverted())
  File "matplotlib/transforms.py", line 1822, in inverted
    self._inverted = Affine2D(inv(mtx), shorthand_name=shorthand_name)
  File "<__array_function__ internals>", line 6, in inv
  File "numpy/linalg/linalg.py", line 546, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix

```

### CODE REVIEW

**Comment by vallsv** [comment]
Any idea if there is a typo in the `xunit` here?
```
        x = super(_TextWithOffset, self).convert_xunits(self._x)
        y = super(_TextWithOffset, self).convert_xunits(self._y)
```

**Comment by t20100** [comment]
Not sure, but it really looks like it indeed, nice catch!

**Comment by t20100** [comment]
It's a typo, but it has no effect if the argument is a `Number` which is the case here.

There seems to also be another typo: `_TextWithOffset.convert_xunits` and `_TextWithOffset.convert_yunits` ignores their argument and use `self._x` (`self._y`) instead... which has the same value here.

**Comment by vallsv** [comment]
I see be careful, i have designed this stuff. I think it's a trick to make it work as i expect.

**Comment by t20100** [comment]
Yes, I won't touch this now, it indeed sounds tricky.

**Pull request merged**
