### PR TITLE
[silx view] When NXdata title is defined, do not append dataset name

### LINKED ISSUE #2998: [NXdata] User supplied title not fully respected
It seems the signal dataset name is appended to the user supplied title. If the user wanted that, (s)he would just add that to the title. 

image

### PR DESCRIPTION
**Pull request by t20100**
This PR avoid appending the dataset name to the plot title when the `title` attribute is defined.

closes #2998

### CODE REVIEW

**Comment by vasole** [comment]
I am hesitating about the behavior to have for the auxiliary signals. My caveat is the data producer has no way to provide the appropriate title for them.

**Comment by vasole** [comment]
Please forget my previous comment. The auxiliary signals should also be displayed.

**Comment by vasole** [comment]
- For 1D data, we can display all the curves simultaneously, therefore only the user specified title is to be provided.
- For 2D data, we are unable to display all the images simultaneously and we use a slider. In that case the previous behavior is appropriate (2D + Aux. signals)

**Comment by t20100** [comment]
Updated to append the dataset signal name when there is more than one.

**Pull request merged**
