### PR TITLE
Various FitManager and FitWidget improvements

### PR DESCRIPTION
**Pull request by PiRK**
Addresses #257 

Currently the main features added by this PR are:

- support of auto weight (use `sqrt(y)` as weight in the least-square problem)
- smoothing prior to strip background computation

This is still work in progress, but at some point we should merge what is finished for inclusion in the 0.3.0 and leave the rest of the remaining unrelated bullet points for next release.

### CODE REVIEW

**Comment by PiRK** [comment]
I'm done with the fit tutorial. The rest of the improvements will go to a separate pull request, and will not be included in *silx 0.3.0*.

**Comment by vasole** [comment]
@kif 

I had to uninstall PyOpenCL on my machine (Windows, Python 3.5, Qt5) in order to pass the test suite.

**Comment by vasole** [comment]
@kif 

A bad OpenCL installation at my side not excluded.

**Comment by kif** [comment]
what is the relationship with opencl ?

**Comment by vasole** [comment]
None. It was for a heads up but you are already working on OpenCL tests.

**Pull request merged**
