### PR TITLE
[plot] Add action show/hide axis

### PR DESCRIPTION
**Pull request by payno**
simple action to show and hide axis.
This only manage the case of the public API ('manage' the call to setAxesDisplayed)

### CODE REVIEW

**Comment by t20100** [comment]
Few comments:

- I would definitely add the action to the available actions but I think it should not be added to existing widgets' toolbar.
  Extra actions can be added by the user in a subclass (and issue #1162 should simplify adding actions to toolbars by splitting it down).
- In `PlotWidget`, you still need to call `self._setDirtyPlot()` as this is handling the repaint of the plot, no?
- `_sigAxesVisibilityChanged` can be public (maybe name it `sigAxesDisplayChanged` to match `setAxesDisplayed` method)
- It seems `PlotWidget.isAxesDisplayed` is missing, it would be best to add it rather than adding it to each backend.
- For the icon, what about using the full screen icon? Otherwise, I send you how to "optimize" the SVG file.

**Comment by payno** [comment]
> I would definitely add the action to the available actions but I think it should not be added to existing widgets' toolbar.
Extra actions can be added by the user in a subclass (and issue #1162 should simplify adding actions to toolbars by splitting it down).

Seems fair

> In PlotWidget, you still need to call self._setDirtyPlot() as this is handling the repaint of the plot, no?
I am not sure I see

yes bad line removal. Fixed

> _sigAxesVisibilityChanged can be public (maybe name it sigAxesDisplayChanged to match setAxesDisplayed method)

Complicated topic. Because for now only the case to call of the public API is handled. But in some cases only one axes can be modified (in the future ?). Maybe we can add an information about the axis concerned. But it will probably evolved and as we don't have a lot of time to think about it (if this is in the next release), have it private seems  'the safest'.

> It seems PlotWidget.isAxesDisplayed is missing, it would be best to add it rather than adding it to each backend.

Yes. But I thing a way or another it will be linked to the backend. For example in OpenGL it is link to  _plotFrame.displayed

> For the icon, what about using the full screen icon? Otherwise, I send you how to "optimize" the SVG file.

Maybe. This is true that it will in a way 'force' image to take all the place available. But it is also removing axis. I think this depend on users. But good for me.

**Comment by t20100** [comment]
You're right, let's keep `_sigAxesVisibilityChanged` private.

For `PlotWidget.isAxesDisplayed`, we can keep a duplicate of the backend state in `PlotWidget`. This is done for example for axis states, it minimizes the code duplicated in each backend.

For the icon it's up to you, it's a matter of taste ;)

**Comment by payno** [comment]
For PlotWidget.isAxesDisplayed I would also go to keep it private for now. For the same reason as _sigAxesVisibilityChanged

**Pull request merged**
