### PR TITLE
[waiting for review] Opencl unittests

### PR DESCRIPTION
**Pull request by kif**
For review: forget about Thomas's commits (they are under review...). Focus on Henri and mine.
Improved the overall usability on OSX with CPU fall-back when invalid workgroup size.

### CODE REVIEW

**Comment by kif** [comment]
@cicciodevoto could you validate this pull-request ? does it run on your mac ?

**Comment by cicciodevoto** [comment]
@kif sure. I don't have with me my mac, I will do it asap.

**Comment by kif** [comment]
@vallsv Why did you change the title: the work is done

**Comment by payno** [comment]
Good for me

**Pull request merged**
