### PR TITLE
Fix float128 on matplotlib < 2.1

### LINKED ISSUE #1288: [plotwidget] Fail to display float128 setImage
I tried to display a float128 image into a `PlotWidget` using `setImage`.

- The plot fail at the repaint
- The repaint is not synchronous with the `setImage` then we can't catch the exception
- After that, the plot is locked: can't use anymore `setImage` with a working data (that's the blocking point for me)

Any idea?

```
Traceback (most recent call last):
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/backends/BackendBase.py", line 317, in postRedisplay
    plot.replot()
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/PlotWidget.py", line 2612, in replot
    item._update(self._backend)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/items/core.py", line 291, in _update
    self._backendRenderer = self._addBackendRenderer(backend)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/items/image.py", line 281, in _addBackendRenderer
    alpha=self.getAlpha())
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 309, in addImage
    image.set_data(data)
  File "/usr/lib/python2.7/dist-packages/matplotlib/image.py", line 434, in set_data
    raise TypeError("Image data can not convert to float")
TypeError: Image data can not convert to float
```

Trying with silx view, the result is the same
```
valls@linkdick /workspace/valls $ python -m silx view
ERROR:silx.gui.qt._qt:<type 'exceptions.TypeError'> No matching signature found   File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/ColorBar.py", line 213, in _activeImageChanged
    data=image)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/ColorBar.py", line 159, in setColormap
    data=data)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/ColorBar.py", line 389, in setColormap
    self.colorScale.setColormap(colormap, data)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/ColorBar.py", line 518, in setColormap
    self.vmin, self.vmax = self._colormap.getColormapRange(data=data)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/Colormap.py", line 251, in getColormapRange
    min_, max_ = min_max(data, min_positive=False, finite=True)
  File "silx/math/combo.pyx", line 320, in silx.math.combo.min_max (silx/math/combo.c:17719)
  File "silx/math/combo.pyx", line 210, in silx.math.combo.__pyx_fused_cpdef (silx/math/combo.c:15832)

ERROR:silx.gui.qt._qt:<type 'exceptions.TypeError'> Image data can not convert to float   File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/backends/BackendBase.py", line 317, in postRedisplay
    plot.replot()
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/PlotWidget.py", line 2612, in replot
    item._update(self._backend)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/items/core.py", line 291, in _update
    self._backendRenderer = self._addBackendRenderer(backend)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/items/image.py", line 281, in _addBackendRenderer
    alpha=self.getAlpha())
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 309, in addImage
    image.set_data(data)
  File "/usr/lib/python2.7/dist-packages/matplotlib/image.py", line 434, in set_data
    raise TypeError("Image data can not convert to float")
```

### PR DESCRIPTION
**Pull request by vallsv**
- Fix `matplotlib` to convert data to `float64` if needed
- Fix `min_max` combo to use `long double`
    - Add `long double` to `_number` fuse type
    - Typo on `min_pos` (it was not defineded, and `minpos` was not used)
    - Redefinition of `_float` fuse type (`cython.floating` do not contains `long double`)

Closes #1288

### CODE REVIEW

**Comment by t20100** [comment]
I think it is worth adding `float128` to tested types for `min_max`, and maybe a test with it for `addImage`.
Otherwise LGTM.

**Comment by vallsv** [comment]
Test fixed

**Comment by vallsv** [comment]
```
======================================================================

FAIL: test_infdata (silx.math.test.test_combo.TestMinMax)

Test min_max with inf. [] (dtype=float128, data=(nan, -inf, inf))

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/silx/math/test/test_combo.py", line 187, in test_infdata

    self._test_min_max(data, min_positive=True)

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/silx/math/test/test_combo.py", line 108, in _test_min_max

    self.assertSimilar(minimum, result.minimum)

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/silx/math/test/test_combo.py", line 119, in assertSimilar

    a == b)

AssertionError: False is not true

======================================================================

FAIL: test_nandata (silx.math.test.test_combo.TestMinMax)

Test min_max with NaN in data [] (dtype=float128, data=(nan, 1.0))

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/silx/math/test/test_combo.py", line 170, in test_nandata

    self._test_min_max(data, min_positive=True)

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/silx/math/test/test_combo.py", line 108, in _test_min_max

    self.assertSimilar(minimum, result.minimum)

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/silx/math/test/test_combo.py", line 119, in assertSimilar

    a == b)

AssertionError: False is not true

```

If somebody have an idea? Yet i dont check it.

**Comment by t20100** [comment]
I fixed the `min_max` issue in a PR on this branch: https://github.com/vallsv/silx/pull/12
It was due to using `cython.floating` to test for floating point types rather than `_floating` which include `float128`.

**Comment by vallsv** [comment]
LGTM

**Pull request merged**
