### PR TITLE
Colormap implementation in silx

### PR DESCRIPTION
**Pull request by t20100**
This PR provides a cython/OpenMP implementation of colormap computation (Related to #1648 ).
This implementation provides linear, log, sqrt and arcsinh (Related to #1212 ).

This PR contains only the implementation of the colormap and not its usage in silx.gui.plot which will be done in another PR.

### CODE REVIEW

**Comment by vallsv** [comment]
NAN looks to be unsupported in Windows.

The Cython code of qhull uses:
```
cdef extern from "numpy/npy_math.h":
    double nan "NPY_NAN"
```
It is maybe something usable.

**Comment by t20100** [comment]
Yes it is still WIP, I haven't ported it to Windows (all the isnan, isfinite, NAN,... are not available), and I also have issues with "old" versions of Cython (i.e., those available on Debian 8)

**Comment by t20100** [comment]
Fixed support of Windows and Cython 0.21.1. Ready for review if CI is happy.

From what I tested it is faster than current state in silx.
Compared to C implementation in pymca it is slightly faster for float but slower for (u)int8|16.

It is using OpenMP all the time (even for small datasets), and I am wondering if it would be good to add a `num_thread` argument to the `cmap` function as OpenMP might not always be desired.

**Comment by vallsv** [comment]
With the numpy from Python2.7 Debian8

```
WARNING:run_tests:Test silx 0.8.0-dev0 from /workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx
Traceback (most recent call last):
  File "./run_tests.py", line 473, in <module>
    unittest.defaultTestLoader.loadTestsFromNames(options.test_name))
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/math/test/__init__.py", line 40, in <module>
    from .test_colormap import suite as test_colormap_suite
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/math/test/test_colormap.py", line 41, in <module>
    from silx.math import colormap
  File "silx/math/colormap.pyx", line 113, in init silx.math.colormap (silx/math/colormap.c:36272)
    numpy.linspace(0.5, 1., LOG_LUT_SIZE + 1,
TypeError: linspace() got an unexpected keyword argument 'dtype'
```

**Comment by t20100** [comment]
Fixed, thanks for the check

**Pull request merged**
