### PR TITLE
Support intensity histogram for scatter

### LINKED ISSUE #2840: [plot] Add scatter support to histogram
The histogram action do not support scatters but only images.

It could be nice to support scatters too.

For that we could create a generic `selectedItem` which contains the last selected item of any kind (and which can contain nothing). And a specific histogram action targetting this attribute to avoid to break the previous one, in case.

### PR DESCRIPTION
**Pull request by vallsv**
Closes #2840 
Relative to #2830 

This PR update the intnesity histogram action to support scatters

- Add an `activeItem` and a `sigActiveItemChanged`  to the plot
    - Basically the last active item (not legend) from any kind
- Add a `setActiveItem` using an item (could be useful)
- Rework `PixelIntensitiesHistoAction`
   - Uses `sigActiveItemChanged`
   - Uses item, not legend
   - Uses Data update
   - Supports scatter (basic histogram from `getValueData`)
- Add the histogram action to the `ScatterView`

This also fixes glitsh on `silx view` when opening the histo, closing it, changing the dataset, opening again the histo window

### CODE REVIEW

**Comment by vallsv** [comment]
```
Traceback (most recent call last):
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\test\utils.py", line 94, in tearDown
    super(PlotWidgetTestCase, self).tearDown()
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\utils\testutils.py", line 196, in tearDown
    raise AssertionError("Exception occured in Qt thread:\n" + messages)
AssertionError: Exception occured in Qt thread:
Traceback (most recent call last):
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\actions\histogram.py", line 113, in _itemUpdated
    self.computeIntensityDistribution()
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\actions\histogram.py", line 141, in computeIntensityDistribution
    xmin, xmax = min_max(array, min_positive=False, finite=True)
  File "silx\math\combo.pyx", line 327, in silx.math.combo.min_max
    return _finite_min_max(data, min_positive)
  File "silx\math\combo.pyx", line 225, in silx.math.combo._finite_min_max
    raise ValueError('Zero-size array')
ValueError: Zero-size array
```

**Comment by vallsv** [comment]
- [ ] @t20100 proposed to use `sigCurrentChanged(current, previous)`, instead of `sigActiveItemChanged(previous, current)`. i am fine with it.

**Comment by t20100** [comment]
Related to  #1733 (Change active item management).

**Comment by vallsv** [comment]
Reworked in #3089

**Pull request closed without merging**
