### PR TITLE
Plot item objet API

### PR DESCRIPTION
**Pull request by t20100**
This PR completes the objet orient plot item API by making `add|removeItem` the public version of `_add` and `_remove`, so one can instanciate and item and add it to the plot.

With `sigItemAdded`, `sigItemAboutToBeRemoved` and `getItems` to me, the API is completed.
Compatibility of `add|removeItem` is maintained (with a deprecation).

TODO:  handle item legends: init with a unique default legend.

### CODE REVIEW

**Comment by vallsv** [comment]
Just a note, i was expecting `_add` (using by `addImage`, `addCurve`...) to enforce legend, while `addItem` could be able to handle object without legend. Is that still doable with this rework?

**Comment by vallsv** [comment]
FYI i am evilly using this private API:
```
plot._add
plot._setActiveItem
item._setLegend
```

**Comment by t20100** [comment]
@vallsv, I kept the private API methods (`plot._add`, `plot._remove`, `item._setLegend) with deprecation warnings.
This PR is NOT changing the need for a unique legend by kind of item in a `PlotWidget`, it just changes the API (while keeping compatibility with the previous one).
This should be doable for `addItem`, but it probably tricky, so it's better to check it and do it separately.

For consistency with ROIs API, I added the `Item.getName` and `Item.setName` methods that are respectively equivalent to `Item.getLegend` (also kept) and `Item._setLegend` (deprecated).
`Item.setName` can only be called on items that are not yet in a `PlotWidget`, else they raise an exception.

**Comment by t20100** [comment]
This is ready for review.

**Comment by vallsv** [comment]
`setName` is nice idea, while the legend can be updated with `id(item)` as said by Armando. I can check that in a few days. But i can't update my project to use that until the integration of the next release.

**Comment by t20100** [comment]
`Item._setLegend` remains available.

**Comment by vallsv** [comment]
COuld you please update the conflict?

**Comment by vallsv** [comment]
Looks good to me. I mean i tested flint with, without problems.

**Comment by t20100** [comment]
Conflict fixed.

**Comment by vallsv** [comment]
Let's try it

**Comment by t20100** [comment]
related to #2830

**Pull request merged**
