### PR TITLE
Icon for the normalization of the ColormapDIalog

### PR DESCRIPTION
**Pull request by vallsv**
As we have a lot now.

I wanted to distinguish continuous, partial, and parametric functions.

Capture d’écran du 2020-06-17 08-52-26

### CODE REVIEW

**Comment by vallsv** [comment]
```
Traceback (most recent call last):

  File "setup.py", line 987, in <module>

    setup_package()

  File "setup.py", line 982, in setup_package

    setup_kwargs = get_project_configuration(dry_run)

  File "setup.py", line 935, in get_project_configuration

    version=get_version(),

  File "setup.py", line 95, in get_version

    import version

  File "/home/travis/build/silx-kit/silx/version.py", line 90, in <module>

    strictversion += PRERELEASE_NORMALIZED_NAME[version_info[3]] + str(version_info[-1])

KeyError: 'rc'

The command "python setup.py $BUILD_COMMAND" failed and exited with 1 during .
```
THe issue is about the branch, "rc" flag

**Comment by t20100** [comment]
CI was probably running against master branch, I restarted it and it should be fine

**Comment by t20100** [comment]
Did you optimized the SVG icons? And could you update the icon gallery in the doc?

**Comment by vallsv** [comment]
Yes it was optimized. Ill generate the gallery.

**Comment by vallsv** [comment]
Done.

**Pull request merged**
