### PR TITLE
Disable textures for Nvidia Fermi GPUs

### LINKED ISSUE #3094: [opencl] Convolution tests fail
I disabled my intel drivers (which we have in CI AFAIK) and I only have the nvidia drivers enabled (debian10, python 3.7.3):

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.116                Driver Version: 390.116                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 580     Off  | 00000000:17:00.0 N/A |                  N/A |
| 41%   46C   P12    N/A /  N/A |    137MiB /  1474MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  Quadro P400         Off  | 00000000:73:00.0 Off |                  N/A |
| 34%   34C    P8    N/A /  N/A |     17MiB /  1999MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

Some kernels do not compile (something to do with textures according to @kif ). I'm only showing one of them:

```python
python run_tests.py silx.opencl.test.test_convolution.test_convolution

ERROR: test_1D (silx.opencl.test.test_convolution.TestConvolution)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/test/test_convolution.py", line 198, in test_1D
    self.template_test("test_1D")
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/test/test_convolution.py", line 176, in template_test
    conv = self.instantiate_convol(data.shape, kernel)
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/test/test_convolution.py", line 126, in instantiate_convol
    extra_options={"dont_use_textures": not(self.param["use_textures"])}
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/convolution.py", line 83, in __init__
    self._init_kernels()
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/convolution.py", line 245, in _init_kernels
    compile_options=compile_options
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/processing.py", line 265, in compile_kernels
    self.program = pyopencl.Program(self.ctx, kernel_src).build(options=compile_options)
  File "/mntdirect/_data_id21_inhouse/wout/dev/virtualenvs/lid21data/silx/py37/lib/python3.7/site-packages/pyopencl/__init__.py", line 522, in build
    options_bytes=options_bytes, source=self._source)
  File "/mntdirect/_data_id21_inhouse/wout/dev/virtualenvs/lid21data/silx/py37/lib/python3.7/site-packages/pyopencl/__init__.py", line 566, in _build_and_catch_errors
    raise err
pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'GeForce GTX 580' on 'NVIDIA CUDA' at 0x15a7b30>:

<kernel>:173:31: error: no matching function for call to 'read_imagef'
        sum += READ_IMAGE_X * READ_FILTER_VAL(jx);
                              ^~~~~~~~~~~~~~~~~~~
<kernel>:99:32: note: expanded from macro 'READ_FILTER_VAL'
    #define READ_FILTER_VAL(j) READ_FILTER_1D(j)
                               ^~~~~~~~~~~~~~~~~
<kernel>:48:27: note: expanded from macro 'READ_FILTER_1D'
#define READ_FILTER_1D(j) read_imagef(filter, (int2) (FILTER_INDEX(j), 0)).x;
                          ^~~~~~~~~~~
cl_kernel.h:18365:25: note: candidate function not viable: requires 3 arguments, but 2 were provided
float4 __OVERLOADABLE__ read_imagef(image3d_t image, sampler_t sampler, float4 coord);
                        ^
cl_kernel.h:18364:25: note: candidate function not viable: requires 3 arguments, but 2 were provided
float4 __OVERLOADABLE__ read_imagef(image3d_t image, sampler_t sampler, int4 coord);
                        ^
cl_kernel.h:18363:25: note: candidate function not viable: requires 3 arguments, but 2 were provided
float4 __OVERLOADABLE__ read_imagef(image2d_t image, sampler_t sampler, float2 coord);
                        ^
cl_kernel.h:18362:25: note: candidate function not viable: requires 3 arguments, but 2 were provided
float4 __OVERLOADABLE__ read_imagef(image2d_t image, sampler_t sampler, int2 coord);
                        ^

(options: -DUSED_CONV_MODE=0 -DIMAGE_DIMS=1 -DFILTER_DIMS=1 -I /mntdirect/_data_id21_inhouse/wout/dev/virtualenvs/lid21data/silx/py37/lib/python3.7/site-packages/pyopencl/cl)
(source saved as /tmp/tmpik4ni302.cl)

======================================================================
SKIPPED: test_1D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_batched_2D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_nonseparable_2D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_nonseparable_3D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_separable_2D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_separable_3D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_1D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_batched_2D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_nonseparable_2D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_nonseparable_3D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_separable_2D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_separable_3D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_1D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_batched_2D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_nonseparable_2D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_nonseparable_3D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_separable_2D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_separable_3D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_1D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_batched_2D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_nonseparable_2D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_nonseparable_3D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_separable_2D (silx.opencl.test.test_convolution.TestConvolution)
SKIPPED: test_separable_3D (silx.opencl.test.test_convolution.TestConvolution)
----------------------------------------------------------------------
mode=constant not implemented without textures
----------------------------------------------------------------------
Ran 192 tests in 8.292s

FAILED (errors=96, skipped=24)
```

### PR DESCRIPTION
**Pull request by pierrepaleo**
Close #3094

### CODE REVIEW

**Comment by woutdenolf** [comment]
Running on the system with the original problem gives this after the patch:

```python
python run_tests.py silx.opencl.test.suite

======================================================================
ERROR: test_separable_3D (silx.opencl.test.test_convolution.TestConvolution)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/test/test_convolution.py", line 204, in test_separable_3D
    self.template_test("test_separable_3D")
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/test/test_convolution.py", line 176, in template_test
    conv = self.instantiate_convol(data.shape, kernel)
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/test/test_convolution.py", line 126, in instantiate_convol
    extra_options={"dont_use_textures": not(self.param["use_textures"])}
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/convolution.py", line 82, in __init__
    self._allocate_memory(mode)
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/convolution.py", line 222, in _allocate_memory
    "mode='constant' is not implemented without textures yet"
NotImplementedError: mode='constant' is not implemented without textures yet

Ran 253 tests in 28.146s

FAILED (errors=27, skipped=24)
```

And when selecting `test_convolution` specifically: 

```python
python run_tests.py silx.opencl.test.test_convolution

Traceback (most recent call last):
  File "run_tests.py", line 478, in <module>
    unittest.defaultTestLoader.loadTestsFromNames(options.test_name))
  File "/usr/lib/python3.7/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.7/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.7/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3.7/unittest/loader.py", line 124, in loadTestsFromModule
    tests.append(self.loadTestsFromTestCase(obj))
  File "/usr/lib/python3.7/unittest/loader.py", line 93, in loadTestsFromTestCase
    loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
  File "/usr/lib/python3.7/unittest/suite.py", line 24, in __init__
    self.addTests(tests)
  File "/usr/lib/python3.7/unittest/suite.py", line 57, in addTests
    for test in tests:
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/test/test_convolution.py", line 103, in __init__
    self.mode = param["boundary_handling"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by pierrepaleo** [comment]
The tests instantiate `Convolution` with "all" possible combinations, so I have to detect whether a Fermi device is used. It should be OK now.

**Comment by woutdenolf** [comment]
All opencl tests are now disabled when a Fermi GPU is selected

```python
python run_tests.py silx.opencl.test

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

However this work fine

```python
python run_tests.py silx.opencl.test.test_linalg
...
----------------------------------------------------------------------
Ran 3 tests in 0.238s

OK
```

and this doesn't

```python
python run_tests.py silx.opencl.test.test_convolution

Traceback (most recent call last):
  File "run_tests.py", line 478, in <module>
    unittest.defaultTestLoader.loadTestsFromNames(options.test_name))
  File "/usr/lib/python3.7/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.7/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.7/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3.7/unittest/loader.py", line 124, in loadTestsFromModule
    tests.append(self.loadTestsFromTestCase(obj))
  File "/usr/lib/python3.7/unittest/loader.py", line 93, in loadTestsFromTestCase
    loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
  File "/usr/lib/python3.7/unittest/suite.py", line 24, in __init__
    self.addTests(tests)
  File "/usr/lib/python3.7/unittest/suite.py", line 57, in addTests
    for test in tests:
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/test/test_convolution.py", line 103, in __init__
    self.mode = param["boundary_handling"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by woutdenolf** [comment]
Sorry, just noticed that there are 3 tests failing on Fermi other than the convolution tests:

```python
ERROR: test_fbp (silx.opencl.test.test_backprojection.TestFBP)
ERROR: test_fbp_filters (silx.opencl.test.test_backprojection.TestFBP)
ERROR: test_fbp_oddsize (silx.opencl.test.test_backprojection.TestFBP)
```

All with the same error:

```python
======================================================================
ERROR: test_fbp (silx.opencl.test.test_backprojection.TestFBP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/test/test_backprojection.py", line 91, in setUp
    self.fbp = backprojection.Backprojection(self.sino.shape, profile=True)
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/backprojection.py", line 113, in __init__
    self._init_filter(filter_name)
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/backprojection.py", line 265, in _init_filter
    extra_options=self.extra_options,
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/sinofilter.py", line 85, in __init__
    self._allocate_memory()
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/sinofilter.py", line 142, in _allocate_memory
    self.d_filter_f = parray.zeros(self.queue, (self.sino_f_shape[-1],), np.complex64)
  File "/mntdirect/_data_id21_inhouse/wout/dev/virtualenvs/lid21data/silx/py37/lib/python3.7/site-packages/pyopencl/array.py", line 2015, in zeros
    result._zero_fill()
  File "/mntdirect/_data_id21_inhouse/wout/dev/virtualenvs/lid21data/silx/py37/lib/python3.7/site-packages/pyopencl/array.py", line 1232, in _zero_fill
    self.offset, self.nbytes, wait_for=wait_for))
  File "/mntdirect/_data_id21_inhouse/wout/dev/virtualenvs/lid21data/silx/py37/lib/python3.7/site-packages/pyopencl/__init__.py", line 1894, in enqueue_fill_buffer
    return _cl._enqueue_fill_buffer(queue, mem, pattern, offset, size, wait_for)
pyopencl._cl.LogicError: clEnqueueFillBuffer failed: INVALID_OPERATION
```

**Comment by kif** [comment]
I confirm that it fails on Fermi, not on Maxwell.

Small remark, this feature is absent from CUDA and has to be emulated when using the Volta on Power9. I suspect this bug will pop-up again on the power9 as soon as we will want to use it there.

For info, how OpenCL work on the power9:
Pocl compiles the kernel with llvm to produce an IR.
The IR is translated into the nvidia's IR called PTX using NVVM. This `enqueue_fill_buffer` is missing from NVVM.
More info on:
https://github.com/pocl/pocl/issues/725

**Comment by kif** [comment]
LGTM

**Comment by kif** [comment]
I found out that the Fermi is recognized as opencl 1.2 while it is only 1.1. A bug in pyopencl, I submitted a patch.

**Pull request merged**
