### PR TITLE
Added a test to check read() return value.

### PR DESCRIPTION
**Pull request by alexmarie78**
Trying to resolve warning from silx/io/specfile/src/sfinit.c #2302 issue.

### CODE REVIEW

**Comment by vasole** [comment]
The function should return an error (instead of being void) with that error taken into account by the calling functions.

**Comment by vasole** [comment]
... or not? Still to decide what to do in case of error. We do not want that a problem with one scan preventing us from accessing all the previous scans.

**Comment by vallsv** [comment]
Is there a way to create a file which will use this return branch? It could help.

**Comment by alexmarie78** [comment]
Hello,
I was working on my fork repository, thus I don't know why my last commit :
"Removed "try/except" blocks for h5py and fabio." is here instead of in my fork repo.
And this thing prevents me from open a new PR with the last commit.

**Comment by t20100** [comment]
Looks you're working on the master branch of your local repository.
if you start working on multiple pull requests (PR) at once, you should do the development in a different branch for each PR.
You can look at scikit-image documentation for a brief description of the process: http://scikit-image.org/docs/dev/contribute.html

**Comment by alexmarie78** [comment]
Hello,
Thanks for all your answers, i'm working on it.

**Pull request closed without merging**
