### PR TITLE
[FBP] PEP8

### PR DESCRIPTION
**Pull request by payno**

### CODE REVIEW

**Comment by t20100** [comment]
Could you add the example to the example gallery in the doc (https://github.com/silx-kit/silx/blob/master/doc/source/sample_code/index.rst) ?

**Comment by t20100** [comment]
And maybe use a longer name for the example filename.

**Comment by payno** [comment]
waiting for the forward projector to be merged and we will add utils to generate a Shepp-Logan phantom

**Comment by payno** [comment]
Now the backprojection example is free from external resources. 
It deal with it using the forward projection.
Question : 
should we also include an example for the projection ?
I think the current example is enough.

**Pull request merged**
