### PR TITLE
Stats roi

### PR DESCRIPTION
**Pull request by payno**
#2684 should be merged before
The goal of this PR is to provide a convenient way to compute statistics on specific Region of interest.

Steps:
- [x] adapt the stats handler to manage roi
- [x] add a mask system to filter values in a specific roi
   - [x] test on CurveContext
   - [x] test on Imagecontext
   - [x] test on 2D ScatterContext
   - [x] test on Histogram context
   - [ ] ~test on 3D ScatterContext~ -> not managed, would need a 3d roi or an axis at leasr
   - [ ] ~test on 3D _plot3DArrayContext~ -> same as ScatterContext
- [x] add a widget to display the result for a roi and a set of stats.
   - how to present this to the user ? Make roi selection possible for a plot and display all the stats or present only one stat and all the roi, or create a filter with a set of roi and a set of stats ? Is the roi editable box available ? -> this is PR #2754
- [x] add isIn function in _RegionOfInterestBase
   - add unit test
- [x] add an example of usage
- [x] doc
- [x] speed up statistic calculation (especially calls to isIn and neighbouring functions)
   - [x] better filtering when event is 'DataChanged'
   - [x] keep contexts for (item, plot, roi, on_limits) to keep mask and avoid there avoid it recalculation when possible.

This feature requires:

- [x] minimalistic common API between ROI class and RegionOfInterestClass (see PR: #2684)
- [x] a new signal 'RegionEditionFinished' for RegionOfInterestClass ? Overwise will always update the stats. Might also be managed as plot and the '_dirty' flag ? See issue #2685 , but might be complicated.

#2724 and #2754 need to be merged before

:warning: The goal of this PR is to provide the feature of roi and stats as a first steps.
Here we are looking for high performances. If this feature is commonly use then we should look to speed up performances. Some ideas:
* we can add some filter in the isIn function to first look if a bounding box contains the pixel... before calling more complex operations.
* `isIn` functions could be done in Cython

:warning:
`isIn` functions for image context: for now have basically a binary approach, the pixel is in a roi or not. To have a fully 'correct behaviour' we should add a weight on stats calculation to moderate the pixel value.

:warning:
behaviour of scale images: now the statistics are computed on the entire data array (there is no sampling in the array or interpolation regarding the scale). This also mean that the result can differ from what is displayed. But I guess there is no perfect behaviour.

### CODE REVIEW

**Comment by payno** [comment]
For now:
- the `RegionOfInterestManager` knows the plot associate to the RegionOfInterest for 2D+
- ROITable nows the plot and associate it the ROI, ROI has no information about the associated plot.

Make sense for this to be not associated. So the RoiStatsWindow will manage a list of roi, the update of this list has to be managed by the developers.

**Comment by payno** [comment]
screenshot from the examples/plotRoiStats

roiStats

**Comment by payno** [comment]
Regarding the source code we can ask ourself if _StatsROITable should inherit from _StatsWidgetBase or from StatsTable instead. We could eaven consider having all the ROI mecanism in StatsTable. But making something fully generic would bring more complexity in this class which is avoidable by creating an upper class.

**Comment by payno** [comment]
Screenshot from 2019-09-25 16-50-12

**Comment by payno** [comment]
Some benchmark on my PC (Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz)
With BB:

[ 65.00%] ··· benchmarks.StatsImageContextArcRoiSuite.time_image_mean                                                                                                                                            
[ 65.00%] ··· ======== =============
               param1               
              -------- -------------
                256       175±2μs   
                512       625±8μs   
                1024    3.14±0.03ms 
                2048     15.3±0.2ms 
              ======== =============

[ 70.00%] ··· benchmarks.StatsImageContextArcRoiSuite.time_image_sum                                                                                                                                             
[ 70.00%] ··· ======== =============
               param1               
              -------- -------------
                256       111±1μs   
                512       400±3μs   
                1024    2.30±0.01ms 
                2048    11.7±0.07ms 
              ======== =============

[ 75.00%] ··· benchmarks.StatsImageContextLineRoiSuite.time_image_mean                                                                                                                                   
[ 75.00%] ··· ======== =============
               param1               
              -------- -------------
                256       172±2μs   
                512       629±10μs  
                1024    3.15±0.02ms 
                2048       failed   
              ======== =============

[ 80.00%] ··· benchmarks.StatsImageContextLineRoiSuite.time_image_sum                                                                                                                                    
[ 80.00%] ··· ======== =============
               param1               
              -------- -------------
                256      111±0.7μs  
                512       407±10μs  
                1024    2.29±0.01ms 
                2048       failed   
              ======== =============

[ 85.00%] ··· benchmarks.StatsImageContextRectangleRoiSuite.time_image_mean                                                                                                                             
[ 85.00%] ··· ======== ============= ============= =========== =============
              --                               param2                       
              -------- -----------------------------------------------------
               param1        32            64          128          256     
              ======== ============= ============= =========== =============
                256       174±3μs       172±2μs     165±0.6μs     111±2μs   
                512       626±9μs       630±6μs      619±7μs      604±10μs  
                1024    3.10±0.01ms   3.10±0.01ms    3.13±0ms   3.05±0.03ms 
                2048       failed        failed       failed       failed   
              ======== ============= ============= =========== =============

[ 90.00%] ··· benchmarks.StatsImageContextRectangleRoiSuite.time_image_sum                                                                                                                              
[ 90.00%] ··· ======== ============= ============= ============= ============
              --                               param2                        
              -------- ------------------------------------------------------
               param1        32            64           128          256     
              ======== ============= ============= ============= ============
                256      109±0.7μs     109±0.6μs     103±0.8μs    48.4±0.4μs 
                512       414±5μs       419±7μs       401±5μs      379±10μs  
                1024    2.32±0.01ms   2.29±0.01ms   2.27±0.01ms    2.19±0ms  
                2048       failed        failed        failed       failed   
              ======== ============= ============= ============= ============

witout BB

[ 65.00%] ··· benchmarks.StatsImageContextArcRoiSuite.time_image_mean                                                                                                                                            
[ 65.00%] ··· ======== =============
               param1               
              -------- -------------
                256       179±2μs   
                512       651±60μs  
                1024    3.22±0.02ms 
                2048     16.1±0.4ms 
              ======== =============

[ 70.00%] ··· benchmarks.StatsImageContextArcRoiSuite.time_image_sum                                                                                                                                             
[ 70.00%] ··· ======== =============
               param1               
              -------- -------------
                256      113±0.5μs  
                512       405±6μs   
                1024    2.38±0.06ms 
                2048    12.1±0.05ms 
              ======== =============

[ 75.00%] ··· benchmarks.StatsImageContextLineRoiSuite.time_image_mean                                                                                                                                   
[ 75.00%] ··· ======== ==========
               param1            
              -------- ----------
                256     174±2μs  
                512     633±20μs 
                1024    3.14±0ms 
                2048     failed  
              ======== ==========

[ 80.00%] ··· benchmarks.StatsImageContextLineRoiSuite.time_image_sum                                                                                                                                    
[ 80.00%] ··· ======== ============
               param1              
              -------- ------------
                256      112±1μs   
                512      447±50μs  
                1024    2.66±0.1ms 
                2048      failed   
              ======== ============

[ 85.00%] ··· benchmarks.StatsImageContextRectangleRoiSuite.time_image_mean                                                                                                                             
[ 85.00%] ··· ======== ============= ============= ============= =============
              --                                param2                        
              -------- -------------------------------------------------------
               param1        32            64           128           256     
              ======== ============= ============= ============= =============
                256       177±4μs       176±4μs       170±5μs       117±4μs   
                512       647±10μs      654±20μs      657±30μs      598±20μs  
                1024    3.27±0.02ms   3.15±0.01ms   3.31±0.07ms   3.21±0.01ms 
                2048       failed        failed        failed        failed   
              ======== ============= ============= ============= =============

[ 90.00%] ··· benchmarks.StatsImageContextRectangleRoiSuite.time_image_sum                                                                                                                              
[ 90.00%] ··· ======== =========== ============ ========== =============
              --                             param2                     
              -------- -------------------------------------------------
               param1       32          64         128          256     
              ======== =========== ============ ========== =============
                256      112±4μs     110±5μs     106±9μs     49.6±0.2μs 
                512     545±100μs    425±8μs     464±70μs     390±40μs  
                1024     2.37±0ms   2.59±0.1ms   2.36±0ms   2.31±0.02ms 
                2048      failed      failed      failed       failed   
              ======== =========== ============ ========== =============

**Comment by t20100** [comment]
There's a conflict.
Its probably worth waiting for PR #3048 to be finished and merged before merging this PR.

**Comment by vallsv** [comment]
This `isIn` could be a dedicated PR. But i think it would be good to rename it. Maybe `containsPoint` (i did not checked exactly the code)? and this point is screen/widget coord? or data coord?

**Comment by payno** [comment]
split into #3056 and #3055

**Comment by payno** [comment]
it has been split in #3056 and #3055

**Pull request closed without merging**
