### PR TITLE
[plot3d] Add alternative interaction when ctrl is pressed

### LINKED ISSUE #1131: [plot3d] Add a different mode on Ctrl pressed
As now interaction is only with left button, it would be nice to temporarily switch mode with modifier key, e.g., to have pan while Ctrl pressed when in rotate mode.

### PR DESCRIPTION
**Pull request by t20100**
This PR adds support of a second interaction when Ctrl  (command on macOS) is pressed:
- For scene rotation, Ctrl switches to scene panning
- For scene panning, Ctrl switches to scene rotation
- For plane panning (so far only available in ScalarFieldView), Ctrl switches to scene rotation.

closes #1131

### CODE REVIEW

**Comment by vallsv** [comment]
Why don't you use id keys from Qt?

**Comment by t20100** [comment]
`silx.gui.plot3d.scene` was so far not depending on Qt, but there is no real need for it, so I can use key codes from Qt.

**Comment by t20100** [comment]
Updated key codes + refactor `setInteractiveMode` method in `Plot3DWidget` and `ScalarFieldView`

**Comment by vallsv** [comment]
LGTM

**Pull request merged**
