### PR TITLE
silx.gui.plot.PlotWidget: Added `get|setAxesMargins` methods to control margin ratios around plot area

### LINKED ISSUE #2681: PlotWidget doesn't use available screen space
I'm using the `PlotWidget`, integrated into one of our applications.

However, I find that the available screen space is not efficiently used. There is too much empty space around the data and axes, as displayed below:
silx-widget-space

The blue is the widget background color, as set via `PlotWidget.setBackgroundColor`.

Is there any way to improve this?

### LINKED ISSUE #3193: Colormap dialog: Very small histogram in OpenGL
Hi,

No idea if it is an issue, but i feel like if silx is setup to use OpenGL, the colormap dialog then provide a very small histogram which is not convenient to use. Or which could be improved.

Do you think there is easy way to optimize the space here?

Maybe disabling OpenGL for this specific plot?

Screenshot from 2020-09-21 11-46-11

### PR DESCRIPTION
**Pull request by t20100**
This PR adds `PlotWidget.setAxesMargins(left, top, right, bottom)` and `PlotWidget.getAxesMargins` methods for controlling the margins in which the axes and labels are displayed.
It is implemented for both matplotlib and OpenGL backends.

closes #3193 
closes #2681

### CODE REVIEW

**Comment by vallsv** [comment]
I don't really agree for replacing the visibility of the axis with the margin. It's not the same concept.

It's somehow like saying you can remove `button.setVisible(False)` cause you can use `button.setFixedSize(0, 0)`.

I think i want to be able to set the margin, and i want to be able to hide or display the axis. That's commonly used for Flint plot displaying images. I don't want to store on my side the previous margin size to be able to restore it. That's something you easily can deal with.

This said i have not checked the PR.

**Comment by t20100** [comment]
OK, should be simple to change (only need to be implemented in `PlotWidget`).
Then, I'll rename `get|setPlotMargins` to `get|setAxesMargins` so it ressembles `setAxesDisplayed`... and also probably make `isAxesDisplayed` public.

**Comment by vasole** [comment]
I'm a bit confused.

Are we talking about margins inside the plot (so that maximum does not touch the borders and so on), about margins between the plot rectangle and the axes labels or about something else?

**Comment by t20100** [comment]
That's the margins between the axes and the border of the widget (i.e., where the labels and ticks are).
It also makes OpenGL and matplotlib backends consistent (it was not).

**Comment by vasole** [comment]
I thought those borders could be controlled just by using Qt, so you are clearly talking about other thing.

| widget margins (Qt)|Left axis Labels|Plot Rectangle|right Axis labels|widget margins(Qt)|

So, you are talking about margins between the plot rectangle and the axes labels.

**Comment by t20100** [comment]
Yes, that's the "margins" where the labels are drawn.

**Comment by vallsv** [comment]
Thanks a lot. Yes the getter should be public, i guess i use it.

**Comment by t20100** [comment]
Updated to restore `setAxesDisplayed` and made `isAxesDisplayed` public.

**Comment by vallsv** [comment]
Very nice. Thanks for the patch.

**Pull request merged**
