### PR TITLE
Add a pylab-like module

### PR DESCRIPTION
**Pull request by t20100**
Following #118.

Usage: `from silx.pylab import *`

Functionalities:
- It provides a flattened namespace by doing `from silx.<package> import *`
- It also load the equivalent of `%pylab`
- If not loaded from the notebook, it setups qt and matplotlib before pylab, starts a QApplication (if not yet started) and load the widgets' modules.

This is a proposal to discuss.
Any idea for a better name than pylab? silx.silx, silx.slx, silx.s, silx.ipy....
Another way of using it? E.g., `from silx import slx` instead of  `from silx.pylab import *`

### CODE REVIEW

**Comment by vasole** [comment]
- The safest approach would be to use a module that exposes selected functionalities because it can be easily extended to whatever we might need.
- I would discourage the use of from whatever import *

**Comment by kif** [comment]
On a clean debian8, I got: 
kieffer@mac13:~/workspace/silx/package$ ipython
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from silx import sx
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-3f9c8e31b7c3> in <module>()
----> 1 from silx import sx

/usr/lib/python2.7/dist-packages/silx/sx.py in <module>()
     69 # %pylab
     70 if _get_ipython is not None:
---> 71     _get_ipython().enable_pylab(gui='inline' if _IS_NOTEBOOK else 'qt')
     72 
     73 

/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.pyc in enable_pylab(self, gui, import_all, welcome_message)
   2980         from IPython.core.pylabtools import import_pylab
   2981 
-> 2982         gui, backend = self.enable_matplotlib(gui)
   2983 
   2984         # We want to prevent the loading of pylab to pollute the user's

/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.pyc in enable_matplotlib(self, gui)
   2946         # Now we must activate the gui pylab wants to use, and fix %run to take
   2947         # plot updates into account
-> 2948         self.enable_gui(gui)
   2949         self.magics_manager.registry['ExecutionMagics'].default_runner = \
   2950             pt.mpl_runner(self.safe_execfile)

/usr/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.pyc in enable_gui(gui, app)
    314         from IPython.lib.inputhook import enable_gui as real_enable_gui
    315         try:
--> 316             return real_enable_gui(gui, app)
    317         except ValueError as e:
    318             raise UsageError("%s" % e)

/usr/lib/python2.7/dist-packages/IPython/lib/inputhook.pyc in enable_gui(gui, app)
    539         e = "Invalid GUI request %r, valid ones are:%s" % (gui, guis.keys())
    540         raise ValueError(e)
--> 541     return gui_hook(app)
    542 

/usr/lib/python2.7/dist-packages/IPython/lib/inputhook.pyc in enable_qt4(self, app)
    258             app = QtGui.QApplication(sys.argv)
    259         """
--> 260         from IPython.lib.inputhookqt4 import create_inputhook_qt4
    261         from IPython.external.appnope import nope
    262         app, inputhook_qt4 = create_inputhook_qt4(self, app)

/usr/lib/python2.7/dist-packages/IPython/lib/inputhookqt4.py in <module>()
     22 
     23 from IPython.core.interactiveshell import InteractiveShell
---> 24 from IPython.external.qt_for_kernel import QtCore, QtGui
     25 from IPython.lib.inputhook import allow_CTRL_C, ignore_CTRL_C, stdin_ready
     26 

/usr/lib/python2.7/dist-packages/IPython/external/qt_for_kernel.py in <module>()
     79 api_opts = get_options()
     80 if api_opts is not None:
---> 81     QtCore, QtGui, QtSvg, QT_API = load_qt(api_opts)
     82 
     83 else: # use ETS variable

/usr/lib/python2.7/dist-packages/IPython/external/qt_loaders.pyc in load_qt(api_options)
    239 
    240         #cannot safely recover from an ImportError during this
--> 241         result = loaders[api]()
    242         api = result[-1]  # changed if api = QT_API_PYQT_DEFAULT
    243         commit_api(api)

/usr/lib/python2.7/dist-packages/IPython/external/qt_loaders.pyc in import_pyqt4(version)
    169         sip.setapi('QVariant', version)
    170 
--> 171     from PyQt4 import QtGui, QtCore, QtSvg
    172 
    173     if not check_version(QtCore.PYQT_VERSION_STR, '4.7'):

RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class

**Comment by t20100** [comment]
Fixed, IPython < 3.2.2 (as in Debian 8) does not check if PyQt5 is already loaded (which is now what silx tries first...).
So, with IPython < 3.2.2, import PyQt4 or PySide before importing silx to force it....

**Comment by kif** [comment]
looks like a good idea

**Comment by t20100** [comment]
I think so too ;)... at least as an entry point from (i)python console.
For scripts/applications, I'd rather import what I need and not more.
Any other comments, ideas?

**Comment by vasole** [comment]
For the time being we let it as it is but we keep the door open to a flattened namespace. Everybody agrees that this module (with or without flattened namespace) is to be considered only for interactive use.

**Comment by vallsv** [comment]
@t20100 do you think it is still up-to-date with the new features of silx?

**Comment by t20100** [comment]
I haven't updated the available features since it pushed it 2 months ago.
Anyone willing to add some functions in the sx module?

Currently this module provides:
GUI:
from silx.gui import qt
from silx.gui import plot
from silx.gui.plot import ImageView, plot1D, plot2D
qapp variable (the QApplication)

None GUI:
from silx import *  # For the versions
from silx.io.utils import save1D
from silx.math import Histogramnd, HistogramndLut, leastsq

**Comment by vasole** [comment]
I would have considered PlotWindow, Plot1D and Plot2D and I would have left the function equivalents as plot1d and plot2d to avoid confusion. If plot2D and plot2D can be used without passing data, then it is not so critical. I would nevertheless add PlotWindow.

**Comment by t20100** [comment]
- Added PlotWindow
- plot1D and plot2D can be called without arguments. I'd keep them in the sx module as they allow to plot data in a single liner which is convenient. We can also add Plot1D and Plot2D, though it might be confusing...

**Comment by vasole** [comment]
Following the code camp feedback, we should remove plot1D and plot2D from PlotWindow.py in order to be replaced by plot and imshow in sx module. Then there is no confusion between plot1D and Plot1D pr between plot2D and Plot2D and there is a clear separation between the interactive use (plot and imshow from sx module)  and the programmatic use (Plot1D and Plot2D).

**Comment by t20100** [comment]
I changed plot1d and plot2d function to plot and imshow with functions signature as close as possible to matplotlib. I felt weird doing so: matplotlib-like API over silx plot over matplotlib again...

Anyway, ready for review for me.

Reminder of current sx content:
GUI:
from silx.gui import qt
from silx.gui.plot import *
plot, imshow functions

None GUI:
from silx import * # For the versions
from silx.io.utils import save1D
from silx.math import Histogramnd, HistogramndLut

Please add stuff to sx if you want to expose it there.

**Comment by vallsv** [comment]
The load API is merged. I propose to add
```
from silx.io.utils import load  # noqa
```

**Comment by t20100** [comment]
Rebased and added load to sx.

**Comment by vasole** [comment]
leastsq still exists... I guess it should be exposed ``in math.__init__`` and in this module.

**Comment by t20100** [comment]
I added leastsq to sx.

**Comment by vasole** [comment]
Since this can be a never ending pull request, I propose to merge it now and for any other addition open the corresponding issue/pull request.

**Comment by t20100** [comment]
Yes!

**Pull request merged**
