### PR TITLE
[Plot] Add a masking tools panel

### LINKED ISSUE #98: [Plot] Image mask tools
Functions (list taken from PyMca MaskImageWidget):
- Operation on the whole mask:
    - Clear
    - Inversion
- Drawing tools:
    - Brush (with settable width in image pixels)
    - Rectangle
    - Polygon
    - Above threshold
    - Below threshold
    - Within range
- Each draw tool can either paint or erase
- Multiple level of exclusive masks

Proposal: Regarding the number of tools and the fact that more tools will probably be needed, I'm thinking of making a DockWidget as for ROIs, e.g.:

maskdockwidget

Ideas for future:
- History/undo/redo
- Drawing tools: circle, ring
- Edition of shapes as vector graphics
- shrink/expand mask
- show/hide different level of mask
- Load (replace of add) and Save masks

### PR DESCRIPTION
**Pull request by t20100**
Closes #98 

Implemented functions :
- Multiple level of exclusive masks or a single level (as an option)
- Operation on the whole mask:
    - Clear
    - Inversion
    - Reset all mask levels
- Drawing tools:
    - Brush (with settable width in image pixels), which provides a way to draw circle
    - Rectangle
    - Polygon
    - Each draw tool can either paint or erase
- Thresholding:
    - Above threshold
    - Below threshold
    - Within range
    - Range can be loaded from current colormap range
- 10 levels of undo/redo
- load/save mask

Related issues: #104, #105

### CODE REVIEW

**Comment by vasole** [comment]
It looks very nice. Some feedback:

- The transparency of the mask is too low (at least on my screen).
- Colormap dialog is modal. Is it intended?
- In my opinion, the mask should not disappear. You have masked the image, the image has a mask and it is drawn.
- The polygonal mask tooltip icon should explain the usage (left button to add points, right button to finish)

**Comment by t20100** [comment]
Colormap dialog is modal because it does not sync with image changes (colormap dialog needs rework).
Addressed 3 comments.
Leaving the mask displayed when closing the mask tool can lead to inconsistencies if one change the image or remove it, the mask will stay...

**Comment by vasole** [comment]
The main root of the problem is that the mask is totally dissociated of the image used to define it. If the mask is totally dissociated from the image, as it seems to be your choice, you can design a mask at a much higher resolution than the image below it. So, you may think a pixel is selected when it is not.

To me, an image can potentially have data, representation and masks. Of course any of those on its own lead to a visual representation and the actual visualization does not care because it only needs to draw pixmaps. Keeping the simple concept of "legend", one can pack together items and choose to make them disappear if the "image legend" does so. 

The analogue in 1D is a curve that has its data (positive and negative values) and its representation (without negative values with log scales). If one totally decouples both, bugs like #100 happen.

**Comment by vasole** [comment]
@srio

Manolo's proposal: Provide the possibility to show all masks, a particular mask or none.

**Comment by t20100** [comment]
Mask visibility toggling would be nice, but I'd keep that for later.
It's in the list of mask tools enhancements: See #105.

**Pull request merged**
