### PR TITLE
3451 doubleword

### PR DESCRIPTION
**Pull request by kif**
Minor improvement over existing PR: just rename 3 functions

### CODE REVIEW

**Review by pierrepaleo — APPROVED** [review]

**Comment by pierrepaleo** [comment]
Looks good. CI fails on some platform with
```
2021-05-31T08:26:05.3283670Z   File "setup.py", line 612, in patch_extension
2021-05-31T08:26:05.3284390Z     numpy_version = [int(i) for i in numpy.version.short_version.split(".", 2)[:2]]
2021-05-31T08:26:05.3285640Z AttributeError: module 'numpy.version' has no attribute 'short_version'
```

**Comment by kif** [comment]
On Mon, 31 May 2021 01:29:46 -0700
Pierre Paleo ***@***.***> wrote:

> Looks good. CI fails on some platform with
> ```
> 2021-05-31T08:26:05.3283670Z   File "setup.py", line 612, in patch_extension
> 2021-05-31T08:26:05.3284390Z     numpy_version = [int(i) for i in numpy.version.short_version.split(".", 2)[:2]]
> 2021-05-31T08:26:05.3285640Z AttributeError: module 'numpy.version' has no attribute 'short_version'
> ```

I'll come to ESRF to install the new mac so that we can debug. Mine is too old to be updated now.

**Comment by t20100** [comment]
Maybe related to https://pypi.org/project/numpy/1.21.0rc1/ released on the 24th of May?

**Comment by kif** [comment]
I confirm ... Able to reproduce the bug with numpy-RC

**Comment by kif** [comment]
https://github.com/numpy/numpy/pull/19142

**Comment by kif** [comment]
Fixed upstream ... waiting for numpy 1.21rc2.

**Comment by t20100** [comment]
LGTM, can this be merged?

**Pull request merged**
