### PR TITLE
[plot] rework ROI curve widget with object (Fix 1711)

### PR DESCRIPTION
**Pull request by payno**
- [x]  add the ROI Object
- [x] reset the API
- [x] move listener into the ROITable instead of the CurvesROIWidget
- [x] <s>Move the ROI object somewhere else ?</s>

The roles between CurvesROIWidget and ROITable are:

* ROITable: display ROIs and insure connection with the plot (curves) and rois
* CurvesROIWIdget define behavior to have and clicking 'add ROI' and 'remove ROI'

### CODE REVIEW

**Comment by payno** [comment]
PR #1713 should be merged before.

**Comment by payno** [comment]
- [ ]  add the ROI Object
- [ ] reset the API
- [ ] move listener into the ROITable instead of the CurvesROIWidget
- [ ] move the marker management into the ROI object ?

**Comment by payno** [comment]
All the 'standard ROI functionalities' have been moved to the ROITable.
The CurvesROIWidget only contains the behavior to have when requesting for a new ROI according to the existing ROIs.

current behavior modifications:

CurvesROIWidget + ROITable
- getRois return the dict of ROI **Object**
- setRois require a list of ROI object. If is a dict of ROI will deal with it but signal the deprecation warning

ROITable:

Removed:
    - fillFromROIDict function
    - nameslot
Deprecated:

    - getROIListAndDict. Even if deprecated returning ROI object

Added:
    - getRois
   - save
   - load
   - showAllMarkers
   - setMiddleROIMarkerFlag

In CurvesROIWidget I would like to remove the calculateROIs which has been deprecated since the v

    @deprecation.deprecated(replacement="calculateRois",
                            reason="CamelCase convention")
    def calculateROIs(self, *args, **kw):
        self.calculateRois(*args, **kw)

**Comment by payno** [comment]
Should the ROI object link to markers objects representing him (could avoid duplication of information such as draggable, color....) ?

**Comment by payno** [comment]
There is some approximation actually made by the calculation of netCounts and Raw Counts. 

For example in the case of the following curve : 

roi

We have RawCounts giving 8.0 and netCounts giving 2.0 instead of 4.0 and 1.0

I think you can change it to call the numpy.trapz. This shouldn't be too long no ?
What to you think @vasole, @t20100 

The new algorithm (first draw on the commit 3991be0db92090d0d5877623098037d5c5debbf7 ) would be something like:
- compute the area of the curve in the ROI (between the Xs included in the ROI)
- compute the integral between the quadrilateral defined by the curve intersection, ROI boundaries and the x axis to get the background.
- actually there is no interpolation made to get the correct y value of the intersection between the curve and the ROI boundaries. We are simply taking the closest. That might be interesting to add a few more operation here no ?

**Comment by payno** [comment]
This PR is close to be complete.
Two questions remains:

- should we have to CurvesRoiWidget to insure full compatibility
- I think the ROI should be moved out from the widget but where can we add it. Consecutively what could be merge between the ROI '1D' and the newest ROI '2D' from @t20100 to have at least a common base class even if not a lot seem generic.

**Comment by payno** [comment]
Now classes look like:


diagcurvesroiwidget

**Comment by payno** [comment]
Maybe to generalize for n d we could have something like:

diagramcurvesroiwidget2

**Comment by vasole** [comment]
A word of caution. In the example you give, the correct results (as of today) should be 8 for the raw counts and 4 for the net counts.

I'm not against having different algorithms available. It can be useful to cross check fit results for instance.

**Comment by payno** [comment]
Agree for the different algorithm (at least having areas). For the net counts it gives 2.0 which is correct from my point of view because raw is 8 and background is 6*1.

**Comment by vasole** [comment]
@payno 

``For the net counts it gives 2.0 which is correct from my point of view because raw is 8 and background is 6*1.``

Correct, the contribution of each channel at 2 is 2-1.

**Comment by payno** [comment]
I think having a ROI is good but we should discuss with @t20100 to define 1D/2D/3D ROI common base class / API

**Comment by t20100** [comment]
Yes, if it's possible, it would make sense to have similar API for all ROIs.

**Comment by payno** [comment]
@t20100 :
After looking the `RegionOfInterest` Object I guess we can start with a simple class (_BaseRegionOfInterest) for example which will be something like:

_BaseRegionOfInterest(qt.QObject) containing:

- QSignal sigChanged (or sigRegionChanged) as you prefer
- name (which will replace the curren t_label from RegionOfInterest)
- self._editable
- we might also add the _id that I am using in the 1D ROI

**Pull request merged**
