### PR TITLE
plot backend clean-up

### PR DESCRIPTION
**Pull request by t20100**
This PR clean-up the `z` argument from plot backend `add*` method which is no longer used.

### CODE REVIEW

**Comment by vasole** [comment]
May I ask how you make sure who is on top?

**Comment by vallsv** [comment]
The backend API is supposed to be private. BTW it is often changed, basically on every releases.

**Comment by vasole** [comment]
The call with z=XXX was not private and it was used to decide what curve was on top of the others for instance.

**Comment by vallsv** [comment]
`z=XXX` from `BackendBase`?

**Comment by vasole** [comment]
OK. If it is kept at the high level interface (PlotWidget) it is fine.

**Comment by vallsv** [comment]
I have fixed the conflict with the master, waiting for CI

**Comment by vallsv** [comment]
There is problem with the installation of setuptools in the Linux CI.
As the tests pass on Windows and the changes are not platform dependant, i merge it.

**Comment by vallsv** [comment]
THe problem is about pip 20.0 -> https://github.com/pypa/pip/issues/7620

**Comment by t20100** [comment]
@vasole , the handling of `z` order is now done by the `PlotWidget`, no longer by the backend, this PR just removed arguments that were no longer used.

**Pull request merged**
