### PR TITLE
fix PY3 bug when generating NXdata examples in hdf5widget

### PR DESCRIPTION
**Pull request by PiRK**
Usual issues with sequences of unicode not handled by h5py.

### CODE REVIEW

**Comment by vasole** [comment]
You should prepend a "u" in front of all those attributes in order to make sure you get the same output in python2 and python3.

**Comment by vasole** [comment]
Example:

``gd1.attrs["title"] = "x, y, values scatter with asymmetric y_errors"``

should become

``gd1.attrs["title"] = u"x, y, values scatter with asymmetric y_errors"``

**Comment by PiRK** [comment]
It may work for single strings in this specific case, but it crashes with tuples of strings:
`gd1.attrs["axes"] = u"x", u"y"

It also crashes with single strings if, instead of assigning the value with `=` we use the `.create` method:
`gd1.attrs.create("title", u"x, y, values scatter with asymmetric y_errors"`

Initially all these strings had a `"b"` prepended, which worked in all these cases, but it produced ASCII encoding.

**Comment by PiRK** [comment]
h5py is very picky with its implicit `unicode` -> `UTF-8` conversion. I found that the only method that works in absolutely all cases for writing utf-8 is 
```
gd1.attrs["axes"] = numpy.array(whatever,
                                                     dtype=h5py.special_dtype(vlen=six.text_type))
```

**Comment by vasole** [comment]
I already reported that. I was explicitly referring to the single string case. Whenever one has more than one string one has to pass by the numpy.array with special type.

**Pull request merged**
