### PR TITLE
Simplification of fit configuration module.

### PR DESCRIPTION
**Pull request by PiRK**
This PR replaces QScriptOption with a new simpler widget.

### CODE REVIEW

**Comment by vasole** [comment]
Looks good. Some minor things:

[] - Initialize "internal background" to 2 and 5000 instead of 1 and 10000.
[] - When the user has configured the "internal background" via the interface, the estimation should reflect the user parameters and not the default.
[] - Somehow there is a CIRITICAL error calculating the covariance matrix when using the internal background as background.

**Comment by vasole** [comment]
- Where the interface says curvature it should say width.
- The curvature factor should always be one.
- An additional parameter for a smoothing width is needed for a complete characterization

**Comment by vasole** [comment]
- Unit test needs to be updated (testFitConfig.py line 77). The assert is now to be made with a value of 2 and not 1.

**Comment by PiRK** [comment]
This PR closes #249

**Comment by vasole** [comment]
The estimation of the step is wrong. You should not remove the background. Just calculate the derivative and pass that to the estimate function for the Gaussian functions.

**Pull request merged**
