### PR TITLE
[Plot] Add a Colorbar widget

### LINKED ISSUE #261: [Plot] Plot 2D: is it possible to add a colorbar (optional)?

### PR DESCRIPTION
**Pull request by t20100**
This PR proposes to add a widget displaying a colorbar synchronized with a PlotWidget displayed image or default colormap.
It wraps matplotlib colorbar in a QWidget to automate synchronisation.

TODO:
- [ ] More tests
- [ ] Add a button to edit the colormap
- [ ] Integrate with Plot2D and ImageView
- [ ] If possible rework layout to avoid having to much white space...

Closes #261

### CODE REVIEW

**Comment by vasole** [comment]
An alternative more widespread than I initially thought is to put the colorbar into the plot area.
Just for the record:
https://github.com/ppinard/matplotlib-colorbar
It works fine when there are no labels associated to the colorbar. If there are, it can be ugly

**Comment by t20100** [comment]
My idea was at first to simply wrap matplotlib colorbar in a dedicated widget which can connect to a silx plot in order to sync it with current plot colormap.
This also allow to reuse it in other context (e.g., with a 3D plot)

**Comment by vasole** [comment]
At this point is not critical, but I do not like to see a dependency on matplotlib under Colors.py

On my understanding, when the OpenGL plot backend will be ready, silx should be able to perform 1D and 2D plotting without having matplotlib installed.

**Comment by t20100** [comment]
Closing this PR, PR #664 supersedes it.

**Pull request closed without merging**
