### PR TITLE
[plot] make image mask always return 2D array

### PR DESCRIPTION
**Pull request by t20100**
This PR makes image mask `getSelectionMask` always return 2D arrays.
Related to #1765

### CODE REVIEW

**Comment by t20100** [comment]
Also fixes reset of mask when removing image while the mask widget is hidden.

**Comment by vallsv** [comment]
Before merging we have to check that PyFAI is still working with.

**Comment by vallsv** [comment]
No problem with PyFAI, but i send you a PR to fix an example.

**Comment by vallsv** [comment]
LGTM

**Pull request merged**
