### PR TITLE
Trying to fix issue from #2120

### PR DESCRIPTION
**Pull request by alexmarie78**
I can't import hdf5plugin as the computer doesn't have it installed.
I don't have the rights to install it, thus I can't start "run_tests.py" optimally.
Maybe someone can have a try ?

### CODE REVIEW

**Comment by vasole** [comment]
The code below does not require any rights

```
pip install --user
```

**Comment by alexmarie78** [comment]
Hi, I'll correct that, thanks.
About hdf5plugin, the issue is while I run "run_tests.py", there are few importError caused by hdf5plugin is missing. And by "rights" I meant that I can't install on this computer as it is not my personal one.

**Comment by t20100** [comment]
Having a quick look at it, changing:
```
try:
    import fabio
except ImportError:
    fabio = None
```
to `import fabio` is not the only change to do.
Every place where the availability of `fabio` or `h5py` is checked can be cleaned-up.
E.g., for `silx/examples/compareImages.py` line 134:
```
    if fabio is None and PIL is None:
        raise ImportError("fabio nor PIL are available")

    if fabio is not None:
        try:
            return fabio.open(filename).data
        except Exception:
            _logger.debug("Error while loading image with fabio", exc_info=True)
```
can be replaced with:
```
    if PIL is None:
        raise ImportError("fabio nor PIL are available")

    try:
        return fabio.open(filename).data
    except Exception:
        _logger.debug("Error while loading image with fabio", exc_info=True)
```

Also `run_tests.py` should be kept as it is. It is an exception as we share it across multiple projects so it is best to keep it generic.

It is best to make small Pull Requests with only a few file changed (e.g., all examples, then submodule by submodule): it will get merged faster in the master.

**Comment by alexmarie78** [comment]
Splitted in two patch set, one for fabio and the other one for h5py.
Hope it will be okay for you

**Comment by t20100** [comment]
Good, splitting is better for us, thanks!

**Pull request merged**
