### PR TITLE
[specfile] use locale.h on Windows

### PR DESCRIPTION
**Pull request by woutdenolf**
Fix issue #3315

### CODE REVIEW

**Comment by woutdenolf** [comment]
@pierrepaleo I used the 0.14 branch as base for the merge. Is that ok?

**Comment by pierrepaleo** [comment]
Yes perfect ! The fixes have to target 0.14.

**Comment by vasole** [comment]
On windows the correct solution would be to use _atof_l

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/atof-atof-l-wtof-wtof-l?view=msvc-160

**Comment by woutdenolf** [comment]
So the use to locale to convert strings to floats in the specfile C-code was disabled on Windows. So I enabled it again and solved what was probably the original issue that was "fixed" by disabling it: the static buffer for the locale name was too short. See here:
https://docs.microsoft.com/en-us/windows/win32/intl/locale-name-constants

On my windows laptop: `localeBuffer = "Dutch_Belgium.1252" (18+1 characters)
On appveyor: "localeBuffer = English_United States.1252" (26+1 characters)

It seems people are using `LOCALE_NAME_MAX_LENGTH=85` so I did the same. But it might be better to use `malloc` or `_atof_l`.

@vasole Is `_atof_l` platform independent?

**Comment by woutdenolf** [comment]
Actually the exit code `-1073740791` (0xC0000409) is STATUS_STACK_BUFFER_OVERRUN. And this was exactly the problem. Sometimes exit codes are helpful ;-).

**Comment by vasole** [comment]
_atof_l is the windows equivalent of strtod_l that is the solution used when setting SPECFILE_USE_GNU_SOURCE

**Comment by vasole** [comment]
I have made a (I think) more efficient implementation, but I do not want to delay things. Since the problem is already solved, I will wait for the release to merge.

**Pull request merged**
