### PR TITLE
[convert] Improve optional arguments

### LINKED ISSUE #1104: [silx convert] Do not compress everything in the output hdf5
After discussion with @vasole, it would be nice if compression is only for data.
Possible options:

-  provide a minimum dataset size for which compression is applied;
-  only apply compression in detectors group.

(From discussion in PR #1053)

### LINKED ISSUE #1105: [silx convert] Add silx version information in output hdf5 file
From discussion in PR #1053:

> It would be good to write somewhere that the file was generated by silx-convert with the "silx version". This kind of information can be very useful at one point. Maybe Nexus files have a specific field for that?

### PR DESCRIPTION
**Pull request by PiRK**
This PR implements several changes for convert:
- set a minimum dataset size for applying compression and chunking (closes #1104)
- create root group by default, provide an option to disable it if the users really wants to merge files (temporary fix for #1127 until we deal with stacks of files)
- write a `silx_version` dataset (closes #1105)
- implement URI, remove `--hdf5-path` option (mentioned in #1127)

### CODE REVIEW

**Comment by vasole** [comment]
I find the 1 MByte limit safe but too small as there are file systems where the minimum block that can be read or written is already 4 MBytes. 

The performance issues due to compression are when the chunk size is beyond the cache used for chunking, The default cache chunk size is 1 MByte by default. What we have to make sure/control is that the chunk size is not bigger than the cache chunk size.

**Comment by vasole** [comment]
After discussion, it seems the simplest solution is:

- Base compression or not of the dataset on the number of elements of the dataset (i.e. medipix images are small and would not be compressed based on size). A default limit of 500 elements seems convenient and user should be able to overwrite the default.

- Perform a check about the size (in bytes) of the chunk is below the currently used cache size.  See slides 30-37 of: 

https://support.hdfgroup.org/HDF5/doc/Advanced/Chunking/Chunking_Tutorial_EOS13_2009.pdf

**Comment by PiRK** [comment]
To be merged *after* #1135

**Comment by vallsv** [comment]
LGTM

**Pull request merged**
