### PR TITLE
Prefix for resources

### PR DESCRIPTION
**Pull request by vallsv**
- Fix timeout on test of external resources
- Add `is_dir` and `list_dir`
- Allow to specify a prefix to resource names: "silx:foo.png". It allow to use the same framework for other projects. It will reduce a lot of code duplication, especially on the GUI part.
- Move resources used in tests on a `silx.test.resources` package

```
# For example we can do that in PyFAI

import silx.resources
silx.resources.register_resource_directory("pyfai", pyFAI.resources)
# The package "pyFAI.resources" must have the same structure of the one from silx.

filename = silx.resources.resource_filename("pyfai:calibrant/my_calibrant.C")

import silx.opencl.utils
filename = silx.opencl.utils.get_cl_file("pyfai:my_program")

import silx.gui.icons
icon = silx.gui.icons.getIcons("pyfai:my_funky_icon")
```

### CODE REVIEW

**Comment by t20100** [comment]
Closes #379

**Comment by t20100** [comment]
Allow `register_resource_directory` to take either a package name or a path (in case resources are not stored in a python package, e.g., for Debian).

Question to discuss: For external resources, `getQIcon` is adding `gui/icons/` to the icon path. I'd prefer to use absolute path for external resources rather than forcing users to store them in a gui/icons/ directory. @vallsv has the opposite opinion. Any other opinions?

**Comment by t20100** [comment]
For the test of resources, it would be better to avoid having data files outside `silx.resources` to ease extraction of data from package.
An option is to create a temporary folder with some files to test it, but it prevents testing pkg_resources...

**Comment by vallsv** [comment]
- registration function was reworked to be able to force a directory
- resources for tests was removed (and temp file are not used)

**Comment by kif** [comment]
TV: namespace + path VV suggest 'namespace:path', 
    TV agrees with a single parameter, while a 2-parameter field would look easier in a first instance 
    but more complicated in the long term as there will always be 2 parameters to forward in every function to be called. ('gui/icons/icon.png', project='silx')
    This field should be unique, so a single string makes more sense.
    examples: "gui/icons/icon.png" or "silx:gui/icons/icon.png" or "pyFAI:gui/icon/another.png"
    We agreed that if there is a prefix before colon, the path provided after should be complete related to the project's resource root.
    i.e. "silx:logo" will NOT resolve logo into gui/icon/logo.png.

**Pull request merged**
