### PR TITLE
silx.gui: Renamed `exec_` methods to `exec` for compatibility with Qt6

### PR DESCRIPTION
**Pull request by t20100**
This makes PyQt5/PySide2 provide PyQt6/PySide6 API regarding `exec_` -> `exec` renaming:
- It adds necessary `exec` methods to Qt objects providing `exec_` for PyQt5 and PySide2
- It makes use of `exec` throughout silx.
- `exec_` methods in silx are renamed `exec` to be consistent but `exec_` compatibility wrapper are also provided (without deprecation warnings).
- For `FitWidget`, since API allows to provide dialogs (`FitWidget.associateConfigDialog`), here it works with either `exec` (tried first) or `exec_` (as now).

This avoids warnings with PySide6.

Related to #3432

### CODE REVIEW

**Comment by t20100** [comment]
Rebased to use`pytest`. Ready for review.

**Comment by t20100** [comment]
Test fixed, ready for review

**Comment by vallsv** [comment]
Sounds good.

COuld you add a test to check that `exec_` still exists in Qt5?

**Comment by t20100** [comment]
- Added some tests for `exec_` and `exec` method availability.
- Also reworked the wrapper: both using lambda function or assigning `<class>.exec = <class>.exec_` failed.

Ready for review.

Note: As opposed to previous attempts, the `exec` method is only available through `silx.gui.qt` and not directly from the binding.

**Comment by payno** [comment]
LGTM

**Pull request merged**
