### PR TITLE
[silx.math.combo] Fix 1261

### PR DESCRIPTION
**Pull request by payno**

### CODE REVIEW

**Comment by vallsv** [comment]
I found that on our code, which should be more explict.

From chistogram
```
import numpy as np
ctypedef fused lut_t:
    np.int64_t
    np.int32_t
    np.int16_t
```
or from fabio
```
cimport numpy as cnp
ctypedef fused any_int_t:
    cnp.int8_t
    cnp.int16_t
    cnp.int32_t
    cnp.int64_t
```

**Comment by payno** [comment]
should close #1261

**Comment by t20100** [comment]
chistogram also depends on numpy at C level, there is a `cimport numpy as np`.

**Comment by t20100** [comment]
Ideal solution would be to have signed types definition without relying on numpy.

**Pull request merged**
