### PR TITLE
[ci] Use PySide2 from pypi

### PR DESCRIPTION
**Pull request by t20100**
This PR load PySide2 from pypi rather than from nightly build, andwait for window exposed in stat widget test.

### CODE REVIEW

**Comment by t20100** [comment]
Looks that there is quite a few issues with the latest version of pyside2 (5.12.0).... should be good to have the time to look at it before the release...

**Comment by vallsv** [comment]
Could be rebased over the master?

**Comment by t20100** [comment]
Rebased.

**Comment by vallsv** [comment]
Error on Python 3.7 only. Both Windows and Linux.
```
ERROR: testFailingConverters (silx.gui.plot.tools.test.testTools.TestPositionInfo)
Test PositionInfo with failing custom converters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\tools\test\testTools.py", line 134, in testFailingConverters
    self._test(positionWidget, ['Exception'], error=2)
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\tools\test\testTools.py", line 108, in _test
    self.mouseMove(self.plot, pos=(1, 1))
  File "C:\projects\silx\venv_test\lib\site-packages\silx\utils\testutils.py", line 183, in __exit__
    expected_count, logging.getLevelName(level), count))
RuntimeError: Expected 2 ERROR logging messages, got 0
======================================================================
FAIL: test (silx.gui.plot.test.testPlotInteraction.TestSelectPolygon)
Test draw polygons + events
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\test\testPlotInteraction.py", line 141, in test
    self.assertEqual(len(drawEvents[-1]['points']), 3)
AssertionError: 4 != 3
======================================================================
SKIPPED: testMovieIconExists (silx.gui.test.test_icons.TestAnimatedIcons)
```

**Comment by t20100** [comment]
This errors looks to be related with the new version of PyQt5...

**Comment by t20100** [comment]
Ready to merge: basically use pyside2 5.11.1 release on pypi rather than outdated nightly build.
Prepare for pyside2 5.12.x where shiboken2 is a separate package

**Comment by vallsv** [comment]
LGTM. There packaging looks strange BTW.

**Pull request merged**
