### PR TITLE
[ci] update appveyor config

### PR DESCRIPTION
**Pull request by t20100**
Attempt to fix appveyor issue

### CODE REVIEW

**Comment by t20100** [comment]
related to #1961

**Comment by payno** [comment]
LGTM

**Comment by charris** [comment]
If anyone here is in a position to do so, we (NumPy) would appreciate a bisection to discover which commit caused this problem.

**Comment by t20100** [comment]
@charris, I reproduced the issue with `import numpy; import PyQt5.QtCore` and it disappear when I build numpy from source (see https://github.com/numpy/numpy/issues/11431#issuecomment-401041624)

**Pull request merged**
