### PR TITLE
fix 2390 - ICR roi color and middle marker visibility

### PR DESCRIPTION
**Pull request by payno**
if ROI is ICR then set back default marker color to black and hide middle - marker

### CODE REVIEW

**Comment by vasole** [comment]
- Default color is black for the ICR
- Default color is blue for the other markers
- Default color for the middle marker is yellow
- Default behavior is no middle marker

**Comment by payno** [comment]
close #2390

**Comment by vasole** [comment]
Not fixed by latest commit.

What is not respected is the behavior requested by a call  ``setMiddleROIMarkerFlag(True)``

**Comment by vasole** [comment]
The behavior seems correct now. The deprecation warning corrected with #2389 is present in the code.

**Pull request merged**
