### PR TITLE
Update silx-view mime type association

### LINKED ISSUE #1549: Please add mime type to silx view
It would be great if we could double click on a supported file and open it directly from the nautilus etc...

Can you add .desktop files for silx view and set the right mime-type

https://developer.gnome.org/integration-guide/stable/mime.html.en

It would be great also add edf as an image type :)

Cheers

Frederic

Ps: Same of other esrf tools  ;)

### PR DESCRIPTION
**Pull request by vallsv**
Closes #1549

### CODE REVIEW

**Comment by vallsv** [comment]
I still have problem with this PR

No idea how to create the default association. Everything looks fine but nautilus dont fine any default application.

```
$ sudo cp package/desktop/org.silx.SilxView.desktop /usr/share/applications/
$ sudo cp package/desktop/silx.xml /usr/share/mime/packages/

# update the database
$ sudo update-mime-database /usr/share/mime
$ sudo update-desktop-database
```

Here the associations looks fine:
```
$ more /usr/share/applications/mimeinfo.cache | grep -i silx
application/x-hdf=hdfview.desktop;org.silx.SilxView.desktop;
application/x-silx-hdf5=org.silx.SilxView.desktop;
application/x-silx-nexus=org.silx.SilxView.desktop;
application/x-silx-specfile=org.silx.SilxView.desktop;
image/tiff=display-im6.q16.desktop;display-im6.desktop;evince.desktop;gimp.desktop;evince-previewer.desktop;rawtherapee.desktop;eog.desktop;org.silx.SilxView.desktop;
image/x-silx-cbf=org.silx.SilxView.desktop;
image/x-silx-edf=org.silx.SilxView.desktop;
image/x-silx-marccd=org.silx.SilxView.desktop;
image/x-silx-numpy=org.silx.SilxView.desktop;
```

But no default application is found
```
$ xdg-mime query default image/png  # it works for a PNG file
eog.desktop
$ xdg-mime query default image/x-silx-edf  # No output
$ xdg-mime query default application/x-hdf  # No output for the default hdfviewer
```

The custom mimetype is right, but the association with the application is not found:
```
$ xdg-mime query filetype ../data/edf/medipix.edf
image/x-silx-edf
$ xdg-open ../data/edf/medipix.edf
gvfs-open: ../data/edf/medipix.edf: error opening location: No application is registered as handling this file
```

I try to create a `/usr/share/applications/silx/mimeapps.list` contains default associations, but while `/usr/share/applications/mimeinfo.cache` is fine, i dont really understand why we should duplicate this informations. Maybe we have to call `xdg-mime default <application> <mimetype>` at the post installation of the scripts?

Do you have any idea @picca? Some hint can be very useful.

**Comment by picca** [comment]
I have never done this by myself, sorry, but on my stretch I have this

picca@diffabs6:~/hkl$ xdg-mime query default application/x-hdf
hdfview.desktop

Maybe somethig else is done during the installation of the package...

**Comment by picca** [comment]
Here the files of the hdfview package.

```
/.
/usr
/usr/bin
/usr/bin/hdfview
/usr/share
/usr/share/applications
/usr/share/applications/hdfview.desktop
/usr/share/doc
/usr/share/doc/hdfview
/usr/share/doc/hdfview/changelog.Debian.amd64.gz
/usr/share/doc/hdfview/changelog.Debian.gz
/usr/share/doc/hdfview/copyright
/usr/share/icons
/usr/share/icons/hicolor
/usr/share/icons/hicolor/16x16
/usr/share/icons/hicolor/16x16/apps
/usr/share/icons/hicolor/16x16/apps/hdfview.png
/usr/share/icons/hicolor/16x16/mimetypes
/usr/share/icons/hicolor/16x16/mimetypes/application-x-hdf.png
/usr/share/icons/hicolor/22x22
/usr/share/icons/hicolor/22x22/apps
/usr/share/icons/hicolor/22x22/apps/hdfview.png
/usr/share/icons/hicolor/22x22/mimetypes
/usr/share/icons/hicolor/22x22/mimetypes/application-x-hdf.png
/usr/share/icons/hicolor/24x24
/usr/share/icons/hicolor/24x24/apps
/usr/share/icons/hicolor/24x24/apps/hdfview.png
/usr/share/icons/hicolor/24x24/mimetypes
/usr/share/icons/hicolor/24x24/mimetypes/application-x-hdf.png
/usr/share/icons/hicolor/32x32
/usr/share/icons/hicolor/32x32/apps
/usr/share/icons/hicolor/32x32/apps/hdfview.png
/usr/share/icons/hicolor/32x32/mimetypes
/usr/share/icons/hicolor/32x32/mimetypes/application-x-hdf.png
/usr/share/icons/hicolor/48x48
/usr/share/icons/hicolor/48x48/apps
/usr/share/icons/hicolor/48x48/apps/hdfview.png
/usr/share/icons/hicolor/48x48/mimetypes
/usr/share/icons/hicolor/48x48/mimetypes/application-x-hdf.png
/usr/share/icons/hicolor/64x64
/usr/share/icons/hicolor/64x64/apps
/usr/share/icons/hicolor/64x64/apps/hdfview.png
/usr/share/icons/hicolor/64x64/mimetypes
/usr/share/icons/hicolor/64x64/mimetypes/application-x-hdf.png
/usr/share/icons/hicolor/96x96
/usr/share/icons/hicolor/96x96/apps
/usr/share/icons/hicolor/96x96/apps/hdfview.png
/usr/share/icons/hicolor/96x96/mimetypes
/usr/share/icons/hicolor/96x96/mimetypes/application-x-hdf.png
/usr/share/java
/usr/share/java/jhdfview.jar
```

**Comment by picca** [comment]
Here the desktop file

```
[Desktop Entry]
Exec=/usr/bin/hdfview %F
MimeType=application/x-hdf;
Name=hdfview
Name[de]=hdfview
Name[en]=hdfview
Comment=HDF4/5 Data Browser
Comment[DE]=HDF4/5 Daten Browser
Comment[EN]=HDF4/5 Data Browser
Terminal=false
Type=Application
X-MultipleArgs=true
Categories=Science;Physics;DataVisualization;Education;
Icon=hdfview
```


So it seems that this is enought.

Maybe just let this like this and  we will see if it works for the next silx package :))

**Comment by vallsv** [comment]
Thanks, i will try it.
Maybe it works cause `application/x-hdf` is already defined.

**Comment by vallsv** [comment]
Thanks a lot. My `.local` was polluted.
Then it was working.
You will be able to open h5, edf, cbf, tif, spec and few others with a double click.

**Comment by picca** [comment]
alleluia :))

**Pull request merged**
