### PR TITLE
silx.gui.plot: Fixed RegionOfInterest `contains`

### LINKED ISSUE #3335: Right button click on a plot with profile tools leads to an exception
With both current master and 0.14 branch, creating a horizontal line profile on an image and then pressing right click on the plot leads to this exception:
```
ERROR:silx.gui.qt._qt:<class 'TypeError'> 'float' object is not subscriptable   File "/silx/gui/plot/tools/roi.py", line 606, in _feedContextMenu
    if roi.contains(data):
  File "/silx/gui/plot/items/roi.py", line 405, in contains
    return position[1] == self.getPosition()[1]
```
It is not the case with silx v0.13.2.

Reproducible with `examples/plotInteractiveImageROI.py` or `silx view` with an image

### PR DESCRIPTION
**Pull request by t20100**
This PR fixes crashes on right click with profiles and ROIs by implementing `contains` methods.
Those methods are exact, so their use in interaction might not be ideal since it is almost impossible.

Still todo: ellipse and testing.

closes #3335

### CODE REVIEW

**Comment by vallsv** [comment]
Be careful you have triggered other commits with this PR.

**Comment by pierrepaleo** [comment]
Thanks ! Can you target `0.14` ?

**Comment by t20100** [comment]
Ready for review.
I'm doing a bit more testing but it should be OK.

**Comment by t20100** [comment]
Added entry in changelog

**Comment by t20100** [comment]
There's still a bug to fix... and `contains` does not always return a `bool`.

**Comment by t20100** [comment]
Fixed bug in circle ROI and make sure `contains` always return a `bool` (it wasn't the case with `LineROI`).

**Review by payno — APPROVED** [review]
LGTM

**Pull request merged**
