### PR TITLE
Hdf5tree test and documentation

### PR DESCRIPTION
**Pull request by vallsv**
- test (with a good coverage of the model and the sorting)
- simple documentation
- public API
- few small fixes

```
Name                                                                 Stmts   Miss  Cover
----------------------------------------------------------------------------------------
build/lib.linux-x86_64-2.7/silx/gui/hdf5/Hdf5HeaderView                 81     42    48%
build/lib.linux-x86_64-2.7/silx/gui/hdf5/Hdf5Item                      232     60    74%
build/lib.linux-x86_64-2.7/silx/gui/hdf5/Hdf5LoadingItem                29     14    52%
build/lib.linux-x86_64-2.7/silx/gui/hdf5/Hdf5Node                       55      9    84%
build/lib.linux-x86_64-2.7/silx/gui/hdf5/Hdf5TreeModel                 318     69    78%
build/lib.linux-x86_64-2.7/silx/gui/hdf5/Hdf5TreeView                   98     52    47%
build/lib.linux-x86_64-2.7/silx/gui/hdf5/NexusSortFilterProxyModel      57      6    89%
build/lib.linux-x86_64-2.7/silx/gui/hdf5/__init__                       10      0   100%
build/lib.linux-x86_64-2.7/silx/gui/hdf5/_utils                        105     60    43%
----------------------------------------------------------------------------------------
TOTAL                                                                  985    312    68%
```

### CODE REVIEW

**Comment by vallsv** [comment]
Let me know if something is missing

**Comment by payno** [comment]
l 171 in the test_hdf5.py 
you have a call to "encode" with the default parameter.
Shouldn't we set the type we wan't to use ? Specifing the type to avoid some (hypothetical) issue later ?  (self.setData(self.MIME_TYPE, "".encode(encoding='utf-8')))

**Comment by vallsv** [comment]
I still have to update the documentation

**Comment by vallsv** [comment]
It should be fine know :-)

**Comment by t20100** [comment]
Looks good to me

**Comment by vallsv** [comment]
Let see if it improve the tests

**Pull request merged**
