### PR TITLE
Icon for unsupported ROIs

### PR DESCRIPTION
**Pull request by vallsv**
This PR allow to use costom ROIs in the ROI manager.
A default display will be provided.

### CODE REVIEW

**Comment by t20100** [comment]
The icon looks to have an embedded PNG image, it would be better to avoid it for optimum compatibility.
We had issues with icons with images, so it is best to avoid it in new icons

**Comment by t20100** [comment]
I made a PR on your branch with an optimized svg file

**Comment by vallsv** [comment]
Oups, maybe i missing to remove my shadok template.
It would be better to fully remove it from the history, i guess it's a big image.

**Comment by t20100** [comment]
It's probably nothing compared to the history of Cython generated files...

**Comment by vallsv** [comment]
Yes you are right. Anyway, this PR is now cleaned up from the RAW image.

**Pull request merged**
