### PR TITLE
Add copy-to-clipboard icon to HDF5 view

### PR DESCRIPTION
**Pull request by t20100**
This PR adds a copy to clipboard icon on the right side of each field in the HDF5 view `Hdf5TableView` (used in `silx view`).

There are recurrent questions about how to copy-paste those fields (e.g., PR #2758, issue #573 ...).
This PR proposes an explicit way (through a button) to do so similar to what's currently done on web pages.

Screenshot (see icons on the right side):
Screenshot from 2020-01-22 16-57-54

### CODE REVIEW

**Comment by vallsv** [comment]
I really don't think it is a good idea, cause there is too much icons for a very basic feature. And it is non consistent, or you will also add that to the compression cells?

A tooltip make more sense. Or allow to select the text with the mouse (which should not be a big deal).

**Comment by t20100** [comment]
I'd say the key things to copy are in "Path Info". I was even thinking of putting the copy icons only there. For me, an icon for a basic thing that is often used is fine.

People does not find how to copy with `Ctrl-C` by themselves, the icon is an explicit way to provide it, any other way is not.

The selectable text is a good option though, it makes more explicit that you can do `Ctrl-C`.

**Comment by vallsv** [comment]
But if there is no time for better solution, it;s fine. It can be merged.

**Comment by t20100** [comment]
Let's see what we can do with selectable text rather than selectable cells.

**Comment by vallsv** [comment]
AppVeyor looks broken

**Comment by vallsv** [comment]
Superseded by #2903

**Pull request closed without merging**
