### PR TITLE
[plot] Add support for more colormap normalization

### PR DESCRIPTION
**Pull request by t20100**
This PR is a first step to add more normalization to `Colormap` and add a `sqrt` normalization.

Tasks:
- [x] Refactor `Colormap` class to ease integration of new colormap normalizations.
- [x] Refactor `ColorBar` to ease integration of new colormap normalizations.
- [x] Rework `ColormapDialog` to support new colormap normalizations
- [x] Support in `plot` OpenGL backend
- [x] Support in `plot3d`

### CODE REVIEW

**Comment by t20100** [comment]
The `ColormapDialog` is partly done: it works for `sqrt` but its histogram is not normalized.
It would be great to have no specific code in `ColormapDialog` regarding normalization, but I doubt that's possible...

**Comment by vallsv** [comment]
Just a comment. Maybe you can use normal object for normalization, instead of static and class method. It just have to be initialized a single time `LINEAR: _LinearNormalization()`. I guess in Python the cost is the same. But i understand anyway you choice, it's also nice.

**Comment by t20100** [comment]
@vallsv, yes I might do that.

**Comment by t20100** [comment]
Fixed issues from CI tests, added support in OpenGL `plot` backend.

**Comment by t20100** [comment]
`plot3d` support added, `ColormapDialog` updated to have a more generic implementation to minimize cost of adding new normalizations.

**Comment by t20100** [comment]
This PR removes `DEFAULT_MIN_LOG` and `DEFAULT_MAX_LOG` module constants and `Colormap._getDefaultMin` and `Colormap._getDefaultMax` methods.
This (and more) is available through a "normalizer" object: `Colormap._getNormalizer()` which is private for now.

**Comment by t20100** [comment]
With this PR, adding new normalizations will be simpler:
- To add a normalization, one needs to implemented it as a subclass of `silx.gui.colors._Normalization`.
- The OpenGL plot backend has a fallback to compute the colormap outside of OpenGL, so it is optional to integrate the normalization in the OpenGL shader.
- The `ColorBar` handles normalization in a generic way (except if it is desired to use logscale ticks).
- The `ColormapDialog` still needs a bit of specific code but less.
- `plot3d` however requires that the normalization is implemented in the shader.

**Comment by vallsv** [comment]
I dont know if it is related:
```
Traceback (most recent call last):
  File "/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/dialog/ColormapDialog.py", line 729, in _displayDataInPlotModeChanged
    self._setDataInPlotMode(mode)
  File "/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/dialog/ColormapDialog.py", line 725, in _setDataInPlotMode
    self._updateDataInPlot()
  File "/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/dialog/ColormapDialog.py", line 768, in _updateDataInPlot
    histogram, bin_edges = self._getNormalizedHistogram()
  File "/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/dialog/ColormapDialog.py", line 419, in _getNormalizedHistogram
    histogram = self._computeNormalizedHistogram()
  File "/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/dialog/ColormapDialog.py", line 448, in _computeNormalizedHistogram
    counts, edges = self.parent().computeHistogram(data, scale=norm, dataRange=dataRange)
  File "/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/dialog/ColormapDialog.py", line 1118, in computeHistogram
    histogram = Histogramnd(data, n_bins=nbins, histo_range=data_range)
  File "/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/math/histogram.py", line 251, in __init__
    wh_dtype=self.__wh_dtype)
  File "silx/math/chistogramnd.pyx", line 235, in silx.math.chistogramnd.chistogramnd
    histo = np.zeros(output_shape, dtype=np.uint32)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

```

**Comment by vallsv** [comment]
When we switch to log or sqaure root, there is 5 times the same logs. Do you think we can reduce the amount?
```
WARNING:/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/colors.py:Invalid vmin, switching to autoscale for lower bound
WARNING:/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/colors.py:Invalid vmin, switching to autoscale for lower bound
WARNING:/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/colors.py:Invalid vmin, switching to autoscale for lower bound
WARNING:/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/colors.py:Invalid vmin, switching to autoscale for lower bound
WARNING:/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/colors.py:Invalid vmin, switching to autoscale for lower bound
```

**Comment by vallsv** [comment]
The 3 x stddev looks to be broken for log and square root

**Comment by t20100** [comment]
Do you have some data to reproduce?

**Comment by t20100** [comment]
Ok, issue with range always being the default one...

**Comment by vallsv** [comment]
Oh, weird, it uses the range 1..10, kind of default range?

Tested with:
```
./bootstrap.py examples/findContours.py
```

**Comment by t20100** [comment]
That was a poor typo.

**Comment by t20100** [comment]
The many warning logs are due to different parts (e.g., ColorBar, ColormapDialog, backend,...) asking the colormap range.
I move this log to `info`.

**Comment by t20100** [comment]
Fixed reported exception.

**Comment by vallsv** [comment]
LGTM

**Pull request merged**
