### PR TITLE
Misc: Fixed `silx test` application on Windows

### LINKED ISSUE #3410: Windows fat binary multiprocessing issue
There is an issue running `silx test` with Windows fat binary, I expect it is due to `multiprocessing` being used in `silx.io.h5py_utils` which makes a fork-bomb.
Using `multiprocessing.freeze_support()` should fix it.

### PR DESCRIPTION
**Pull request by t20100**
Avoid fork-bomb when running `silx test` with Windows fat binary.

closes #3410

### CODE REVIEW

**Comment by t20100** [comment]
Funny issue with `silx.app.view.test.test_launcher.TestLauncher.testExecuteSilxViewHelp` during `import multiprocessing` which does `import math` at some point, which imports `silx.math` because running `silx/__main__.py` as a script adds `silx/` to `sys.path`.
I fixed it by copying the file to run in a temporary directory.

**Comment by vallsv** [comment]
Could it be done using `-m` instead?

**Comment by t20100** [comment]
It would be definitely better but there's maybe a reason it was not already the case.

**Comment by t20100** [comment]
Looks tests now pass fine.

BTW, when running `silx test` in a Windows fat binary, some tests fails (see https://gitlab.esrf.fr/silx/bob/silx/-/jobs/191819) and I personnally think it is not an issue, but it is no longer a fork bomb.

**Pull request merged**
