### PR TITLE
silx.gui.plot: Added some statistic indicators in `PixelIntensitiesHistoAction` action

### LINKED ISSUE #3215: Add statistics indicator to PlotWidget histogram action
Adding display of min/max, mean/stdev, sum values to histogram action ("a la" oxidis).

Feedback from beamline.

### PR DESCRIPTION
**Pull request by t20100**
This PR adds basic stats (min, max, mean, std, sum) at the bottom of the histogram window of PixelIntensitiesHistoAction

closes #3215

### CODE REVIEW

**Comment by t20100** [comment]
Ready for review. To me it could be integrated in 0.15

I have some doubts/questions on the histogram behavior when items disappear from the plot, but I'll make a separate PR for this.

**Comment by t20100** [comment]
histogram behavior fixed in PR #3396

**Comment by vallsv** [comment]
I think it is not a good idea to use docks because you provide flexibility for no real need.

If you have to setup it every time you launch the appli, you don't win much.

Anyway I prefer to use it, you anyway have to handle properly the close of the dock.
If i am not wrong, for now you have to restart the application to display it back.

**Comment by t20100** [comment]
I used dock for convenience in the code, but I agree it should not be moved: I'll check whether to rewrite the window or to change the dock widget properties to disable closing and moving.

This is hidden but in the context menu of the toolbar of a main window, you can open the dock widgets... except that in the `PlotWidget` we overload the context menu so it is not available... Anyway, there is no way to guess that.

**Comment by vallsv** [comment]
It also could be part of the "Options" menu.

**Comment by t20100** [comment]
For the added stats in the histogram window, I'd to keep them always visible, this does not take much space.

**Comment by vallsv** [comment]
I agree, if people complain, you will have time to rework it.

**Comment by t20100** [comment]
Updated to avoid using a dock widget and have a widget for the histogram window that is separated from the action.

**Comment by t20100** [comment]
Added a `setItem` to the `HistogramWidget` and move item update tracking and histogram/stats computation there.
Also added use of `ElidedLabel` and `sizeHint` as in PR #3399

**Comment by t20100** [comment]
Added used of `ElidedLabel` similar to #3399

**Comment by vallsv** [comment]
Looks good to me

**Pull request merged**
