### PR TITLE
silx.io.url.DataUrl: Fixed slice provided as python slice string

### LINKED ISSUE #3265: Issue with DataUrl as string if provides `slice` with start and stop
the following url is find invalid: `url = DataUrl(path='silx:///data/visitor/ls2914/id19/set40_tomo_black_drum_LPJ21_6p5mu_unload/set40_tomo_black_drum_LPJ21_6p5mu_unload_0001/set40_tomo_black_drum_LPJ21_6p5mu_unload_0001_0000.nx?path=/entry0000/instrument/detector/data&slice=2000:2021')`

### PR DESCRIPTION
**Pull request by payno**
Closes #3265

### CODE REVIEW

**Comment by t20100** [comment]
What about supporting slices such as `:4`, `4:`, `::2`?
This sounds easy to add, basically: `int(s) if s else None`

**Comment by payno** [comment]
yes I forgot this case in fact. I will update it

**Comment by payno** [comment]
should be handle now.

**Comment by vallsv** [comment]
Closes #3265

**Pull request merged**
