### PR TITLE
[io] NXdata support signal_dataset_name_errors for signal_dataset_name

### LINKED ISSUE #2975: [silx view] VARIABLE_errors not handled in NXdata plots.
image

### PR DESCRIPTION
**Pull request by vasole**
closes #2975 

image

### CODE REVIEW

**Comment by t20100** [comment]
LGTM, appveyor seems to have some issues today,

**Comment by vasole** [comment]
Just make clear that for the x axis the support was already there.

image

**Comment by vallsv** [comment]
By chance is it easy to add a test on the parser?

**Comment by vasole** [comment]
Done.

**Comment by vasole** [comment]
It seems AppVeyor is trying to run the tests with me being not a member of the ESRF. If they are sun with me being an ESRF member they run properly:

https://ci.appveyor.com/project/ESRF/silx/builds/31688660

**Comment by vasole** [comment]
I guess last commit was not needed (despite being correct).

**Comment by vasole** [comment]
Ready for review.

**Pull request merged**
