### PR TITLE
Curve legends widget

### LINKED ISSUE #2009: Pymca-like display of legends?
Users would like to see legends like in PyMCA, under Plot1D without the need to click on 'options' then 'legends', and with a compact view.

### PR DESCRIPTION
**Pull request by t20100**
This PR adds a `CurveLegendsWidget` to the plot associated tools widgets.
The idea is to have a widget taking less space that `LegendSelector` and (at least as it is) with less functionalities (i.e., no possibility to change the curves).

curvelegendswidget

To acheive this, it uses a `FlowLayout` and reuse `LegendSelector` icon widget.

Todos:

- [x] Documentation
- [x] Tests
_- Improve FlowLayout size management and alignment (kept for later:  #2059)_

related to  #1447
closes #2009

### CODE REVIEW

**Comment by t20100** [comment]
Idea from @vallsv add active curve selection from the legend widget

**Comment by vasole** [comment]
What about implementing signals in line with sigLegendClicked and sigLegendContextMenuRequested? That would allow the application to implement whatever they want.

**Comment by t20100** [comment]
Good idea, that would allow extensions

**Comment by t20100** [comment]
Added:
- `sigCurveClicked` signal which provides the curve object corresponding to the clicked legend.
- `curveAt(QPoint)` method which returns the curve corresponding to the Legend widget at the given position. This makes it easy to use QWidget's customContextMenuRequested signal (see plotCurveLegendsWidget.py for sample code) and is even more generic (this is used for the `sigCurveClicked`)

I opened issue #2059 to do " Improve FlowLayout size management and alignment" later, so ready for review.

**Comment by t20100** [comment]
Update: instead of hiding the legend when the curve is hidden, it is now displayed with 'disabled' style.
Example updated with show/hide curve context menu option and active curve set/unset.

**Comment by PiRK** [comment]
LGTM.

**Pull request merged**
