### PR TITLE
[plot] Keep profile window always on top

### LINKED ISSUE #2935: [plot] Switch profile windows as dialog
I think it would be better to set our side windows (like the profile window) always over there main parent window.

This can be achieved by using `windowFlags` with `qt.Qt.Dialog` + hint for minimize/maximize.

I guess there is not only the profile window to patch.

Could we do it in silx?

### PR DESCRIPTION
**Pull request by t20100**
This PR ensures the profile window remains on top of the plot window.

closes #2935

### CODE REVIEW

**Comment by vallsv** [comment]
Yet i did not try, but i think this PR will not behave as expected.

I mean it should not be displayed on the top of all the applications. But only on the top of the main window.

**Comment by t20100** [comment]
Yes, you are right, my bad.

**Comment by t20100** [comment]
This is using the `Dialog` flag instead.

**Comment by vallsv** [comment]
Ahahah i was thinking about doing that on my PR, i do not remember it was here ^_^

**Pull request merged**
