### PR TITLE
735 download

### LINKED ISSUE #735: Utilities to dowload test data
Ported from pyFAI

### PR DESCRIPTION
**Pull request by kif**
close #735

### CODE REVIEW

**Comment by kif** [comment]
A couple of comments:
* Damien suggests to handle checksums ... do we want/need this ?
* shall it be available to be used from outside silx ? (possibility to set alternative URLs, ...)

**Comment by dnaudet** [comment]
IMO if only used for silx tests, checksums are probably overkill and adds unnecessary complexity. I just added them to the xsocs download script because it didn't take me long.

**Comment by t20100** [comment]
`download_all` is not tested and uses a `getimage` method that was rename as `getfile`.

I would not provide default values for `project`, `url_base` and `env_key` in `TestResources.__init__`.
I'd rather provide them when instanciating it.

What about renaming `utilstest` to `testresources`, I find utilstest not meaningfull.

**Comment by dnaudet** [comment]
It looks like you update the json file before actually downloading the file, shouldnt it be the other way around?

**Pull request merged**
