### PR TITLE
Refactoring Mask

### PR DESCRIPTION
**Pull request by PiRK**
The Mask tools need some refactoring to be able to do masks on other type of data (not just images).

Older history is available here: https://github.com/PiRK/scripts/commits/master/ScatterMaskToolsWidget.py

Addresses #691

### CODE REVIEW

**Comment by PiRK** [comment]
Closes #710  (https://github.com/silx-kit/silx/pull/716/commits/f2a9636a6052acd48fb51aa521c81635a4517721)

**Comment by vasole** [comment]
An example or the possibility to execute the new modules would simplify code review.

**Comment by t20100** [comment]
I encountered a few issues while playing with it (on macOS, python3.5, PyQt5.8):

With both the image mask and the scatter mask example, there is an issue with the 'between' threshold. Here are the log for the image mask:
```
/Users/tvincent/src/silx/build/lib.macosx-10.6-intel-3.5/silx/gui/plot/BaseMask(
   1035                 max_ = float(self.maxLineEdit.text())
   1036                 self._mask.updateBetweenThresholds(self.levelSpinBox.val
-> 1037                                                    min_, max_)
   1038                 self._mask.commit()
   1039 

/Users/tvincent/src/silx/build/lib.macosx-10.6-intel-3.5/silx/gui/plot/BaseMask(
    263         :param bool mask: True to mask (default), False to unmask.
    264         """
--> 265         stencil = numpy.logical_and(min_ <= self._getValues(),
    266                                     self.getDataValues() <= max_)
    267         self.updateStencil(level, stencil, mask)

AttributeError: 'ImageMask' object has no attribute '_getValues'
```

With the scatter mask example:
- The button synchronise min/max of the threshold tool with the colormap does not update the min/max values.
- When setting log scale on an axis:
```
Traceback (most recent call last):
  File "/Users/tvincent/src/silx/build/lib.macosx-10.6-intel-3.5/silx/gui/plot/PlotActions.py", line 265, in _actionTriggered
    self.plot.setXAxisLogarithmic(checked)
  File "/Users/tvincent/src/silx/build/lib.macosx-10.6-intel-3.5/silx/gui/plot/Plot.py", line 1964, in setXAxisLogarithmic
    self.resetZoom()
  File "/Users/tvincent/src/silx/build/lib.macosx-10.6-intel-3.5/silx/gui/plot/Plot.py", line 2315, in resetZoom
    self._backend.resetZoom(dataMargins)
  File "/Users/tvincent/src/silx/build/lib.macosx-10.6-intel-3.5/silx/gui/plot/backends/BackendMatplotlib.py", line 541, in resetZoom
    ranges = self._plot.getDataRange()
  File "/Users/tvincent/src/silx/build/lib.macosx-10.6-intel-3.5/silx/gui/plot/Plot.py", line 430, in getDataRange
    self._updateDataRange()
  File "/Users/tvincent/src/silx/build/lib.macosx-10.6-intel-3.5/silx/gui/plot/Plot.py", line 397, in _updateDataRange
    bounds = item.getBounds()
  File "/Users/tvincent/src/silx/build/lib.macosx-10.6-intel-3.5/silx/gui/plot/items/core.py", line 96, in getBounds
    return self._getBounds()
  File "/Users/tvincent/src/silx/build/lib.macosx-10.6-intel-3.5/silx/gui/plot/items/core.py", line 621, in _getBounds
    displayed=True)
ValueError: too many values to unpack (expected 4)
```
This seems an issue with plot.items Scatter and Point classes conflict of cache attribute.

Otherwise, looks good to me.

**Comment by PiRK** [comment]
I fixed all the problems you mentioned, but I found another one for which I don't see an obvious solution: 
the "active" scatter handling is different from the active image handling.

The first image added is the active one, but there is no active scatter unless we specifically activate one. 
Currently the method `_activeScatterChanged` uses `activeScatter = self.plot.getScatter()` which returns the last scatter added to the plot. This is the scatter used for displaying the mask, not the real scatter data.

**Comment by PiRK** [comment]
We cannot use `_setActiveItem(...)` because we don't want the scatter data to be all black (selection color).

**Comment by PiRK** [comment]
Actually the scatter does not change color when it is selected, so the solution was simple (https://github.com/silx-kit/silx/pull/716/commits/22760fac91e7994f8ec99ba5933e84ba3381d42a)

The PR is ready for review.

There is still an issue of lack of public API to get/set the active scatter, but this can be discussed and implemented in a separate PR, because it is also a problem for histograms.

**Comment by vallsv** [comment]
Tested with pyFAI-drawmask without any problem.

**Pull request merged**
