### PR TITLE
PlotWidget: Added sigBackendChanged

### LINKED ISSUE #3883: Create a sigBackendChanged to the PlotWidget
When the backend is updated, the widget handle is not the same.

In some case i have to register this widget to capture some qt events.

It would be useful to provide a signal in this case.

Related to #3876

### PR DESCRIPTION
**Pull request by vallsv**
Added `sigBackendChanged` to `PlotWidget`

Related to #3876 

Closes #3883

Changelog: 
- Added `sigBackendChanged` to `PlotWidget`

### CODE REVIEW

**Comment by vallsv** [comment]
I was thinking of added `current, previous` params to the signal.

Usually if you don't do that, the user of the API have to store the backend reference on its side. So i think it could be done without much problem.

**Review by t20100 — APPROVED** [review]
LGTM

The `OpenGLAction` can be improved with this

**Comment by vallsv** [comment]
That's a good idea i have updated the stuff.

**Comment by t20100** [comment]
> I was thinking of added current, previous params to the signal.

If it's needed, why not.
It's not Qt-like but some other signals of `PlotWidget` already provides current, previous params.

But this means you'll give back a `previous` backend that is no longer used by a `PlotWidget`, not sure what it's useful for, and risky if used.

**Comment by t20100** [comment]
> aboutToConnect/aboutToDisconnect, but i feel like it's overkill.

I agree.

`sigBackendChanged` can also only provide the current backend, that more Qt-like and does cause trouble with giving access to a disconnected backend.

It's fine as it for me.

**Pull request merged**
