### PR TITLE
Misc.: Fixed `run_test.py --qt-binding` option

### PR DESCRIPTION
**Pull request by t20100**
This PR makes sure the chosen Qt binding is loaded by importing it as early as possible, else this can cause issues if multipe Qt bindings are available.

### CODE REVIEW

**Comment by t20100** [comment]
completes PR #3486

Related to #3432

**Comment by t20100** [comment]
Issue with CI on macos with matplotlib v3.5.0b1 (see #3524), pin-pointing matplotlib on macos for now.

**Comment by t20100** [comment]
-  Fixed `run_tests.py` on Windows
- Switch CI tests: PyQt5 on macos and PySide2 on Linux (There are still issues to solve with PySide2 on macos:  #3524)
- Updated tests and some code with circular reference to make tests pass with PySide2.

**Comment by vallsv** [comment]
Are you sure about `_set_qt_binding` inside `pytest_addoption`?

`pytest_addoption` is supposed to be called to register available option, not to setup them, right?

**Comment by t20100** [comment]
Yes, maybe using `pytest_configure` is indeed best.
Anyway the need is to import the Qt binding before the tests look-up, else PyQt5 will be imported during test look-up.

**Comment by vallsv** [comment]
Let me know if you want to change it, else ill merge it as it is.

**Comment by t20100** [comment]
Yes I test it and if it does the job I update the PR, else I let you know.

**Comment by t20100** [comment]
`_set_qt_binding` is already called from `pytest_configure` ;)

**Comment by vallsv** [comment]
Looks good. Sorry.

**Pull request merged**
