### PR TITLE
[examples] tomographyReconstruction.py display fix

### LINKED ISSUE #1254: [examples] tomographyReconstruction.py does not show the images
The problem appears under windows, PyQt5, python 3.6

### PR DESCRIPTION
**Pull request by vasole**
Call qt.qApp.processEvents prior to ask for command line input. closes #1254

### CODE REVIEW

**Comment by vasole** [comment]
@PiRK @t20100 

Can it make it to the release?

**Comment by PiRK** [comment]
No problem. It is a small bugfix in a piece of sample code. I'll cherry-pick it into v0.6.

**Comment by t20100** [comment]
Why not showing both plot and call `app.exec_` ?

**Comment by vasole** [comment]
I took a minimalist approach...

**Pull request merged**
