### PR TITLE
Mask out regions for various operation: histograms, colormap selection and profile ... 

### LINKED ISSUE #3124: Combining mask and histogram in widgets/silx view
I had a request for it.
Do we want to allow to combine the histogram plot action with the mask tool, from widgets? and from `silx view`?

Below is a sample code that works for images by overriding `PixelIntensitiesHistoAction.computeIntensityDistribution` to add :
```
        source = self.getSelectionMaskSource()
        if source is not None:
            mask = source.getSelectionMask()
            if mask is not None:
                array = numpy.array(array, dtype=numpy.float64, copy=True)
                array[mask != 0] = numpy.nan  # Replace masked values with NaN
```

Sample code:
```
import numpy

import fabio

from silx.gui import qt
from silx.gui.plot import Plot2D, items
from silx.math.combo import min_max
from silx.math import Histogramnd
from silx.gui.plot.actions import histogram as histogram_action


class HistoMaskAction(histogram_action.PixelIntensitiesHistoAction):
    """Histogram action with support for a mask to compute the histogram"""

    def __init__(self, *args, **kwargs):
        self.__selectionMaskSource = None
        super().__init__(*args, **kwargs)

    def setSelectionMaskSource(self, source):
        """Set the source of the selection mask.

        :param source:
            QObject with sigMaskChanged signal and getSelectionMask method.
        """
        if self.__selectionMaskSource is not None:
            self.__selectionMaskSource.sigMaskChanged.disconnect(
                self.computeIntensityDistribution)
        self.__selectionMaskSource = source
        if self.__selectionMaskSource is not None:
            self.__selectionMaskSource.sigMaskChanged.connect(
                self.computeIntensityDistribution)

    def getSelectionMaskSource(self):
        """Returns the source of selection mask.

        :rtype: QObject with sigMaskChanged signal and getSelectionMask method.
        """
        return self.__selectionMaskSource

    def computeIntensityDistribution(self):
        """Get the active image and compute the image intensity distribution
        """
        item = self._getSelectedItem()

        if item is None:
            self._cleanUp()
            return

        if isinstance(item, items.ImageBase):
            array = item.getData(copy=False)
            if array.ndim == 3:  # RGB(A) images
                _logger.info('Converting current image from RGB(A) to grayscale\
                    in order to compute the intensity distribution')
                array = (array[:, :, 0] * 0.299 +
                         array[:, :, 1] * 0.587 +
                         array[:, :, 2] * 0.114)
        elif isinstance(item, items.Scatter):
            array = item.getValueData(copy=False)
        else:
            assert(False)

        if array.size == 0:
            self._cleanUp()
            return

        source = self.getSelectionMaskSource()
        if source is not None:
            mask = source.getSelectionMask()
            if mask is not None:
                array = numpy.array(array, dtype=numpy.float64, copy=True)
                array[mask != 0] = numpy.nan  # Replace masked values with NaN

        xmin, xmax = min_max(array, min_positive=False, finite=True)
        nbins = min(1024, int(numpy.sqrt(array.size)))
        data_range = xmin, xmax

        # bad hack: get 256 bins in the case we have a B&W
        if numpy.issubdtype(array.dtype, numpy.integer):
            if nbins > xmax - xmin:
                nbins = xmax - xmin

        nbins = max(2, nbins)

        data = array.ravel().astype(numpy.float32)
        histogram = Histogramnd(data, n_bins=nbins, histo_range=data_range)
        assert len(histogram.edges) == 1
        self._histo = histogram.histo
        edges = histogram.edges[0]
        plot = self.getHistogramPlotWidget()
        plot.addHistogram(histogram=self._histo,
                          edges=edges,
                          legend='pixel intensity',
                          fill=True,
                          color='#66aad7')
        plot.resetZoom()


class Plot(Plot2D):
    """Image plot widget with histogram taking the mask into account."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__histoMaskAction = HistoMaskAction(self, parent=self)
        self.__histoMaskAction.setSelectionMaskSource(self.getMaskToolsDockWidget())
        self.toolBar().addAction(self.__histoMaskAction)


if __name__ == "__main__":
    import sys

    app = qt.QApplication([])

    img = fabio.open(sys.argv[1])
    w = Plot()
    w.addImage(img.data)
    w.show()

    app.exec_()
```

### LINKED ISSUE #3263: Combining mask and profile in widgets/silx view
Allowing to use current mask to compute profile.

Similar to #3124 but for profile.

Regarding how to connect mask tool to profile, any better idea than what I proposed in #3124, i.e., using:
```
def setSelectionMaskSource(self, source):
        """Set the source of the selection mask.

        :param source:
            QObject with sigMaskChanged signal and getSelectionMask method.
        """
```

An alternative I see is to attach the mask to the image at the item level, that might be more generic since it does not rely on the mask tool.

### LINKED ISSUE #3285: Profile drawing and masked regions ...
After discussion with Thomas, we agree this is a wished feature. Nevertheless taking into account the mask should be wired down at the array level and not connecting at the mask widget as it is proposed in #3281. This will simplify also the calculation of the range of the colormap with masked data (especially important with Eiger2 detectors are the dummy value is above 4 billions, 2^32-1)

This approach will require much more work at lower levels but will allow the generalization to all kind of processing very easily.

Here is a TODO list:

- [ ] Provide the associated mask in the image object like: image.getData() one could have image.getMask()
- [x] Profile calculation are performed in Cython. It is the right time to refactor the code to take mask into account
- [ ] Wire the mask in the ProfileToolBar.

The mask should be an array of same size as the image with dtype uint8 (or None if absent)
The alternative, numpy.maskedarray, has been discarded because we which to be able to manage multiple masks, either 7 overlapping masks or 254 non overlapping masks.

Sponsor: ID17

### PR DESCRIPTION
**Pull request by kif**
Changelog: Associate a mask to the plotting of the image

- [X] Histogram
- [x] Colormap
- [x] Profile

closes #3263
closes #3124
closes #3285

### CODE REVIEW

**Comment by kif** [comment]
close #3263

**Comment by kif** [comment]
Sorry, the message was for Valentin ... @vallsv

**Comment by t20100** [comment]
@kif, I'll have a look at this.

**Comment by t20100** [comment]
I'm reworking this PR (extending support to complex images, making sure it works when image size changes,...).
I'll make another PR based on this one because of issues with rebase.

**Comment by t20100** [comment]
I'm closing this PR, it is continued in PR #3369

**Pull request closed without merging**
