### PR TITLE
[ImageStack] Add ImageStack.py file

### PR DESCRIPTION
**Pull request by payno**
Screenshot from 2020-01-15 16-24-07

### CODE REVIEW

**Comment by t20100** [comment]
I made a PR on your branch with a few small things: renaming `getPlot` to `getPlotWidget` and avoiding to hide the whole plot while waiting.

A first few comments on the API: 
- Instead of using inheritance and override `getUrlLoader` to change the `UrlLoader`, you can provide a `setUrlLoader` method. BTW, is this tuning needed for now?
- I'd keep `getPreviousUrl`, `getNextUrl`, `getNNextUrls` and `getNPreviousUrls` private and add a `getUrls` returning the tuple of URLs and a `getCurrentUrlIndex` methods.
- Adding `getNPrefetch` would complete the `setNPrefetch`.
- Don't you need a signal to know when the current URL changes?

**Comment by t20100** [comment]
Also I'm wondering whether it would better or not to put the list of URLs in a `QDockWidget`. That would be inline with the other `PlotWidget` tools (e.g., mask).

**Comment by payno** [comment]
>     * Instead of using inheritance and override `getUrlLoader` to change the `UrlLoader`, you can provide a `setUrlLoader` method. BTW, is this tuning needed for now?
> 

Yes, the idea is to replace some code in tomwer where we have some different file format like .vol from pyhst... and we need to have a different loader.

>     * Don't you need a signal to know when the current URL changes?

Yes I should provide this information :smiley:

**Comment by payno** [comment]
I think I should adapt the url loader to allow him the possibility to load several url.
Will be usefull for speed up, avoiding some file opening / closing and avoiding massive number of threads in some cases

**Comment by payno** [comment]
> I think I should adapt the url loader to allow him the possibility to load several url.
> Will be usefull for speed up, avoiding some file opening / closing and avoiding massive number of threads in some cases

could be done internally but this is not the first goal of it. Might be done later because will bring some complexity in it and might be really 'application' specific.

**Comment by payno** [comment]
> Also I'm wondering whether it would better or not to put the list of URLs in a `QDockWidget`. That would be inline with the other `PlotWidget` tools (e.g., mask).

Good question.
- It is True that it is not convenient at all to different 'sources' for the Dock Widget and it can be confusing for the users.
- In the ImageStack widget I also think the UrlList is really a 'core' feature that is meant to be the center of the intereaction with users. So it has from my point of view a different status than others possible DockWidgets...

**Pull request merged**
