### PR TITLE
[io] is_specfile PY3 bug when reading binary data

### PR DESCRIPTION
**Pull request by PiRK**
This solves the immediate issue (#1416).
 
But the current test to find whether a file is a specfile is not very well suited for investigating large binary files.
The issue is that we assume the data is text, and we loop `for line in f:` to test for a `#f` or `#s` in the first 10 lines. This means that we might end up reading an entire data file to find out that it is not a Specfile, if there are not at least 10 `\n` characters in the file.

### CODE REVIEW

**Comment by PiRK** [comment]
There is no perfect solution. I don't think that we can guarantee that the first  character (after stripping whitespaces) will always be a #. I also don't think we can assume that a specfile must only contain ascii characters, if we want to support files generated by third party scripts.

**Comment by vasole** [comment]
There should not be any stripping of white spaces at the beginning of the lines. We support specfile and not something resembling it.

Concerning the problem. What about an fread of a maximum of 2500 bytes maximum and apply the 10 lines rule to it? For instance, one should only have to look for "\n#F" ot "\n#S" in that maximum of 2500 bytes.

**Comment by vallsv** [comment]
It sounds reasonable

**Comment by PiRK** [comment]
Done.

**Pull request merged**
