### PR TITLE
Fix FFT norm (pyfftw & numpy)

### PR DESCRIPTION
**Pull request by leonroussel**
## Fixing problem on normalization of FFT

Usual normalization is on backward FFT ( ./1 on forward & ./N on backward) but we can expect to have a non-normalize FFT (with parameter normalize="none"), this option is not implemented correctly

### Solution & modifications :

- numpy : `norm="backward"` on FFT & `norm="forward"` on IFFT
- pyfftw : `normalise_idft=True` on FFT & `normalise_idft=False` on IFFT

(There is also a problem with pyfftw implementation, it does not have the expected behavior with the last version (0.13), https://github.com/pyFFTW/pyFFTW/issues/341
but the solution normally bypass this problem)

### TODO

- [x] ~~requirements for numpy version ? >= 1.12 ? or different in setup.py ? (if >= 1.10, a case could be avoided in npfft.py)~~
- [x]  normalization "by hand" if numpy version do not allow normalization="none" ? or keep a warning ?
- [x] need to be tested with both version of pyfftw 0.12 & 0.13
- [x] ~~more efficient solution than np_version in ["1.8", ...]~~

Changelog: FFT: fix normalization modes, notably account for regression in pyfftw normalization

### CODE REVIEW

**Comment by leonroussel** [comment]
Failure on old numpy implem ?

================================== FAILURES ===================================
______________________________ TestNumpyFFT.test ______________________________
self = <silx.math.fft.test.test_fft.TestNumpyFFT testMethod=test>
    def test(self):
        """Test the numpy backend against native fft.
    
        Results should be exactly the same.
        """
        for trdim in self.transform_infos.dimensions:
            for mode in self.transform_infos.modes:
                for size in self.transform_infos.sizes[trdim]:
                    with self.subTest(trdim=trdim, mode=mode, size=size):
>                       self.__test(trdim, mode, size)
venv_test\lib\site-packages\silx\math\fft\test\test_fft.py:267: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
venv_test\lib\site-packages\silx\math\fft\test\test_fft.py:282: in __test
    res = F.fft(input_data)
venv_test\lib\site-packages\silx\math\fft\npfft.py:129: in fft
    return self.numpy_funcs[0](array, **self.numpy_args_fft)
<__array_function__ internals>:6: in rfft
    ???
venv_test\lib\site-packages\numpy\fft\_pocketfft.py:367: in rfft
    if norm is not None and _unitary(norm):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
norm = 'backward'
    def _unitary(norm):
        if norm is None:
            return False
        if norm=="ortho":
            return True
        raise ValueError("Invalid norm value %s, should be None or \"ortho\"."
>                        % norm)
E       ValueError: Invalid norm value backward, should be None or "ortho".
venv_test\lib\site-packages\numpy\fft\_pocketfft.py:88: ValueError
============================== warnings summary ===============================
gui/plot/test/testPlotWidget.py::TestPlotAxes::testAxisExtent

**Comment by leonroussel** [comment]
- requirements for numpy version ? >= 1.12 ? or different in setup.py ? (if >= 1.10, a case could be avoided in npfft.py)
- normalization "by hand" if numpy version do not allow normalization="none" ? or keep a warning ?

**Comment by leonroussel** [comment]
Still CI failures :
================================== FAILURES ===================================
_____________________ TestMaskToolsWidget.testWithAnImage _____________________
...

**Comment by pierrepaleo** [comment]
Thanks! 

From what I see in `requirements.txt` and `pyproject.toml`, the minimum required numpy version is `1.12`, not `1.8`. 

To simplify version comparison a little bit, you can use `from pkg_resources import parse_version`, eg. `parse_version("1.10.2") > parse_version("1.8.0")`.

The latest CI failures seem related to GUI (happens from time to time)

**Comment by pierrepaleo** [comment]
Test fails for `numpy == 1.19.5`. Seems to be because [not all normalization were available for this version](https://numpy.org/doc/stable/release/1.20.0-notes.html#norm-backward-forward-keyword-options-for-numpy-fft-functions). 

Just tested on my machine:
  - `test_norms` fails with `numpy==1.19.5`
  - `test_norms` passes with `numpy==1.20.0`

**Comment by pierrepaleo** [comment]
Tested with pyfftw 0.12 and 0.13.

**Pull request merged**
