### PR TITLE
[SpecFile] Tutorial, bugfix, multiple MCA headers

### LINKED ISSUE #286: [specfile] Multiple MCAs header information handling
`silx.io.SpecFile` currently cannot handle the case of multiple MCA devices in a single scan when each device has its own header block. 
Currently, the decoding of `#@CHANN` assumes there are 4 values in that header. (https://github.com/silx-kit/silx/blob/4a9a1cd7004c58254dd6b53b34b5f665cb28dd68/silx/io/specfile/specfile.pyx#L196)

In case of multiple headers, we actually have several blocks of 4 values to parse:
```
In [15]: sc3.mca_header_dict
Out[15]: 
{u'CALIB': u'1 2 3\n3.4 5.6 7.8\n3.5 2.1 0.6',
 u'CHANN': u'20 0 19 1\n20 0 19 1\n20 0 19 1',
 u'CTIME': u'123.4 234.5 345.6\n56.4 23.4 234.5\n13.4 34.5 34.6',
 u'MCA': u'%16C\n%16C\n%16C',
 u'MCADEV': u'1\n2\n3'}

```

### PR DESCRIPTION
**Pull request by PiRK**
This PR is an addition to #259, and minor improvements in handling exotic MCA cases:

- Make the SPEC file example clearer in the tutorial
- Add a script example (CLI for SpecFile -> HDF5 conversion) 
- Handle multiple MCA devices in the case each device has its own MCA header
- Bugfix: Raise a KeyError when a user explicitly tries to access a MCA group that does not exist

The code example could be the basis for a `silx spectoh5` command.

Closes #286

### CODE REVIEW

**Comment by PiRK** [comment]
We can now access scans by index in `SpecH5` objects as well:
```
In [1]: from silx.io.spech5 import SpecH5

In [2]: sfh5 = SpecH5("oleg.dat")

In [3]: sfh5.keys()
Out[3]: [u'94.1', u'95.1', u'96.1']

In [4]: sfh5[0]
Out[4]: <SpecH5Group "/94.1" (4 members)>

In [5]: sfh5[0] == sfh5["/94.1"]
Out[5]: True

In [7]: sfh5[1] 
Out[7]: <SpecH5Group "/95.1" (4 members)>

In [9]: sfh5[2]
Out[9]: <SpecH5Group "/96.1" (4 members)>

In [10]: sfh5[3]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-10-99ab9b51227b> in <module>()
----> 1 sfh5[3]
...
IndexError: Scan not found error ( SpecFile )
```

**Comment by vasole** [comment]
I am not sure about "To work with text data (``title``, ``start_time``, headers...), you should convert the
datasets into strings."

We have to check how h5py presents those things when the datasets have been generated under Python 2 and they are read under Python 3.

**Comment by PiRK** [comment]
I'm fixing this by refactoring SpecH5Dataset, so that strings will be `numpy.string_` objects rather than `()`-shape numpy array of `dtype=numpy.string_` (and similar solution for scalars, int or float).

This will make scalar datasets (`shape==()`) much easier to work with.

**Comment by vasole** [comment]
Great job!

**Pull request merged**
