### PR TITLE
Improves scatter irregular grid visualization

### LINKED ISSUE #2828: [scatter] Fix irregular rendering for the last line

### PR DESCRIPTION
**Pull request by t20100**
This PR improves the rendering of the scatter plot irregular grid visualization by no longer clipping the data to a grid, falling back to points for a single data point, and handling data as a single row/column.

closes  #2828

### CODE REVIEW

**Comment by t20100** [comment]
Ready for review (and merge if CI is happy with it).

It should now fully supports incomplete grids.

**Comment by vallsv** [comment]
At start i receive this exception
```
  File "/home/ordinateur/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/backends/BackendBase.py", line 343, in postRedisplay
    plot.replot()
  File "/home/ordinateur/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/PlotWidget.py", line 2787, in replot
    item._update(self._backend)
  File "/home/ordinateur/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/items/core.py", line 336, in _update
    self._backendRenderer = self._addBackendRenderer(backend)
  File "/home/ordinateur/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/items/scatter.py", line 633, in _addBackendRenderer
    points[1:nbpoints] - points[:nbpoints-1], (0., 0., 1.))[:, :2]
ValueError: could not broadcast input array from shape (3,2) into shape (17,2)
```

**Comment by vallsv** [comment]
```
WARNING:bliss.flint.widgets.scatter_plot:[-0.75 -0.6  -0.45] [-0.75 
-0.75 -0.75] [7.14440149 9.98673139 0.75862823]                                                                
WARNING:bliss.flint.widgets.scatter_plot:hint (<VisualizationParamet
er.GRID_SHAPE: 'grid_shape'>, (11, 11))                                                                        
WARNING:bliss.flint.widgets.scatter_plot:hint (<VisualizationParamet
er.GRID_BOUNDS: 'grid_bounds'>, ((-0.75, -0.75), (0.75, 0.75)))                                                
WARNING:bliss.flint.widgets.scatter_plot:hint (<VisualizationParamet
er.GRID_MAJOR_ORDER: 'grid_major_order'>, 'row')                                                               


WARNING:bliss.flint.widgets.scatter_plot:[-0.75 -0.6  -0.45] [-0.75 
-0.75 -0.75] [7.14440149 9.98673139 0.75862823]                                                                
WARNING:bliss.flint.widgets.scatter_plot:hint (<VisualizationParamet
er.GRID_SHAPE: 'grid_shape'>, (11, 11))                                                                        
WARNING:bliss.flint.widgets.scatter_plot:hint (<VisualizationParamet
er.GRID_BOUNDS: 'grid_bounds'>, ((-0.75, -0.75), (0.75, 0.75)))                                                
WARNING:bliss.flint.widgets.scatter_plot:hint (<VisualizationParamet
er.GRID_MAJOR_ORDER: 'grid_major_order'>, 'row')                                                               


WARNING:bliss.flint.widgets.scatter_plot:[-0.75 -0.6  -0.45] [-0.75 
-0.75 -0.75] [7.14440149 9.98673139 0.75862823]                                                                
WARNING:bliss.flint.widgets.scatter_plot:hint (<VisualizationParamet
er.GRID_SHAPE: 'grid_shape'>, (11, 11))                                                                        
WARNING:bliss.flint.widgets.scatter_plot:hint (<VisualizationParamet
er.GRID_BOUNDS: 'grid_bounds'>, ((-0.75, -0.75), (0.75, 0.75)))                                                
WARNING:bliss.flint.widgets.scatter_plot:hint (<VisualizationParame$
er.GRID_MAJOR_ORDER: 'grid_major_order'>, 'row')                                                               
CRITICAL:root:Uncaught exception

```

**Comment by t20100** [comment]
I fixed an issue when the grid shape is provided, let me know if this fixes your issue.

BTW, for the first line to be displayed with provided grid shape, the grid_major_order must be correctly provided.

**Comment by vallsv** [comment]
Looks perferct

**Pull request merged**
