### PR TITLE
3713 bitshuffle decompression

### PR DESCRIPTION
**Pull request by kif**
There is apparently a need to perform compression and decompression on the GPU, two advantages for this:
* prevents the transfer of uncompressed data, since most of the time the tranfer to the GPU over PCIe is the limiting factor
* alleviate the slow power9 processor when it comes to bitshuffling (this is due to the small vectorial data-types)

Changelog: Implement bitshuffle-LZ4 decompression in OpenCL

### CODE REVIEW

**Comment by kif** [comment]
close #3713

**Comment by kif** [comment]
For now, the code is not complete, the last bits are not properly decompressed / shuffled properly.

**Comment by pierrepaleo** [comment]
Nice! I'm reviewing it. For macos we might force `wg=1`.

**Comment by kif** [comment]
Apparently, there is a bug line 476 of the kernel where there is an invalid read and write ...
```
Index (346112) exceeds static array size (8592)
	Kernel: bslz4_decompress_block
	Entity: Global(2243584,0,0) Local(0,0,0) Group(2191,0,0)
	  store i8 %20, i8 addrspace(3)* %arrayidx22, align 1, !dbg !106
	At line 476 (column 26) of input.cl:
	  (source not available)
	

Invalid read of size 1 at global memory address 0x1b000000237423
	Kernel: bslz4_decompress_block
	Entity: Global(2243584,0,0) Local(0,0,0) Group(2191,0,0)
	  %20 = load i8, i8 addrspace(1)* %arrayidx20, align 1, !dbg !102
	At line 476 (column 28) of input.cl:
	  (source not available)
	

Invalid write of size 1 at local memory address 0x2000000054c00
	Kernel: bslz4_decompress_block
	Entity: Global(2243584,0,0) Local(0,0,0) Group(2191,0,0)
	  store i8 %20, i8 addrspace(3)* %arrayidx22, align 1, !dbg !106
	At line 476 (column 26) of input.cl:
	  (source not available)
```

**Comment by kif** [comment]
Validated on Nvidia, Power9, AMD GPU and Intel CPU.
TODO: validate on intel-gpu (Beignet)

**Comment by pierrepaleo** [comment]
Looks good.

**Pull request merged**
