### PR TITLE
OpenCL FFT

### PR DESCRIPTION
**Pull request by pierrepaleo**
This PR aims at providing an OpenCL FFT interface using gpyfft.

### CODE REVIEW

**Comment by pierrepaleo** [comment]
I am struggling with a "double free" issue when the FFT class instance is deleted. 
It is certainly due to gpyfft dealloc method, although further investigations have to be done.

**Comment by payno** [comment]
close ##939

**Comment by kif** [comment]
I am trying to set up some test to validate the code vs numpy ...

**Comment by kif** [comment]
Life goes on in #2180

**Pull request closed without merging**
