### PR TITLE
Remove cythonized files

### PR DESCRIPTION
**Pull request by vallsv**
This PR remove all the cythonized files from the Git repository.

The configuration of the continuous integration files was updated to include cython as dependency.

The `setup.py`'s targets `sdist` and `clean` was updated.

- `python setup.py clean` will now also remove cythonized files
- `python setup.py sdist` will react as we expect for the project: regenerate all the cython files without OpenMP to provided them as source to pypi.

### CODE REVIEW

**Comment by kif** [comment]
does sdist generate the C-files ?

**Comment by vallsv** [comment]
No, but i can try.

I think i will try something like: `python setup.py sdist --cythonized`, instead of only `sdist`.

**Comment by vallsv** [comment]
BTW there is a pbm with the qhull compilation here.

**Comment by t20100** [comment]
I think we should add cython to `setup_requires` in the `setup.py`... eventually except for `sdist` if the C files are embedded...

**Comment by t20100** [comment]
I'm checking for QHull, looks like an issue with different version of cython.

**Comment by t20100** [comment]
PR #1776 is fixing the qhull issue...

**Comment by kif** [comment]
looks great to me.

**Pull request merged**
