### PR TITLE
Setup.py modifications to make the code Cython3 compatble

### PR DESCRIPTION
**Pull request by kif**
There are issues within the qhull code which is not cython3-ready.

### CODE REVIEW

**Comment by kif** [comment]
Sorry, my eclipse is rather picky about blank lines.

**Comment by kif** [comment]
We are still using the old_build_ext from cython, the new one provides parallel builds. Is it a good idea to have it or will it break compatibility with elder version of cython ?

**Comment by kif** [comment]
close #3027

**Comment by vallsv** [comment]
AFAIR the default cython builder was not providing enough flexibility for flags, like openmp. But that's a long time ago.

**Comment by vallsv** [comment]
I think it should be merged as it is cause it fixes the CI.

But it would be good to check next that openmp is still working. And clean up our custom code if it not needed anymore.

**Comment by t20100** [comment]
qhull code is already fixed upstream in scipy... to me we should get rid of our copy and disable the features based on it if scipy is not available.

**Pull request merged**
