### PR TITLE
Scatter regular grid visualization parameters

### PR DESCRIPTION
**Pull request by t20100**
This PR allows to provide parameters for the regular grid visualization, that when provided replace the guessing.
Those parameters are:
- `GRID_ORDER`: 'C' or 'F' as in numpy for row- or column- major order
- `GRID_BOUNDS`: ((x, y) of first point, (x, y) of last point)
- `GRID_SIZE`: (width, height) number of grid cells in each dimension

`GRID_BOUNDS` and `GRID_SIZE` can be wider than the current number of points, so one can provide the final values of those and only update the data (e.g., for live monitoring...)

Still to do: Use `GRID_BOUNDS` as the bounds of the item when provided?

related to #2743

### CODE REVIEW

**Comment by t20100** [comment]
Answer to: Use GRID_BOUNDS as the bounds of the item when provided?

No, use data bounds, so ready for review.

**Comment by vallsv** [comment]
Its fine for me. But just a comment about the params:

- `GRID_ORDER`, if it is about the fast axes, i think it could be a little more understandable to use the name of this axes. You named it X and Y. -> `FAST_AXES = 'X'`. or if you expect complex things at one point `GRID_ORDER = "FAST_X" or "XY"`...
- I will receive metadata per axes, in case it is convinient for you, an API per axes fit better `AXES_X = begin,end,nbpoint`, `AXES_Y = begin,end,nbpoint`. But it is up to you.
- What if i have nbpoints for one and not for the other? Just to say that it will happen.

**Comment by vasole** [comment]
@vallsv 

To have the nb of points (or intervals) is not enough. A mesh scan can be incomplete. Therefore one has to figure out the dimensions of the expected regular grid based on the available points. The nice side of the approach is that is the users asks for a regular mesh without relying on any additional data.

**Comment by t20100** [comment]
@vasole, the idea of this PR was to provide some information about the grid structure in case on has it so as to avoid guessing it. If it is not provided, then the grid is guessed.

@vallsv, having `begin,end,nbpoint` for each axis might be a good, I didn't consider the fact of having info for only one axis (in fact, the info from the fast axis only is really needed).
As for the `GRID_ORDER` naming, I reused that of numpy. Calling it fast axis is somewhat specific to scans, I could use `row_major` and `column_major` which is the generic concept underneath.

**Pull request merged**
