### PR TITLE
Rework previous profile

### LINKED ISSUE #2955: [plot] Improve profile architecture
Flint integrate profile from silx.

From user feedback, some feature could be implemented, and could also benefit to silx.

But it would be good improve the current implementation first:

After a talk to @t20100 here few comments:

- The scatter profile and the image profile do not use the same architecture
    - Scatter profile uses ROIs (not the image profile)
    - It would be good to use ROIs for both
        - The limitation here is the weight of the line (it does not exist right now for ROIs)
- The main object for both is a toolbar
   - It is a strong limitation on the reusability
   - It would be better to create a dedicated manager as the main object

### PR DESCRIPTION
**Pull request by vallsv**
PR #2988 and #3008 have to be merged before

Closes #2955, #2865, #2046, #1947, #84, #2046, #3001

This PR rework the previous profile mechanism with the new one.

Then with this PR, Plot1D, Plot2D, StackView, ScatterView, ImageView... uses the the new profile based on ROIs.

- Ceate a toolbar helper
- Rework the 1D 2D scatter toolbars 
- Merge the ROI actions together
- Rewrite the tests

The old toolbar classes are still there. It should not be used by external application, but in case there is a backward compatibility for most of the previous API.

If you use attributes or methods from the previous profile toolbars, this PR can break your code.

### CODE REVIEW

**Comment by vallsv** [comment]
This PR can be used to see the result on the default plots.

**Comment by vallsv** [comment]
The free line is not working well anymore, i suspect the `setSingleShot` mode to break the interaction. I have to investigate.

**Comment by t20100** [comment]
I have to small issues:
- The profile window is very small vertically when first shown.
- The horizontal or vertical scatter profile "grid" tool, if I create the profile line, release the mouse button and then drag it outside the scatter data, I can no longer move it. It does not occur if I create it and drag it without release the mouse button.

**Comment by vallsv** [comment]
- I dont understand the small height size, it should use the legacy code here, but also noticed it
- For the grid it was the problem with the update of the marker when the style is updated. Now it should be fixed

**Comment by vallsv** [comment]
I have fixed the profile window size, add it supports back a custom profile window. I have added a unittest about that.

So the PR is fine.

**Comment by vallsv** [comment]
I can reproduce it here. So easier to fix.

**Comment by vallsv** [comment]
The problem is solved.

In fact an unexpected profile window was on top of the plot, so the second subtest was not able to create the ROI with the mouse.
- small screen so no space on side for the profile window
- now the profile window is bigger (it was incorrectly small before)
- now the profile window is a dialog (so it stay on top of the main window)

Tricky.

**Pull request merged**
