### PR TITLE
Create BoundingRect item

### PR DESCRIPTION
**Pull request by vallsv**
This PR introduce a `BoundingRect` item.

It is a kind of shape, which is not displayed but considered as part of the data.

This can be used to custom the expected visible region of the plot.

### CODE REVIEW

**Comment by t20100** [comment]
Looks like there are a few things missing for the signal and clearing data bounds cache.
I'll make a PR on your branch for it.

**Comment by t20100** [comment]
I made a PR on your branch with the handling of updates to refresh the data bounds whenever visibility, y axis or bounds are changed.
We can discuss it.
The whole data bounds refresh needs to be done in a better way (e.g., inheriting from a `DataItem`) but that is not for this PR.

**Comment by t20100** [comment]
BTW, did you check how it behaves when the rectangle is partly negative and axes are log scale?

Also probably worth making sure the mins are below the maxs...

**Comment by vallsv** [comment]
Here is an update to:
- Check argument validity
- Have an expected behaviour with log scale axes

**Pull request merged**
