### PR TITLE
FFT: avoid creating opencl/cuda contexts when not needed

### PR DESCRIPTION
**Pull request by pierrepaleo**
(see #3439 discussion)

This PR fixes opencl/cuda contexts being created unnecessarily.

Changelog: FFT: avoid creating opencl/cuda contexts when not needed

### CODE REVIEW

**Comment by kif** [comment]
LGTM

**Review by t20100 — APPROVED** [review]
LGTM, can we merge it?

**Comment by pierrepaleo** [comment]
Yes, thanks

**Comment by t20100** [comment]
could you rebase so CI works better?

**Comment by pierrepaleo** [comment]
Sorry missed the last answer. The PR was rebased on latest master.

**Pull request merged**
