### PR TITLE
Add .desktop file and silx icon for silx viewer

### PR DESCRIPTION
**Pull request by t20100**
This PR adds a .desktop file for Linux desktop menu integration and an icon (Related to #1038).

### CODE REVIEW

**Comment by t20100** [comment]
I've checked the files by manually copying them to ~/.local/share/applications/ and ~/.local/share/icons/

**Comment by picca** [comment]
Hello,

look at here :)

https://stackoverflow.com/questions/25284879/install-desktop-file-with-setup-py

**Comment by vallsv** [comment]
BTW i think it would be better to move the `desktop` directory inside our `package` directory. And they recommend to follow the reverse DNS convention for the file name, then something like `org.silx.SilxViewer.desktop`. What do you think?

**Comment by picca** [comment]
obey the policy ;)

**Comment by t20100** [comment]
Moved and renamed.
I will not do the installation of .desktop from the setup.py, the solution proposed in https://stackoverflow.com/questions/25284879/install-desktop-file-with-setup-py does not seem to work with `--user` (It should work if you install the package with pip as root but it is pointless...).
Instead I'm updating our unofficial debian packaging.

**Comment by t20100** [comment]
installation OK on debian8: ready for review.

**Comment by t20100** [comment]
closes #1038

**Comment by vallsv** [comment]
As we have `org.silx` for the app, what about doing the same for the icon? I am always afraid of name collision.

**Comment by t20100** [comment]
There seems to have no icon (at least in Debian gnome icons package) using reverse DNS naming...

**Comment by vallsv** [comment]
Then it's fine for me.

**Comment by vallsv** [comment]
LGTM,
No luck, people ony use rnice without desktop :-)

**Pull request merged**
