### PR TITLE
[plot] Replace usage of PlotWidget's _getAllMarkers and _getItems by getItems

### PR DESCRIPTION
**Pull request by t20100**
This PR replace the use of `PlotWidget._getAllMarkers` and `PlotWidget._getItems` by `PlotWidget.getItems` and deprecates the former private methods.

Following PR #2904, this reduces the amount of methods used and moves towards using the item-based API internally.

### CODE REVIEW

**Comment by t20100** [comment]
Added removing `_itemKey` (replaced by `_itemKind` and `Item.getName`) + avoid to directly use `PlotWidget._content`, use `PlotWidget.getItems` instead.

**Comment by t20100** [comment]
Fixed conflict.

**Comment by vallsv** [comment]
LGTM, hairy PR.

**Comment by t20100** [comment]
;) thanks for the review!

**Pull request merged**
