### PR TITLE
[OpenCL] Expose the workgroup size min, max and memory usage

### PR DESCRIPTION
**Pull request by kif**
This allows ahead of time work-group optimization

Changelog: Expose function to probe kernel and optimize work repartitions

### CODE REVIEW

**Comment by kif** [comment]
close #3303

**Comment by kif** [comment]
I will need this feature in pyFAI 0.20 ...

**Comment by t20100** [comment]
Is it for 0.14? Then it should be merged into branch 0.14 directly.

**Comment by pierrepaleo** [comment]
Not sure `test_query()` will always pass smoothly, I see that some information like `PREFERRED_WORK_GROUP_SIZE_MULTIPLE` are either available in OpenCL 3 and/or `pyopencl >= 2020.3`. But perhaps the pyopencl documentation is incorrect and it will work... I'll test on several machines.

**Comment by pierrepaleo** [comment]
I have the following error with an Intel Xeon W-2133 CPU (pyopencl 2019.1.1, Intel OpenCL ICD):

```
======================================================================
FAIL: test_query (silx.opencl.test.test_addition.TestAddition)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/silx/build/lib.linux-x86_64-3.7/silx/opencl/test/test_addition.py", line 137, in test_query
    self.assertEqual(3, len(query_kernel_info(program=self.program, kernel="addition", what="COMPILE_WORK_GROUP_SIZE")), "3D kernel")
AssertionError: 3 != 0 : 3D kernel

----------------------------------------------------------------------
```

it seems that `COMPILE_WORK_GROUP_SIZE` often gives weird values on CPU, for example I can get `[0, 0, 0]`

**Pull request merged**
