### PR TITLE
[plot] Add PlotScatter widget

### LINKED ISSUE #1672: [test] Move sx tests in sx submodule

### LINKED ISSUE #1706: [plot] Add a PlotScatter widget to the widget zoo
We provide `Plot1D` for curves, `Plot2D` for images but there is no plot widget providing the tools for scatter plots like getting data value (see #1705), a scatter plot profile (see #1613) and the already available scatter mask.

### PR DESCRIPTION
**Pull request by t20100**
This PR adds a `ScatterView` widget with tools dedicated to scatter plots. closes #1706
For now it provides actions for : axes log scale, grid, colormap, aspect ratio and scatter mask.
It does not inherit from `PlotWindow`.

It fixes a bug in scatter mask polygon tool and makes `ColorBarWidget` work with active scatter.

It adds a `sx.scatter` function based on `ScatterView` widget.

TODOs:
- [x] Add `ScatterView` and `sx.scatter` to the doc
- [x] Add position info to display, x, y, value  (see #1705)
- [x] Add a way to select marker and set symbol size

Scatter profile will not be part of this PR (see #1613)

### CODE REVIEW

**Comment by t20100** [comment]
Added:
- Renamed `PlotScatter` to `ScatterView`
- Corresponding documentation
- A bug fix in matplotlib backend concerning marker size (which needs tobe squared with matplotlib `scatter` function to be consistent with other primitives marker size)
- A position info toolbar providing data value and index. (working but still WIP)

**Comment by t20100** [comment]
Ready for review.

**Comment by PiRK** [comment]
I fixed 4 conflicts. I hope I did not break your branch.

**Comment by vasole** [comment]
line 136 in test_sx.py

The title does not seem to match what is required.

**Comment by t20100** [comment]
`ScatterView` API (and proxy methods) slightly reworked, ready to review/merge.

**Pull request merged**
