### PR TITLE
use Python3 for all developer tools

### PR DESCRIPTION
**Pull request by kif**
Changelog: Switch to Python3 for all development tools.

### CODE REVIEW

**Review by t20100 — APPROVED** [review]
LGTM

**Comment by t20100** [comment]
@vasole I'm adding you to the reviewers since you initiated the discussion around this.

**Comment by vasole** [comment]
My take on this is that the proper way of doing thing is ``#!/usr/bin/env python`` and that writing python3 is a linux distribution bound thing.

Apparently I am not the only one thinking that way

https://bugs.python.org/issue28686

**Comment by vallsv** [comment]
`python` target isnt supposed to be already python 3?

**Comment by vasole** [comment]
Conda is doing things properly, and when you activate a environment, python refers to the python of that environment even if python3 or python2 are available.

For instance, under windows python3 does not exist. It is just python.

**Comment by vasole** [comment]
@vallsv 

Apparently not all the unix distributions have caught up. With conda it is the case.

**Comment by kif** [comment]
then setup.py should be reverted as well ...

**Comment by vallsv** [comment]
It should not change much things anyway, no?

I mostly never use this scripts without prefixing them with the python i want to use.

**Comment by t20100** [comment]
virtualenv behaves the same as conda.
For me, since I use virtualenvs for dev, this PR will not change anything.

It's for the "dev" scripts so it should not change much.

BTW both ubunut20.04 and debian11 seems to consider python as python2.

**Comment by vasole** [comment]
To me the change is not needed and it is a question of time to have debian and ubuntu considering python as whatever python is first in the path.

I am -1 on this one but I am just one of many.

**Comment by kif** [comment]
Ubuntu has a package: https://packages.ubuntu.com/focal/python-is-python3
but this does not exist under debian11

**Comment by mretegan** [comment]
On the cluster, the python command doesn't point to any version of Python.

```
retegan@slurm-nice-access201:~> type -a python
python not found
retegan@slurm-nice-access201:~> type -a python3
python3 is /usr/bin/python3
python3 is /bin/python3
```

**Comment by vasole** [comment]
@mretegan 

Since the cluster is ubuntu, then it is perfect to ask installation of the package @kif mentioned above:

https://packages.ubuntu.com/focal/python-is-python3

**Comment by mretegan** [comment]
@vasole I was just trying to point out that not having the python command might be the default case for many Linux installations. Defaulting to python3 seems like the safer choice, at lest for Linux. Hi

**Comment by vasole** [comment]
My point is that it is the safest choice for ubuntu/debian.

Anyone using a virtual env, conda or windows is better served with python (that sooner or later will default to the python 3 version).

In any case I gave my vote. The others can vote too and that's it.

**Comment by kif** [comment]
> Anyone using a virtual env, conda or windows is better served with python (that sooner or later will default to the python 3 version).

venv & conda are working fine with python3. For windows, I have limited experience.

Moreover those are dev' only scripts.

**Comment by t20100** [comment]
I also gave my vote by accepting this PR and @kif by proposing it.
Unless more people disagree on this, I'll merge this PR.

**Pull request merged**
