### PR TITLE
FitAction: Added support of auto update of fitted data and x range

### LINKED ISSUE #2953: [fit] The fit dialog do not take care of the current available curves
The fit action only take care of the curve at the time the dialog was open.

But the dialog can stay open, the user can select something else, the curves can be replaced by something else (open another dataset), the dialog still compute estimation and fit on the very first curve selected.

### PR DESCRIPTION
**Pull request by t20100**
This PR provides a refactoring and extension of the plot `FitAction` in order to add:
- A mode where fitted data is updated when the active curve changes (`FitAction.set|isFittedItemUpdatedFromActiveCurve(bool)`).
- A mode where fitted range is updated when the X limits of the plot changes (`FitAction.set|isXRangeUpdatedOnZoom`).

The default is consistent with the previous behavior (i.e., no update).

What this PR does NOT change:
- The `FitWidget` is never modal
- The `FitWidget` is never reset
- The way the displayed result in the plot is managed
- Exception when estimate/fit goes wrong 

closes #2953

### CODE REVIEW

**Comment by vallsv** [comment]
I just ask myself if we could use a silx version bigger than the alpha/beta we have already released.
I could help me a lot to test on external projects.

**Comment by vallsv** [comment]
I create a PR on top of your branch. Just static check. I still have to test. Merge it if you like.

It looks like there was much more work than what i expect! Thanks a lot.

**Comment by t20100** [comment]
I merged your PR, it is good for me.

**Comment by vallsv** [comment]
image

This fit looks weard. I am afraid there is a problem with the x-range

**Comment by vallsv** [comment]
```
Error on estimate: Traceback (most recent call last):
  File "/home/ordinateur/Software/miniconda3/envs/blissenv2/lib/python3.7/site-packages/silx/gui/fit/FitWidget.py", line 504, in estimate
    self.fitmanager.estimate(callback=self.fitStatus)
  File "/home/ordinateur/Software/miniconda3/envs/blissenv2/lib/python3.7/site-packages/silx/math/fit/fitmanager.py", line 423, in estimate
    fun_params, fun_constraints = self.estimate_fun(xwork, ywork)
  File "/home/ordinateur/Software/miniconda3/envs/blissenv2/lib/python3.7/site-packages/silx/math/fit/fitmanager.py", line 970, in estimate_fun
    return estimatefunction(x, y)
  File "/home/ordinateur/Software/miniconda3/envs/blissenv2/lib/python3.7/site-packages/silx/math/fit/fittheories.py", line 407, in estimate_height_position_fwhm
    numpy.float)
  File "/home/ordinateur/Software/miniconda3/envs/blissenv2/lib/python3.7/site-packages/numpy/core/numeric.py", line 207, in ones
    a = empty(shape, dtype, order)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
```
There is maybe a regression here?

**Comment by t20100** [comment]
- Fixed issue with sync with active curve enabled and sync of xrange disabled
- Also improved the error message you mentioned by fixing array creation/allocation when there is no peak, issue raised no is Singular matrix.

**Comment by vallsv** [comment]
LGTM

**Pull request merged**
