### PR TITLE
Add missing SVG icons

### LINKED ISSUE #157: [Gui] Use SVG for icons
Use SVG instead of PNG for icons to better support high resolution displays

### PR DESCRIPTION
**Pull request by t20100**
This PR adds SVG files for all icons.

Closes #157 

Still missing plot-window.svg and plot-window-image.svg.

### CODE REVIEW

**Comment by vallsv** [comment]
It would be good to remove the useless entities from the SVG files. Else it is fine.
I do not merge cause it is flagged in progress, but there not problem to merge.

**Comment by vallsv** [comment]
It would be nice to update the printer and the save icon.

**Comment by t20100** [comment]
All icons are now available as svg, plus I 'optimized' svg files using scour: https://github.com/scour-project/scour

**Comment by vallsv** [comment]
Fine :-)

**Pull request merged**
