### PR TITLE
[plot] Roi Items

### PR DESCRIPTION
**Pull request by dnaudet**
DO NOT MERGE.
Provided as a base for discussion. Sill a WIP.

Rois :
- rectangles
- polygons

Workflow :
1) user : select shape, draw
2) user : draw shape
3) drawing finished : "editing" mode started automaticaly
4) user : move the anchors around
5) ? (right click? send to a roi table view? ...)
6) party!

(circle, arc and wedge implemented but not included in the merge because somewhat "hacky")

### CODE REVIEW

**Comment by dnaudet** [comment]
Got to add bounds checking.

**Comment by vallsv** [comment]
Hi,

Just a comment about 
```
roiShapes = ('rectangle', 'polygon',)
roiIcons = ('shape-rectangle', 'shape-polygon',)
roiClasses = (RectRoiItem, PolygonRoiItem,)
```
I think it would be better to write it like
```
roiShapes = {}
roiShapes["rectangle"] = ('shape-rectangle', RectRoiItem)
roiShapes["polygon"] = ('shape-polygon', PolygonRoiItem)
or like that
roiShapes.append(("polygon", "shape-polygon", PolygonRoiItem)
```
That's up to you anyway.

Another thing, maybe you can take a look at PyQtGraph signals:
- http://www.pyqtgraph.org/documentation/graphicsItems/roi.html
- sigRegion... for example i think it can be useful to have event between begin and end of the change

**Comment by vasole** [comment]
@vallsv @t20100 

What is the status of this PR? A lot of things have changed since September 2016.

**Comment by t20100** [comment]
We need the feature of this PR, but its implementation is outdated since we introduced the plot object oriented API which is more appropriate for this feature and other things.

We can close it for now and create a new PR when we have time to work on it. (I saved this PR in my repo).

**Comment by t20100** [comment]
Closing for now, think about it for API when doing ROI with object oriented plot API.

**Pull request closed without merging**
