### PR TITLE
Improve launcher

### PR DESCRIPTION
**Pull request by vallsv**
* `pip install` uses setuptools to generate launchers (with entry-points description from `setup.py`)
* Debian 7 uses setuptools to generate launchers (it is done by stdeb) (it will use `/usr/bin/python2`, we dont have packages for python3 on debian7)
* Debian 8 package using executable scripts generated by setuptools. The script uses `/usr/bin/python3`
* Introduce Debian 9 packaging (It is done by `./build-deb8.sh` (checking the debian version used))
* Debian 9 package using executable scripts generated by setuptools. The script uses `/usr/bin/python3`
* `/scripts` was removed
* `bootstrap.py` imports `setup.py` to be able to know available executable names. It can now execute generically any scripts and entry_points defined in the project configuration (`setup.py`).

```
# execute silx
./bootstrap.py silx  # it executes the entry-point silx defined in setup.py
```

Todo:
- [x] Merge Debian 9 packaging from @kif
- [x] Update bootstrap to be able to launch the project as `-m`
- [ ] Test Debian 7/8/9 installations

After merging:
- [ ] Fix nightly build have to be checked.
- [ ] Fix our release documentation

### CODE REVIEW

**Comment by kif** [comment]
Looks good to me

**Comment by kif** [comment]
let's see if the nightly build works again

**Comment by vallsv** [comment]
Here is few changes on the release documentations:

- Location of debian packages have changed
- You dont have anymore to cancel (ctrl-c) installation of the packages when you build it (if you really want to install it at the same time, you can use ``--install``)


https://gitlab.esrf.fr/silx/project/commit/55397c32a39ae8d352feb4a03d4656f9c3df5b79

**Comment by vallsv** [comment]
Nightly build is now working. `help2man` was not installed.

**Pull request merged**
