### PR TITLE
Improve mask tool

### PR DESCRIPTION
**Pull request by vallsv**
- Change behaviour of aspect ratio and y-axis origin icons
- Display mask shape using the mask color
- Display shape for the pencil tool before drawing anything
- Update mask icon

### CODE REVIEW

**Comment by vallsv** [comment]
Ready to be merged.

The preview of the mask is part of another PR: https://github.com/silx-kit/silx/pull/332

**Comment by mretegan** [comment]
It seems that following this, the aspect ratio and y-axis origin icons are always present in the PlotWindow toolbar regardless of the value set by the user at instantiation.

**Comment by vallsv** [comment]
Intresting. It would be good to fix it before the release.

**Comment by t20100** [comment]
Opened issue #344 for this

**Pull request merged**
