### PR TITLE
Custom NXdata selector

### LINKED ISSUE #1783: [silx view] Add a tool to expand all the tree
Requested by Holger Witsch.

### LINKED ISSUE #1785: [hdf5tree] Allow to drag any node of the tree
2 use cases

- Be able to DnD a dataset to a filter on the application
- Be able to DnD a link to external software (in this case, the shared DnD object could contain our silx URL

### LINKED ISSUE #1819: [hdf5tableview] Exception with virtual NXdata

### PR DESCRIPTION
**Pull request by vallsv**
## Current state

Here is some help to test the current state.

The tree behaviour have changed. You have to double-click on datasets to display them. It's the same for custom NXdata. If a custom NXdata is displayed, it will be updated if you edit signals or axes.

custom nxdata 2

## Todo

- [ ] It would be good to allow the copy or move (CTRL) of datasets when using DnD
- [ ] It would be good to merge Hdf5NodeMimeData and Hdf5DatasetMimeData
- [ ] (optional) allow to edit the title
- [x] Items when remove/add axes have to be fixed to avoid to change the selection
- [x] Add show on context menu
- [x] Add more features on the context menu of the NXdata selector
- [x] Hashed drop zone
- [x] Title header on the displayed data
- [x] Allow to drop a dataset as a new custom NXdata
- [x] Allow to drag and drop axis
- [x] Display shape/types/dim
- [x] Display icons/group
- [x] Gen custom NXdata names using prefix
- [x] Take care of memory release when closing a file
- [x] Take care of dataset copy (use links if possible)
- [x] Take care of virtual dataset update
- [x] Allow to add an axes
- [x] Allow to remove axes
- [x] Allow to create and remove new virtual NXdata
- [x] Rework silx view interaction (double click to display the content, single click only for selection)
- [x] Better integration of the custom NXdata widget
- [x] Allow to display/hide the custom NXdata widget using the menu

Closes #1785
Closes #1819
Closes #1783

### CODE REVIEW

**Comment by vallsv** [comment]
Fine enough to be reviewed. There still small things to fix, but mostly everything is done.

**Comment by PiRK** [comment]
A small comment: the first time I used it, it took a few seconds for me to guess that I had to drag and drop the axis inside the individual cell in the dataset column. Would it be difficult or problematic to allow dropping the dataset anywhere  on the table line?

**Comment by vallsv** [comment]
I don't know. I will try but the way it is done do not provide the full control on it i think.

**Comment by t20100** [comment]
A minor comment: "NXData" as the name of the selection in the tree is probably not meaningful for the user.

**Comment by vallsv** [comment]
Yes, but this custom NXdata widget is designed using low level concepts of NXdata. Then it's difficult to find other words without reworking everything.

**Comment by vallsv** [comment]
I still have to add documentation and tests. But it would be nice to merge it before (at least before tests).

**Comment by vallsv** [comment]
Added a small patch, plus documentation. It's ready for review.
I will add unittest with another PR.

**Pull request merged**
