### PR TITLE
Drop support for h5py<2.10

### PR DESCRIPTION
**Pull request by woutdenolf**

### CODE REVIEW

**Comment by t20100** [comment]
By dropping h5py<2.10 we also drop debian10 (h5py 2.8)...

If having h5py<2.8 doesn't change anything, maybe it is better? Else debian10 will stay with v0.13 max or a backport of h5py (which is fine for me).

**Comment by woutdenolf** [comment]
In that case I think it is better to still support 2.7

**Comment by t20100** [comment]
Maybe not, debian10 comes with h5py v2.8 and matplotlib v3.0.2... so currently released version of silx is compatible.

**Comment by woutdenolf** [comment]
Hmmm weird, I have not problems with h5py 2.7 on my Ubuntu 20.04 machine.

**Comment by woutdenolf** [comment]
This is no longer needed. See #3252

**Pull request closed without merging**
