### PR TITLE
Rework setup.py for cython and openmp

### PR DESCRIPTION
**Pull request by vallsv**
- The `Build` class allow to catch options from the build command
- The `BuildExt` class take care of the cytonization and filter flags for OpenMP
- No more global
- No more command-line parsing and hack of sys.args
- No more process outside the setup() function
- Command-line argument have the priority on env variables
- Env variables are parsed (0/1/true/false... else are ignored)

```
python setup.py build --no-cython --no-openmp

python setup.py build --force-cython --openmp

export FORCE_CYTHON=yes
export WITH_CYTHON=True
export WITH_OPENMP=1
python setup.py build

export FORCE_CYTHON=no
export WITH_CYTHON=False
export WITH_OPENMP=0
python setup.py build
```
Limitation: Build options must be after `build` argument.

### CODE REVIEW

**Comment by vallsv** [comment]
Let me know if this version is acceptable for you

**Comment by vasole** [comment]
Just a question (I am lazy to look at the code).

Are the options 0, False, no equivalent and the options 1, True, yes equivalent when dealing with the environment variables? It would be very cumbersome to have to remember that for WITH_CYTHON one has to use True/False and for WITH_OPENMP 1/0

**Comment by vasole** [comment]
In the code we test for false and true. Should the capitalized forms False and True be added? I say it just because it is what it have been naturally used in the opening post.

Following @vallsv decision, the PR can be approved as it is or with the added cases.

**Comment by vallsv** [comment]
@vasole The env variable content is converted to lower case before the test. And `true` is same as `1` or `yes`. If the env variable contains an unexpected value, a warning is displayed and the variable is ignored. I think that's the safer way for env variable.
```
+        value = content.lower()
+        if value in ["1", "true", "yes", "y"]:
+            return True
+        if value in ["0", "false", "no", "n"]:
+            return False
```

**Pull request merged**
