### PR TITLE
[ImageView] Fix support of dict/object Colormap

### LINKED ISSUE #1185: Initial aspect ratio and colormaps for ImageView?
Hi,

Maybe this is documented but I can't find an answer.

I have a class inherited from `ImageView`. I'd like to keep the data aspect ratio and have a logarithmic color map from start, without having to click the buttons every time. How do I do this?

Here's the code,
https://github.com/alexbjorling/nanomax-analysis-utils/blob/master/apps/limaLiveViewer.py

### PR DESCRIPTION
**Pull request by t20100**
This PR update ImageView to support both dict and Colormap in setColormap method.
It also updates ImageView documentation and add a test file for ImageView that was missing.

Closes #1185

### CODE REVIEW

**Comment by t20100** [comment]
Also closes #1187

**Comment by payno** [comment]
LGTM

**Comment by t20100** [comment]
`ImageView` tests fail on macOS, python2.7 with matplotlib 2.1.0rc1(`QWidget::repaint: Recursive repaint detected`) but pass with matplotlib 2.0.2

**Comment by t20100** [comment]
Rebased to only merge bug fixes in the PR.
Corresponding automated tests will be in another PR.

**Pull request merged**
