### PR TITLE
Add gamma correction normalization for Colormap

### PR DESCRIPTION
**Pull request by t20100**
This PR adds a gamma correction normalization to the available colormap normalizations.

It refactors `silx.math.colormap` and `silx.gui.colors` to allow normalization with a parameter (here gamma).
It adds support for gamma normalization in the plot, `ColorBar`, `ColormapDialog` and in `plot3d`.
For OpenGL (both for `plot` and `plot3d`), the gamma correction is implemented in OpenGL.

TODOs:

- [x] Make autoscale mean+/-3std work with gamma correction.
- [x] Add control of the gamma parameter to `plot3d` parameter tree.

### CODE REVIEW

**Comment by t20100** [comment]
Ready for review.

This PR:
- Refactors `silx.math.colormap` to add some `Normalization` objects so as to handle normalizations with parameters such as gamma correction.
- Reworks `silx.gui.colors` to reuse `silx.math.colormap` normalizations
- Adds `Colormap.get|setGammaNormalizationParameter` methods to set the gamma correction parameter.
- Adds support of gamma correction in shaders in `plot` and `plot3d`.
- Reworks `ColormapDialog`, `ColorBar` and `plot3d`'s parameter tree to support gamma correction.

**Comment by t20100** [comment]
Thanks @vallsv for the fixes!

**Comment by t20100** [comment]
- Added a base class for normalization using initial data for autoscale mean+/-3std
- Added support of gamma in `plot3d` group property widget.

Ready for review if CI is happy.

**Comment by vallsv** [comment]
LGTM

**Pull request merged**
