### PR TITLE
Add backport of python3.4 enum package in third_party

### LINKED ISSUE #838: copyright file not up-to-date for embedded matplotlib colormaps

### PR DESCRIPTION
**Pull request by t20100**
The `enum` package will be used by PR #726.

### CODE REVIEW

**Comment by vallsv** [comment]
Hi. Just a little typo, you should remove "update copyright for colormaps closes #838" from this PR.

**Comment by t20100** [comment]
I don't like to put too much things in a single PR to ease the review, but I also find it a bit overkill to do a PR for changing a single line... that's why I bundled it here.

**Comment by vallsv** [comment]
Oh ok. But the title can be confusing. BTW i see no problem to create a lot of PR. Especially here, maybe people want to talk about the first commit, but we can merge the second one without waiting tests.

**Comment by t20100** [comment]
As you want, done.

**Comment by vallsv** [comment]
Looks fine

**Pull request merged**
