### PR TITLE
[gui] Colormap object

### PR DESCRIPTION
**Pull request by payno**
PR relative to #146 

- [x] Move existing Colormap object from plot3d to plot
- [x] Add missing functionalities to the object + signal
- [x] Integrate the object in existing code
- [x] check back widgets using colormap
- [x] Update doc

### CODE REVIEW

**Comment by payno** [comment]
Some question reminder : 
    should the function converting the colormap to a dict should be called getDict or toDict ?

**Comment by dnaudet** [comment]
or asDict ;)

**Comment by t20100** [comment]
I'd avoid `getDict` to keep `get*` for 'attributes' of the class.

**Comment by vallsv** [comment]
`_getDict`?

**Comment by payno** [comment]
I think I will go for toDict

**Comment by payno** [comment]
Q: 
- now that the Color is integrated in the plot is it still interesting to conserve the examples/colorbar ?

**Comment by payno** [comment]
the management of the colrmap by the colorbar will be part of an other PR ( #913 ), this should prevend not regression, the next one should fix remainging issues of #889

**Comment by payno** [comment]
From my point of view the class Colormap in plot3D/scene/function.py should inherit from the general Colormap and the should probably be changed to. What do you think @t20100

**Comment by t20100** [comment]
Indeed, examples/colorbar.py is now pointless.
What would be interesting is to have an example of making a widget inherited from PlotWidget by adding actions, colorbar and tools (see #916).

**Comment by vallsv** [comment]
The ColorBar widget is a widget which can be used without any dependency. Then an example showing the features is still useful.

**Comment by t20100** [comment]
I'd prefer to keep `plot3d.scene` separated from `plot.Colormap` because the whole scene API was made using Python properties rather than get/set and it does not directly depend on Qt (so no QObject in there), but the top-level `plot3d` widget API should use it.

**Comment by t20100** [comment]
@vallsv, agreed if it does not use `Plot2D` (which is what this PR provides).

**Comment by vallsv** [comment]
Few comments:

```
from silx.gui.plot import Colormap as genColormap
```
- It would be good to remove the `as`. Just use Colormap.

```
_DEFAULT_COLORMAPS = {
    'gray': 0,
    'reversed gray': 1,
    'red': 2,
    'green': 3,
    'blue': 4,
    'temperature': 5
}
```
- It would be good to add a little comment about why this things have numbers.

```
NORMS = 'linear', 'log'
"""Tuple of supported normalizations."""

NORMALIZATIONS = ('linear', 'log')
"""Tuple of managed normalizations"""
```
- There is a duplication code. It would be good to use only one of this.
- I would prefer to have enum, but i am maybe the only one
- It would be nice to have const for LOGARITHM  and LINEAR
- If we want to expose the Colormap object as gui or plot module, which can be convenient, it would be nice to expose constants as static attributes from the object it-self.

Most of getter function does not have summary docstring. But i dont check the rendering of the doc anyway. I would prefer
```
Return the upper bounds of the colormap is exists, else None
:rtype: float, None
```
than
```
:return: the upper bounds of the colormap or None
```

**Comment by vallsv** [comment]
You should implement `__eq__` instead of `compare`, and also `__hash__` can be very useful.

**Pull request merged**
