### PR TITLE
Feature matplotlib init

### PR DESCRIPTION
**Pull request by vallsv**
Cherry-picked from https://github.com/silx-kit/silx/pull/369
- 389bb0b
- 4ad741c
- 744c196

Plus typo

### CODE REVIEW

**Comment by t20100** [comment]
Looks good to me ;)
Anyone else willing to do the review?

**Comment by vallsv** [comment]
BTW isn't there a problem with PySide+Qt5?

**Comment by t20100** [comment]
PySide is for Qt4.
There is a PySide2 project for Qt5 support: http://wiki.qt.io/PySide2

**Comment by vallsv** [comment]
Oh, then it is fine. Thanks a lot for the feed back.
It would be very nice if they call it PySide4... :-D

**Comment by vasole** [comment]
Are you sure you want to import matplotlib systematically when importing plot? At a certain point we should be able to choose a different backend.

**Pull request merged**
