### PR TITLE
Fix 773

### PR DESCRIPTION
**Pull request by payno**

### CODE REVIEW

**Comment by vasole** [comment]
- Please check the names are medfilt (not medianfilt), medfilt1d and medfilt2d.
- The situation is much worse than before. Running your benchmark on my machine:

medianfilter780

**Comment by payno** [comment]
Is your compiler dealing with openMP ?
Because I test it on an other computer and tendency is the same ?

**Comment by payno** [comment]
Implementation using queue didn't seems to be a good idea. I move back to vector with fix size.
Seems to make a difference on @vasole computer.

**Comment by vasole** [comment]
Yeah, with your modifications now silx is twice faster than scipy or pymca.

**Pull request merged**
