### PR TITLE
[test] Create test app

### PR DESCRIPTION
**Pull request by vallsv**
- Create `silx test` app
    - Reuse only few command lines from run_tests
    - CTRL-C cancel tests but display the current result
    - Skipped tests are displayed like other output ERROR/FAILED
    - Reduce logs by using unittest buffer
        - By default nothing is displayed (but `.EFs`) all informations of fails and errors will be displayed at the end (with associated log and stdout)
       - `-v` displays for each tests the name then log and stdout
       - `-vv` displays for each tests the name then log (with debug level) and stdout

```
> silx test --help
usage: silx test [-h] [-v] [-x] [-g] [-o] [-l] [--qt-binding QT_BINDING]
                 [test_name [test_name ...]]

Launch unittests of the library

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         Increase verbosity. Option -v prints additional INFO
                        messages. Use -vv for full verbosity, including debug
                        messages and test help strings.
  -x, --no-gui          Disable the test of the graphical use interface
  -g, --no-opengl       Disable tests using OpenGL
  -o, --no-opencl       Disable the test of the OpenCL part
  -l, --low-mem         Disable test with large memory consumption (>100Mbyte
  --qt-binding QT_BINDING
                        Force using a Qt binding, from 'PyQt4', 'PyQt5', or
                        'PySide'
```

```
> silx test
Start Xvfb
feature module is not available to compare results with C++ implementation. Matching cannot be tested.
OpenGL-based widget disabled:
OpenGL not available
...................................................................................................................
...................................................................................................................
..............s...................................................................................................
.....................................s............................................................................
...................................................................................................................
...................................................................................................................
...................................................................................................................
...................................................................................................................
......................................................
----------------------------------------------------------------------
Ran 972 tests in 90.097s

OK (skipped=2)
Skipped silx.gui.data.test.test_dataviewer.TestDataView.testCubeWithComplex (): OpenGL widget not yet tested
Skipped silx.io.test.test_specfile.TestSFLocale.test_locale_de_DE (): de_DE.utf8 locale not installed
Test suite succeeded
python: Fatal IO error 11 (Resource temporarily unavailable) on X server :1974.
```
As you can see Xvfb crashes at the end. `$? == 1`. But i think it is not a big problem here.

```
> silx test -v
QTest.qWaitForWindowExposed not available,using QTest.qWaitForWindowShown instead.
feature module is not available to compare results with C++ implementation. Matching cannot be tested.
Xlib:  extension "RANDR" missing on display ":2066".
No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
Unable to load registered array format handler numeric:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/numeric.py", line 15, in <module>
    raise ImportError( """No Numeric module present: %s"""%(err))
ImportError: No Numeric module present: No module named Numeric

Unable to load registered array format handler vbo:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/vbo.py", line 33, in <module>
    from OpenGL import GL
ImportError: cannot import name GL

Unable to load registered array format handler vbooffset:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/vbo.py", line 33, in <module>
    from OpenGL import GL
ImportError: cannot import name GL

Xlib:  extension "GLX" missing on display ":2066".
Xlib:  extension "GLX" missing on display ":2066".
OpenGL-based widget disabled:
OpenGL not available
Using QLabel
test_imshow (silx.test.test_sx.SXTest)
Test imshow function ... Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 0: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
ok
test_plot (silx.test.test_sx.SXTest)
Test plot function ... Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
ok
testQObject (silx.gui.test.test_qt.TestQtWrapper)
Test that QObject is there. ... ok
testLoadUi (silx.gui.test.test_qt.TestLoadUi)
Create a QMainWindow from an ui file ... ok
testNiceNumbers (silx.gui.plot._utils.test.test_ticklayout.TestTickLayout)
Minimalistic tests of :func:`niceNumbers` ... ok
testNiceNumbersLog (silx.gui.plot._utils.test.test_ticklayout.TestTickLayout)
Minimalistic tests of :func:`niceNumbersForLog10` ... ok
testNoColormap (silx.gui.plot.test.testColorBar.TestColorScale)
Test _ColorScale without a colormap ... ok
testRelativePositionLinear (silx.gui.plot.test.testColorBar.TestColorScale) ... ok
testRelativePositionLog (silx.gui.plot.test.testColorBar.TestColorScale) ... ok
testLinearNormNoAutoscale (silx.gui.plot.test.testColorBar.TestNoAutoscale) ... Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
ok
testLogNormNoAutoscale (silx.gui.plot.test.testColorBar.TestNoAutoscale) ... Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
ok
testColormapWithoutRange (silx.gui.plot.test.testColorBar.TestColorBarWidget)
Test with a colormap with vmin==vmax ... Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
ok
testEmptyColorBar (silx.gui.plot.test.testColorBar.TestColorBarWidget) ... Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
ok
testNegativeColormaps (silx.gui.plot.test.testColorBar.TestColorBarWidget)
test the behavior of the ColorBarWidget in the case of negative ... Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 0: changing bounds.
Log colormap with bound <= 0: changing bounds.
Log colormap with negative bounds, changing bounds to positive ones.
ok
testPlotAssocation (silx.gui.plot.test.testColorBar.TestColorBarWidget)
Make sure the ColorBarWidget is properly connected to the plot ... Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
ok
testRGBA (silx.gui.plot.test.testColors.TestRGBA)
"Test rgba function with accepted values ... ok
testApplyColormapToData (silx.gui.plot.test.testColors.TestApplyColormapToData)
Simple test of applyColormapToData function ... ok
ColormapDialog (silx.gui.plot)
Doctest: silx.gui.plot.ColormapDialog ... /usr/lib/python2.7/dist-packages/matplotlib/collections.py:571: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):
ok
testCalculation (silx.gui.plot.test.testCurvesROIWidget.TestCurvesROIWidget) ... Log colormap with bound <= 1: changing bounds.
ok
testEmptyPlot (silx.gui.plot.test.testCurvesROIWidget.TestCurvesROIWidget)
Empty plot, display ROI widget ... Log colormap with bound <= 1: changing bounds.
ok
testWithCurves (silx.gui.plot.test.testCurvesROIWidget.TestCurvesROIWidget)
Plot with curves: test all ROI widget buttons ... Log colormap with bound <= 1: changing bounds.
ok
testGetAlpha (silx.gui.plot.test.testAlphaSlider.TestActiveImageAlphaSlider) ... ok
testGetImage (silx.gui.plot.test.testAlphaSlider.TestActiveImageAlphaSlider) ... ok
testWidgetEnabled (silx.gui.plot.test.testAlphaSlider.TestActiveImageAlphaSlider) ... ok
testGetAlpha (silx.gui.plot.test.testAlphaSlider.TestNamedImageAlphaSlider) ... ok
testGetImage (silx.gui.plot.test.testAlphaSlider.TestNamedImageAlphaSlider) ... ok
testWidgetEnabled (silx.gui.plot.test.testAlphaSlider.TestNamedImageAlphaSlider) ... ok
testGetAlpha (silx.gui.plot.test.testAlphaSlider.TestNamedScatterAlphaSlider) ... /usr/lib/python2.7/dist-packages/matplotlib/collections.py:631: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors_original != str('face'):
ok
testGetScatter (silx.gui.plot.test.testAlphaSlider.TestNamedScatterAlphaSlider) ... ok
testWidgetEnabled (silx.gui.plot.test.testAlphaSlider.TestNamedScatterAlphaSlider) ... ok
testClickOrDrag (silx.gui.plot.test.testInteraction.TestInteraction)
Minimalistic test for click or drag state machine. ... ok
testLegendSelector (silx.gui.plot.test.testLegendSelector.TestLegendSelector)
Test copied from __main__ of LegendSelector in PyMca ... ok
testDialog (silx.gui.plot.test.testLegendSelector.TestRenameCurveDialog)
Create dialog, change name and press OK ... ok
testEmptyPlot (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget)
Empty plot, display MaskToolsDockWidget, toggle multiple masks ... Log colormap with bound <= 1: changing bounds.
ok
testLoadSaveFit2D (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) ... Log colormap with bound <= 1: changing bounds.
ok
testLoadSaveNpy (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) ... Log colormap with bound <= 1: changing bounds.
ok
testSigMaskChangedEmitted (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) ... Log colormap with bound <= 1: changing bounds.
ok
testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget)
Plot with an image: test MaskToolsWidget interactions ... Log colormap with bound <= 1: changing bounds.
ok
testEmptyPlot (silx.gui.plot.test.testScatterMaskToolsWidget.TestScatterMaskToolsWidget)
Empty plot, display MaskToolsDockWidget, toggle multiple masks ... Log colormap with bound <= 1: changing bounds.
ok
testLoadSaveCsv (silx.gui.plot.test.testScatterMaskToolsWidget.TestScatterMaskToolsWidget) ... Log colormap with bound <= 1: changing bounds.
ok
testLoadSaveNpy (silx.gui.plot.test.testScatterMaskToolsWidget.TestScatterMaskToolsWidget) ... Log colormap with bound <= 1: changing bounds.
ok
testSigMaskChangedEmitted (silx.gui.plot.test.testScatterMaskToolsWidget.TestScatterMaskToolsWidget) ... Log colormap with bound <= 1: changing bounds.
ok
testWithAScatter (silx.gui.plot.test.testScatterMaskToolsWidget.TestScatterMaskToolsWidget)
Plot with a Scatter: test MaskToolsWidget interactions ... Log colormap with bound <= 1: changing bounds.
ok
test (silx.gui.plot.test.testPlotInteraction.TestSelectPolygon)
Test draw polygons + events ... ok
testAddNoRemove (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlot)
add objects to the Plot ... PlotWidget backend does not support widget
ok
testPlotTitleLabels (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlot)
Create a Plot and set the labels ... PlotWidget backend does not support widget
ok
testDataRangeCurveImage (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlotRanges)
right+left+image axis range ... PlotWidget backend does not support widget
ok
testDataRangeHiddenCurve (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlotRanges)
curves with a hidden curve ... PlotWidget backend does not support widget
ok
testDataRangeImage (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlotRanges)
image data range ... PlotWidget backend does not support widget
ok
testDataRangeImageNegativeScaleX (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlotRanges)
image data range, negative scale ... PlotWidget backend does not support widget
ok
testDataRangeImageNegativeScaleY (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlotRanges)
image data range, negative scale ... PlotWidget backend does not support widget
ok
testDataRangeLeft (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlotRanges)
left axis range ... PlotWidget backend does not support widget
ok
testDataRangeLeftRight (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlotRanges)
right+left axis range ... PlotWidget backend does not support widget
ok
testDataRangeNoPlot (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlotRanges)
empty plot data range ... PlotWidget backend does not support widget
ok
testDataRangeRight (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlotRanges)
right axis range ... PlotWidget backend does not support widget
ok
testGetAllImages (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlotGetCurveImage)
PlotWidget.getAllImages test ... PlotWidget backend does not support widget
ok
testGetCurve (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlotGetCurveImage)
PlotWidget.getCurve and Plot.getActiveCurve tests ... PlotWidget backend does not support widget
ok
testGetCurveOldApi (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlotGetCurveImage)
old API PlotWidget.getCurve and Plot.getActiveCurve tests ... PlotWidget backend does not support widget
ok
testGetImage (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlotGetCurveImage)
PlotWidget.getImage and PlotWidget.getActiveImage tests ... PlotWidget backend does not support widget
ok
testGetImageOldApi (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlotGetCurveImage)
PlotWidget.getImage and PlotWidget.getActiveImage old API tests ... PlotWidget backend does not support widget
ok
testEdges (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlotHistogram) ... ok
testHistogramCurve (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlotHistogram) ... ok
testAddGetScatter (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlotAddScatter) ... PlotWidget backend does not support widget
ok
testGetAllScatters (silx.gui.plot.test.testPlotWidgetNoBackend.TestPlotAddScatter)
PlotWidget.getAllImages test ... PlotWidget backend does not support widget
ok
testCustomConverters (silx.gui.plot.test.testPlotTools.TestPositionInfo)
Test PositionInfo with custom converters ... Log colormap with bound <= 1: changing bounds.
ok
testDefaultConverters (silx.gui.plot.test.testPlotTools.TestPositionInfo)
Test PositionInfo with default converters ... Log colormap with bound <= 1: changing bounds.
ok
testFailingConverters (silx.gui.plot.test.testPlotTools.TestPositionInfo)
Test PositionInfo with failing custom converters ... Log colormap with bound <= 1: changing bounds.
ok
testImageFormatInput (silx.gui.plot.test.testPlotTools.TestPixelIntensitiesHisto)
Test multiple type as image input ... Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
ok
testShowAndHide (silx.gui.plot.test.testPlotTools.TestPixelIntensitiesHisto)
Simple test that the plot is showing and hiding when activating the ... Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
Log colormap with bound <= 1: changing bounds.
ok
testChangeLimitsWithAspectRatio (silx.gui.plot.test.testPlotWidget.TestPlotWidget) ... ok
testSetTitleLabels (silx.gui.plot.test.testPlotWidget.TestPlotWidget)
Set title and axes labels ... ok
testShow (silx.gui.plot.test.testPlotWidget.TestPlotWidget)
Most basic test ... ok
testImageOriginScale (silx.gui.plot.test.testPlotWidget.TestPlotImage)
Test of image with different origin and scale ... ok
testPlotColormapCustom (silx.gui.plot.test.testPlotWidget.TestPlotImage) ... ok
testPlotColormapGray (silx.gui.plot.test.testPlotWidget.TestPlotImage) ... ok
testPlotColormapTemperature (silx.gui.plot.test.testPlotWidget.TestPlotImage) ... ok
testPlotColormapTemperatureLog (silx.gui.plot.test.testPlotWidget.TestPlotImage) ... ok
testPlotRgbRgba (silx.gui.plot.test.testPlotWidget.TestPlotImage) ... ok
testPlotCurveColorByte (silx.gui.plot.test.testPlotWidget.TestPlotCurve) ... ok
testPlotCurveColorFloat (silx.gui.plot.test.testPlotWidget.TestPlotCurve) ... ok
testPlotCurveColors (silx.gui.plot.test.testPlotWidget.TestPlotCurve) ... ok
testPlotMarkerPt (silx.gui.plot.test.testPlotWidget.TestPlotMarker) ... ok
testPlotMarkerWithoutLegend (silx.gui.plot.test.testPlotWidget.TestPlotMarker) ... ok
testPlotMarkerX (silx.gui.plot.test.testPlotWidget.TestPlotMarker) ... ok
testPlotMarkerY (silx.gui.plot.test.testPlotWidget.TestPlotMarker) ... ok
testPlotItemPolygonFill (silx.gui.plot.test.testPlotWidget.TestPlotItem) ... ok
testPlotItemPolygonNoFill (silx.gui.plot.test.testPlotWidget.TestPlotItem) ... ok
testPlotItemRectangleFill (silx.gui.plot.test.testPlotWidget.TestPlotItem) ... ok
testPlotItemRectangleNoFill (silx.gui.plot.test.testPlotWidget.TestPlotItem) ... ok
testEmptyPlotTitleLabelsLog (silx.gui.plot.test.testPlotWidget.TestPlotEmptyLog) ... ok
testPlotCurveErrorLogXY (silx.gui.plot.test.testPlotWidget.TestPlotCurveLog) ... ok
testPlotCurveLogX (silx.gui.plot.test.testPlotWidget.TestPlotCurveLog) ... ok
testPlotCurveLogXY (silx.gui.plot.test.testPlotWidget.TestPlotCurveLog) ... ok
testPlotCurveLogY (silx.gui.plot.test.testPlotWidget.TestPlotCurveLog) ... ok
testPlotCurveToggleLog (silx.gui.plot.test.testPlotWidget.TestPlotCurveLog)
Add a curve with negative data and toggle log axis ... /usr/lib/python2.7/dist-packages/matplotlib/scale.py:100: RuntimeWarning: invalid value encountered in less_equal
  a[a <= 0.0] = 1e-300
/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/items/core.py:714: RuntimeWarning: All-NaN axis encountered
  numpy.nanmin(x),
/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/items/core.py:715: RuntimeWarning: All-NaN slice encountered
  numpy.nanmax(x),
/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/items/core.py:716: RuntimeWarning: All-NaN axis encountered
  numpy.nanmin(y),
/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/items/core.py:717: RuntimeWarning: All-NaN slice encountered
  numpy.nanmax(y)
/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/PlotWidget.py:520: RuntimeWarning: All-NaN axis encountered
  xMin = numpy.nanmin([xMin, bounds[0]])
/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/PlotWidget.py:521: RuntimeWarning: All-NaN axis encountered
  xMax = numpy.nanmax([xMax, bounds[1]])
/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/PlotWidget.py:528: RuntimeWarning: All-NaN axis encountered
  yMinLeft = numpy.nanmin([yMinLeft, bounds[2]])
/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/PlotWidget.py:529: RuntimeWarning: All-NaN axis encountered
  yMaxLeft = numpy.nanmax([yMaxLeft, bounds[3]])
ok
testPlotColormapGrayLogX (silx.gui.plot.test.testPlotWidget.TestPlotImageLog) ... ok
testPlotColormapGrayLogXY (silx.gui.plot.test.testPlotWidget.TestPlotImageLog) ... ok
testPlotColormapGrayLogY (silx.gui.plot.test.testPlotWidget.TestPlotImageLog) ... ok
testPlotRgbRgbaLogXY (silx.gui.plot.test.testPlotWidget.TestPlotImageLog) ... ok
testPlotMarkerPtLog (silx.gui.plot.test.testPlotWidget.TestPlotMarkerLog) ... ok
testPlotMarkerXLog (silx.gui.plot.test.testPlotWidget.TestPlotMarkerLog) ... ok
testPlotMarkerYLog (silx.gui.plot.test.testPlotWidget.TestPlotMarkerLog) ... ok
testPlotItemPolygonLogFill (silx.gui.plot.test.testPlotWidget.TestPlotItemLog) ... ok
testPlotItemPolygonLogNoFill (silx.gui.plot.test.testPlotWidget.TestPlotItemLog) ... ok
testPlotItemRectangleLogFill (silx.gui.plot.test.testPlotWidget.TestPlotItemLog) ... ok
testPlotItemRectangleLogNoFill (silx.gui.plot.test.testPlotWidget.TestPlotItemLog) ... ok

... i removed some logs...

Calculating octave 7
Octave 7 scale 0 blur with sigma 1.22627349847
Octave 7 scale 1 blur with sigma 1.54500779364
Octave 7 scale 2 blur with sigma 1.94658784146
Octave 7 scale 3 blur with sigma 2.45254699693
Octave 7 scale 4 blur with sigma 3.09001558729
Compact 0 -> 0 / 900000
Compact 0 -> 0 / 900000
Compact 0 -> 0 / 900000
in octave 7 found 0 kp
Execution time: 197.247ms
[[  5.09644653e-01]
 [  6.93721695e-01]
 [ -4.04438903e+02]
 [ -7.40845963e-01]
 [  9.96513237e-01]
 [  1.17361511e+03]]
Max error: 255.000000 at (1446, 1315)
minimal MSE according to least squares : 19.647030
Global execution time: CPU 358.482ms, GPU: 17.806ms.
Transformation took 5.208ms
ok

----------------------------------------------------------------------
Ran 972 tests in 91.654s

OK (skipped=2)
Skipped silx.gui.data.test.test_dataviewer.TestDataView.testCubeWithComplex (): OpenGL widget not yet tested
Skipped silx.io.test.test_specfile.TestSFLocale.test_locale_de_DE (): de_DE.utf8 locale not installed
Test suite succeeded
python: Fatal IO error 11 (Resource temporarily unavailable) on X server :2066.
```

```
> silx test -vv # this one will also display debug logs
```

### CODE REVIEW

**Comment by t20100** [comment]
My few comments:
- I would personally prefer to have a minimalistic `silx test` to avoid duplicating code between `run_tests.py` and the test command keeping in mind that `run_tests.py` can directly be used in other porjects. Other opinions?

- I would add `xvfbwrapper; sys_platform == 'linux'` to `requirements-dev.txt` to document that xvfbwrapper is an optional dependency of the project.
- If xvfbwrapper is optionally used by `silx test`, python-xvfbwrapper package should be added to the Debian dependencies as build-depends and recommends.

**Comment by vasole** [comment]
I would like to keep dependencies to a minimum. a different thing is to provide means to speed up testing for continuous integration.

To me ``silx test`` is just syntactic sugar compared to importing the tests and running them. At least is what I had in mind when we decided to have a minimalist ``silx test`` option.

**Comment by vasole** [comment]
Why is travis unhappy? I started again the tests this morning and it was fine for AppVeyor but not for Travis.

**Comment by vallsv** [comment]
About the minimalistic thing, I would say
- It is an application. Then at one point ones will would like to disable OpenCL tests, then others will would like to disable GUI... This part is quite a small thing (one argument and one line for each).
- Other things are needed to have a minimalistic output (plus a more verbose output if there is problem)

**Comment by vallsv** [comment]
The Travis conplain was a random one, i think.

**Comment by vallsv** [comment]
I will remove Xvfb from the tests. It's always crashing will using `xvfb-run` works just well.

**Comment by vallsv** [comment]
I implement few things, to display result when we cancel tests with CTRL-C (it was needed to have a cleaner implementation of the print of the skipped tests), and i redirect some text which was displayed by the `warnings` module.

If you think there is still too much command line arguments, we can remove everything.

**Pull request merged**
