### PR TITLE
Add parentheses around the file extension of the filters

### PR DESCRIPTION
**Pull request by mretegan**
A "cosmetic" fix that surrounds the filter's extension with parentheses, similar to other software, e.g. Qt Designer.

### CODE REVIEW

**Comment by vallsv** [comment]
Hi. Looks fine.

But there is a missing close parentheses for dat file, and extra spaces for one of the fmt.
Could you please fix that? You can see it easily in "Files changes".

**Comment by mretegan** [comment]
Should be fine now. Thanks!

**Comment by mretegan** [comment]
I had to make another commit with the updated date.

**Comment by vallsv** [comment]
THere is still a problem on `(*.dat")` -> `(*.dat)"`. Travis complain about that.

**Comment by t20100** [comment]
Looks good to me.
Thank you for the PR !

**Comment by vallsv** [comment]
Yep. It's fine. Thanks a lot.

**Pull request merged**
