### PR TITLE
[gui][stats] add pymca like widget for statistics

### PR DESCRIPTION
**Pull request by payno**
This class will be the base class of any widget displaying silx's statistic from a silx plot.

### CODE REVIEW

**Comment by payno** [comment]
tmp

**Comment by payno** [comment]
Example of how to use the BasicGridStatsWidget

```python
class FWHM(StatBase):
    """
    Simple calculation of the Full width half maximum
    """
    def __init__(self):
        StatBase.__init__(self, name='fwhm', compatibleKinds=('curve',))

    def calculate(self, context):
        # TODO
        pass

...

my_stats = DEFAULT_STATS
my_stats.add(stat=FWHM(), formatter=StatFormatter())
plot = Plot1D()

...

stats_widget = BasicGridStatsWidget(parent=None, stats=my_stats, plot=plot)
stats_widget.show()

```

**Comment by payno** [comment]
this should close #2007

**Comment by payno** [comment]
@mguijarr

I hope this will solve issue to include the statistics regarding curves on a Plot1D.
And you might want to  include an instance of `BasicGridStatsWidget` on your `LivePlot1D`.

A full example script is given below.

Please be aware that the fwhm implementation is just given as an example and is very 'raw'. But I guess you already have your own implementation of the fwhm.
This widget is limited to a specific kind.. Here 'curve'.

The current example will display only the statistic regarding the active curve.
Be also aware that displayed statistics will not take into account the viewport. So statistic will be made on the entire curve, no matter the viewport. (To change the behavior you can use the `statsOnVisibleData` option).

tmp

**Comment by payno** [comment]
```python
from silx.gui import qt
from silx.gui.colors import Colormap
from silx.gui.plot import Plot1D
from silx.gui.plot.stats.stats import StatBase
from silx.gui.plot.StatsWidget import BasicGridStatsWidget, DEFAULT_STATS
from silx.gui.plot.stats.statshandler import StatFormatter
import numpy
import logging

_logger = logging.getLogger()


class FWHM(StatBase):
    """
    Simple calculation of the Full width half maximum
    """
    def __init__(self):
        StatBase.__init__(self, name='fwhm', compatibleKinds=('curve',))

    def calculate(self, context):
        """
        warning: given if the function to be follows a normal distribution
        """
        y_max_value = context.max - context.min
        hm = y_max_value / 2.0
        index = numpy.argmax(context.values)
        # if has several index, return a numpy array
        if isinstance(index, numpy.ndarray):
            _logger.warning('more than one peak found fail to compute FHWM')
            return None

        left_index = (numpy.abs(context.values[0:index] - hm)).argmin()
        right_index = (numpy.abs(context.values[index:-1] - hm)).argmin()
        right_index = right_index + index

        # TODO: find the real intersection of the full fwhm to remove the
        return context.data[0][right_index] - context.data[0][left_index]


if __name__ == '__main__':
    _qapp = qt.QApplication([])
    my_stats = DEFAULT_STATS
    my_stats.add(stat=FWHM(), formatter=StatFormatter())
    plot = Plot1D()

    x = numpy.linspace(-2, 5, 5000)
    sigma = 0.5
    mu = 1.5
    y = 1.0 / (sigma * numpy.sqrt(2.0*numpy.pi)) * numpy.exp(-(x-mu)**2) / (2.0 * sigma**2)
    plot.addCurve(x=x, y=y, legend='normal-curve')
    plot.setActiveCurve('normal-curve')
    plot.show()

    stats_widget = BasicGridStatsWidget(parent=None, stats=my_stats, plot=plot)
    stats_widget.show()
    _qapp.exec_()
```

**Comment by vasole** [comment]
I would suggest the order COM mean STD instead of STD mean COM. It is much more common to see mean followed by STD than the other way around.

**Comment by vasole** [comment]
FAIL: testSetAnotherPlot (silx.gui.plot.test.testStats.TestStatsWidgetWithCurves)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\test\testStats.py", line 434, in testSetAnotherPlot
    self.assertEqual(self.widget.rowCount(), 1)
AssertionError: 0 != 1

**Pull request merged**
