### PR TITLE
Display title in the type field.

### LINKED ISSUE #2713: [silx view] show NXentry title
Could Silx show the NXentry title in the viewer? NXentry names are typically chosen for easy access by software (e.g. just a number) but are not very informative for humans.

### PR DESCRIPTION
**Pull request by vasole**
closes #2713

image

### CODE REVIEW

**Comment by vallsv** [comment]
What about changing the description name, instead of the node name, it is also part of the tree? I think it would be really better.

I mean, it's like having custom magic filename and directory in your file system... Hmmm somebody just told me that Windows is doing that...

**Comment by vasole** [comment]
The problem is the description filed is too far to the right.

**Comment by vasole** [comment]
As it is now, the node name is not changed, only the type displayed.

I considered that to change the node name would be too risky

**Comment by vasole** [comment]
Sorry, the value is what is too far to the right.

image

**Comment by vallsv** [comment]
Also cause your change grow up the type-column ;-)

Value could be a better place, shape could be moved after value.

BTW, in case, you can reorder columns with the mouse, and hide/display things with the right mouse.

**Comment by vasole** [comment]
It seems there is a problem with PySide2.

**Comment by t20100** [comment]
Ideas from a brief discussion with @vasole:
- What about using the `Value` column for `NXEntry` title and moving the `Value` column to be the 2nd one.
- Alternative: Add a `Description` column as 2nd column which content varies according to the dataset/group: title for `NXEntry`, NXClass for other nexus groups, value for scalars, dtype+shape for other datasets...

**Comment by t20100** [comment]
closing as superseded by PR #2804

**Pull request closed without merging**
