### PR TITLE
[plot3d] SceneView widget and associated items

### PR DESCRIPTION
**Pull request by t20100**
This PR provides a `silx.gui.plot3d.SceneWidget` widget, a `SceneWindow` and a `silx.gui.plot3d.items` package for describing/manipulating its content.
It aims at providing an API similar to `silx.gui.plot.items`.

Related to #1311

PR to merge first (cherry-picked here):
- [x] #1326
- [x] #1342
- [x] #1343
- [x] #1353
- [x] #1362

### CODE REVIEW

**Comment by t20100** [comment]
This PR provides the public API of a general purpose 3D plotting widget through a `SceneView` widget and classes in `items` package to describe its content.
This PR also provides a first sample code (plot3dSceneView.py) and some documentation of the API.

It is another step towards #1311.

More features will be added, but the general idea of the proposed public API is there, feedbacks on it warmly welcome before it gets released....

Once #1362 is merged (cherry-picked here), this is ready for review.

**Comment by PiRK** [comment]
The API looks good, from what I saw in the example.

**Comment by payno** [comment]
API seems good for me to.

The only think I would change would be for 

`getSupportedVisualizationModes` and `getVisualizationModeUnusedProperties` and go for shorter names like using 'vis' for 'visualization' but my point of view only

**Comment by t20100** [comment]
@payno, what about  `getUnusedProperties`?

For `getSupportedVisualizationModes`, it matches `get|setVisualizationMode`, so I can propose either to rename it to `supportedVisualizationModes` (a 3 charaters win) or
rename all three to `getSupportedVisualizations` (or `supportedVisualizations`) and `get|setVisualization`.
If possible I would prefer to avoid abbreviation and I find 'get|setMode' too generic.

**Comment by t20100** [comment]
I have a few minor fixes to do on it.

**Comment by t20100** [comment]
I replaced  `getUnusedProperties(mode=None)` by `isPropertyEnabled(name, visualization=None)`, and renamed `getSupportedVisualizationMode` to `supportedVisualization`.
No other changes in the end.

**Comment by payno** [comment]
Good from my POV

**Pull request merged**
