### PR TITLE
Hide displayed tools when the plot is not anymore visible

### LINKED ISSUE #2109: [NXdata] and histogram
There are two bug, the first one is easy, the second more nasty:
* [ ] The histogram button exists in the default image viewer but not in the NXdata image viewer. It would be nice it could be consistent.
* [ ] The histogram only applies when it is called for the first time. It gets updated when changing the image to another image, but not when changing to an NXdata image display.

### PR DESCRIPTION
**Pull request by vallsv**
The PlotAction manage to displayed tool, and hide it if expected.

Applyed on histo, medfilt, and fit actions

Closes #2109

### CODE REVIEW

**Comment by t20100** [comment]
`sigVisibilityChanged` should be added to `PlotWidget` rather than `PlotWindow` as plot actions should work with `PlotWidget`.

Otherwise it's OK for me.

**Comment by vallsv** [comment]
Yes you are right.

**Comment by t20100** [comment]
To complete it, `showEvent` and `hideEvent` still need to be move in `PlotWidget`

**Comment by vallsv** [comment]
Oups, you are right again.

**Comment by vallsv** [comment]
It's done now

**Pull request merged**
