### PR TITLE
[plot] Refactoring of ComplexImageView

### PR DESCRIPTION
**Pull request by t20100**
This PR provides a refactoring of `ComplexImageView` widget.
This provides:
- A new plot item: `ImageComplexData`
- The `ComplexImageView` uses this item and part of its API is now a proxy to this item.

This should ease treatment specific to complex (e.g., #1493)

### CODE REVIEW

**Comment by t20100** [comment]
TODO: The `getData` needs caching

**Comment by t20100** [comment]
Caching added to `getData`

**Comment by vallsv** [comment]
LGTM

**Comment by vallsv** [comment]
It would be better to have a reflexivity between `getData/setData`, but as an internal object it's fine.

**Comment by t20100** [comment]
I'm not happy with `ImageComplexData.get|setData` either.
The only point for this solution is that it is compatible with `ImageData.getData` returning a float32 2D array... so with code using it.

**Pull request merged**
