### PR TITLE
[silx view] Add a sorting toggle action to the browser tree

### LINKED ISSUE #3128: silx view track_order
Any ideas why silx view doesn't keep the order of the keys?

```python
import h5py

h5py.get_config().track_order = True

filename = "test.h5"
with h5py.File(filename, "w") as h5:
    params = h5.create_group("params")
    params["z"] = 10
    params["a"] = 2
    print(params.keys())

with h5py.File(filename, "r") as h5:
    print(h5["params"].keys())
``` 

```
<KeysViewHDF5 ['z', 'a']>
<KeysViewHDF5 ['z', 'a']>
```

`silx view test.h5`

Screenshot 2020-06-15 at 14 46 45

### PR DESCRIPTION
**Pull request by t20100**
This PR adds an action on top of the tree to toggle sorting of the tree and its content.

TODO: Icon is missing, anyone feeling like drawing a nice `sort` icon?

closes #3128

### CODE REVIEW

**Comment by vallsv** [comment]
Sure, i can do it

**Comment by t20100** [comment]
Thanks @mretegan and @vallsv for contributions!

**Comment by t20100** [comment]
Question: Do we want this in `0.13` or `0.14` ?

**Comment by mretegan** [comment]
For me, there is no urgency to have this. On the other hand, it is a simple issue. Do as you see fit.

**Comment by t20100** [comment]
Rebased to 0.13

**Pull request merged**
