### PR TITLE
Allow build under windows.

### PR DESCRIPTION
**Pull request by vasole**
Addresses #9

### CODE REVIEW

**Comment by kif** [comment]
2 comments: 

1. one should probably use "os.path.dirname(os.path.abspath(__file__) )" instead of "os.path.dirname(__file__)", especially in setup.py which under certain circumstances results in "".

2. this "urgent pull request" highlights the lack of test for the given feature. The continuous integration tool did not spot it.

**Comment by vasole** [comment]
On 06.03.2016 09:40, Jerome Kieffer wrote:
> 2 comments:
> 
> one should probably use "os.path.dirname(os.path.abspath(FILE) )"
> instead of "os.path.dirname(FILE)", especially in setup.py which under
> certain circumstances results in "".
> 

- Yes

> 
> this "urgent pull request" highlights the lack of test for the given
> feature. The continuous integration tool did not spot it.
> 

Things to be solved {are they worth a specific issue?):

- How can we test build without Cython besides build without Cython? Can 
we specify two builds?

- Same as above but running the build of the sources generated with 
sdist.

**Comment by vasole** [comment]
- If possible, I would aim for the continuous integration tests to be run on the sources generated by sdist and not on a repository copy.

- I guess the build from the git sources is tested almost every day :-)

**Comment by t20100** [comment]
+1 for test from sdist and without Cython in at least 1 CI.
See issue #12

**Pull request merged**
