### PR TITLE
Fix FitAction support of Y right axis 

### LINKED ISSUE #2968: [plot] Fit action do work on y2
It looks like curves from y2 can't by fit.

It would be good to allow that and to create the fitted curve inside the y2 axis.

### PR DESCRIPTION
**Pull request by t20100**
This PR makes the `FitAction` work with curves on the right Y axis.
It also deprecates the `legend` attribute.

closes #2968

### CODE REVIEW

**Comment by vallsv** [comment]
Tested, approved. I have just restarted the CI.

**Comment by vallsv** [comment]
Fail again. Looks to be a segfault on PySide2 again.

**Comment by t20100** [comment]
Yes and not reproduced locally....

**Comment by t20100** [comment]
No way to reproduce locally so far, that is going to be painful...

**Comment by t20100** [comment]
Now tests pass with `PySide2` on Windows but fail with `PyQt5` everywhere...

**Comment by t20100** [comment]
Looks to be fixed! Ready for review.
It was a funny weird bug....

**Comment by vallsv** [comment]
Good time to switch to PySide2 then?

**Comment by vallsv** [comment]
LGTM

**Pull request merged**
