### PR TITLE
Add an irregular grid rendering mode for scatter plots

### LINKED ISSUE #2743: [plot] Add a solid regular display mode for scatter
The main idea is to render a scatter in a "pixel based" way. But not to render a image using the same pixel size.

Here is constraints which i think are useful for the readability.

- The polygons should have mostly the same surface
- The polygons can be quadrilateral, i don't think we need a real voronoi rendering
- The polygons have to be mostly centered around the location of each points

scatter-solid

I don't need to display the |symbols at the location points. I can do it with another scatter item.

Relative to #2709

### PR DESCRIPTION
**Pull request by t20100**
This PR adds an irregular grid mode to scatter plot visualization.
It provides a way to visualize the data as an irregular grid.

I would consider it an experimental feature to see what it can provide.

Todo: testing, picking.. optimization probably

closes #2743

### CODE REVIEW

**Comment by t20100** [comment]
Few fixes: picking (with OpenGL at least), dimension < 2 check.
Main remaining issue is with column-major grid.

**Comment by t20100** [comment]
column-major grid working.

ready for review.

**Comment by vallsv** [comment]
LGTM except few things.

- The very first line is not rendered (that is not a big problem as far as i can know nothing is rendered)
- The last incomplit line is not rendered (here it is more problematic), if it is not too difficult to do it i really would like to have that.

I will merge it anyway.

**Comment by vallsv** [comment]
Anyway, don't worry, that's already very nice to show what we can do.

**Comment by t20100** [comment]
Yes, as it is, it only works with more than 2 lines and only displays complete lines.
This can be supported but not in this release.

**Pull request merged**
