### PR TITLE
opencl/codec/test/test_bitshuffle_lz4: Fixed bitshuffle import error

### PR DESCRIPTION
**Pull request by woutdenolf**
Checklist:

- [x] The PR title is formatted as: `<Module or Topic>: <Action> <Summary>` (see [contributing guidelines](https://github.com/silx-kit/silx/blob/main/CONTRIBUTING.rst#pull-request-title-format))

<hr>

### CODE REVIEW

**Comment by woutdenolf** [comment]
The github release workflow gives this error

```
Run python -c "import silx.test, sys; sys.exit(silx.test.run_tests(verbosity=3))"
============================= test session starts ==============================
platform linux -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0 -- /opt/hostedtoolcache/Python/3.12.4/x64/bin/python
cachedir: .pytest_cache
rootdir: /home/runner/work/silx/silx
configfile: pytest.ini
plugins: xvfb-3.0.0, mock-3.14.0
collecting ... collected 2525 items / 1 error

==================================== ERRORS ====================================
__________ ERROR collecting opencl/codec/test/test_bitshuffle_lz4.py ___________
/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/silx/opencl/codec/test/test_bitshuffle_lz4.py:44: in <module>
    import bitshuffle
/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/bitshuffle/__init__.py:24: in <module>
    from bitshuffle.ext import (
bitshuffle/ext.pyx:1: in init bitshuffle.ext
    ???
E   ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by woutdenolf** [comment]
Ping @t20100

**Review by payno — APPROVED** [review]

**Comment by payno** [comment]
@t20100 we encountered some troubles with opencl, but only with the 'release' workflow. the 'ci' workflow was working properly.
But from what I remenber the pyopcenl stuff can be a bit 'sensitive'

**Comment by t20100** [comment]
That sounds due to `bitshuffle` wheels not being compatible with numpy v2...

**Pull request merged**
