### PR TITLE
Display pencil preview in mask tool

### PR DESCRIPTION
**Pull request by vallsv**
This PR display the shape preview of the pensil on the mask tool

There is efficiency problems with the pencil. That's why it is in WIP. It must be investigated.

### CODE REVIEW

**Comment by vallsv** [comment]
Here is an update. On my computer it is still slow with a big pencil.

@t20100 I would like input, cause i would like to know the best way to do thinks.

I update `DrawFreeHand` to look like the previous implementation. Then now i use a single polyline for all the drag.

Previously i was using a polyline of 2 points for each mouse move:
```
event, len(polyline), polyline
('prepareDrawingSignal progress', 2, [(303.31139240506332, 692.95342465753424), (841.37946554149084, 677.9908675799087)])
('prepareDrawingSignal progress', 2, [(841.37946554149084, 677.9908675799087), (851.74908579465546, 640.58447488584477)])
('prepareDrawingSignal progress', 2, [(851.74908579465546, 640.58447488584477), (851.74908579465546, 633.10319634703194)])
('prepareDrawingSignal progress', 2, [(851.74908579465546, 633.10319634703194), (851.74908579465546, 606.91872146118726)])
('prepareDrawingSignal progress', 2, [(851.74908579465546, 606.91872146118726), (847.14036568213783, 2.8421709430404007e-14)])
('prepareDrawingSignal end,       2, [(851.74908579465546, 606.91872146118726), (847.14036568213783, 2.8421709430404007e-14)])
```
Now it is:
```
event, len(polyline), polyline
('prepareDrawingSignal progress', 1, [(303.31139240506332, 692.95342465753424)])
('prepareDrawingSignal progress', 2, [(303.31139240506332, 692.95342465753424), (841.37946554149084, 677.9908675799087)])
('prepareDrawingSignal progress', 3, [(303.31139240506332, 692.95342465753424), (841.37946554149084, 677.9908675799087), (851.74908579465546, 640.58447488584477)])
('prepareDrawingSignal progress', 4, [(303.31139240506332, 692.95342465753424), (841.37946554149084, 677.9908675799087), (851.74908579465546, 640.58447488584477), (851.74908579465546, 633.10319634703194)])
('prepareDrawingSignal progress', 5, [(303.31139240506332, 692.95342465753424), (841.37946554149084, 677.9908675799087), (851.74908579465546, 640.58447488584477), (851.74908579465546, 633.10319634703194), (851.74908579465546, 606.91872146118726)])
('prepareDrawingSignal progress', 6, [(303.31139240506332, 692.95342465753424), (841.37946554149084, 677.9908675799087), (851.74908579465546, 640.58447488584477), (851.74908579465546, 633.10319634703194), (851.74908579465546, 606.91872146118726), (847.14036568213783, 2.8421709430404007e-14)])
('prepareDrawingSignal end',      6, [(303.31139240506332, 692.95342465753424), (841.37946554149084, 677.9908675799087), (851.74908579465546, 640.58447488584477), (851.74908579465546, 633.10319634703194), (851.74908579465546, 606.91872146118726), (847.14036568213783, 2.8421709430404007e-14)])
```
What it is the better way? Cause i quest now there is more computation while the polyline is updated.
BTW i guess we can trunc the floats to filter some points? or it does not make sens.

**Comment by vallsv** [comment]
This PR can now be merged.
- It display the profile of the pencil tool before clicking on the picture
- Is also contains a refactoring of the drawing mode to fix the amount of drawing callback (which was creating efficiency issue)

**Comment by vallsv** [comment]
It should be ok now. I add another commit to be able to select the qt binding when launching unittests (--qt-binding)

**Comment by t20100** [comment]
There is an issue when the interaction mode is changed from elsewhere the pencil keeps drawing (e.g., with imageview example: select mask draw mode and then select profile line from the toolbar).

I made a few fix in this PR on your branch: https://github.com/vallsv/silx/pull/3

Otherwise, looks good to me.

**Comment by vallsv** [comment]
Thanks for the PR. I cherry picked it, and i this this last issues (unhided selection and buggy release of the interactive mode). It should be fine now.

**Pull request merged**
