### PR TITLE
silx.gui.hdf5: Made humanReadableHdf5Type a static method of Hdf5Formatter

### PR DESCRIPTION
**Pull request by loichuder**
...to be able to reuse it more easily in other (non-Qt) projects.

### CODE REVIEW

**Comment by vallsv** [comment]
I don't think it's a good idea.

Here it is object oriented. If you want to use it outside, i think it is better to move the function outside. And use the normal function in the method if you like.

**Comment by loichuder** [comment]
> Here it is object oriented. If you want to use it outside, i think it is better to move the function outside. And use the normal function in the method if you like.

You mean copying the function _outside of the silx project_ or _outside of the class_ ?

**Comment by vallsv** [comment]
Outside the class. And if you don't want to use it in Qt context, that's probably better to move it out the this package anyway.

**Comment by loichuder** [comment]
Yeah, in the end, I think I will copy paste the function in our project to avoid pulling `silx` as a dep just for that.

Thanks :+1:

**Pull request closed without merging**
